package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Certmapping generated by hbm2java
 */
@Entity
@Table(name="certmapping"
)
public class Certmapping  implements java.io.Serializable {


     private CertmappingId id;

    public Certmapping() {
    }

    public Certmapping(CertmappingId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="rpolicyno", column=@Column(name="rpolicyno") ), 
        @AttributeOverride(name="rpolicyn", column=@Column(name="rpolicyn") ) } )
    public CertmappingId getId() {
        return this.id;
    }
    
    public void setId(CertmappingId id) {
        this.id = id;
    }




}


