package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertriderId generated by hbm2java
 */
@Embeddable
public class CertriderId  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String ridertype;
     private String sum;
     private String premium;
     private String extrapremium;
     private String riderstatus;
     private String riderstatusdate;
     private String reserve;

    public CertriderId() {
    }

    public CertriderId(String policyno, String certno, String ridertype, String sum, String premium, String extrapremium, String riderstatus, String riderstatusdate, String reserve) {
       this.policyno = policyno;
       this.certno = certno;
       this.ridertype = ridertype;
       this.sum = sum;
       this.premium = premium;
       this.extrapremium = extrapremium;
       this.riderstatus = riderstatus;
       this.riderstatusdate = riderstatusdate;
       this.reserve = reserve;
    }
   

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="ridertype")
    public String getRidertype() {
        return this.ridertype;
    }
    
    public void setRidertype(String ridertype) {
        this.ridertype = ridertype;
    }

    @Column(name="sum")
    public String getSum() {
        return this.sum;
    }
    
    public void setSum(String sum) {
        this.sum = sum;
    }

    @Column(name="premium")
    public String getPremium() {
        return this.premium;
    }
    
    public void setPremium(String premium) {
        this.premium = premium;
    }

    @Column(name="extrapremium")
    public String getExtrapremium() {
        return this.extrapremium;
    }
    
    public void setExtrapremium(String extrapremium) {
        this.extrapremium = extrapremium;
    }

    @Column(name="riderstatus")
    public String getRiderstatus() {
        return this.riderstatus;
    }
    
    public void setRiderstatus(String riderstatus) {
        this.riderstatus = riderstatus;
    }

    @Column(name="riderstatusdate")
    public String getRiderstatusdate() {
        return this.riderstatusdate;
    }
    
    public void setRiderstatusdate(String riderstatusdate) {
        this.riderstatusdate = riderstatusdate;
    }

    @Column(name="reserve")
    public String getReserve() {
        return this.reserve;
    }
    
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CertriderId) ) return false;
		 CertriderId castOther = ( CertriderId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getRidertype()==castOther.getRidertype()) || ( this.getRidertype()!=null && castOther.getRidertype()!=null && this.getRidertype().equals(castOther.getRidertype()) ) )
 && ( (this.getSum()==castOther.getSum()) || ( this.getSum()!=null && castOther.getSum()!=null && this.getSum().equals(castOther.getSum()) ) )
 && ( (this.getPremium()==castOther.getPremium()) || ( this.getPremium()!=null && castOther.getPremium()!=null && this.getPremium().equals(castOther.getPremium()) ) )
 && ( (this.getExtrapremium()==castOther.getExtrapremium()) || ( this.getExtrapremium()!=null && castOther.getExtrapremium()!=null && this.getExtrapremium().equals(castOther.getExtrapremium()) ) )
 && ( (this.getRiderstatus()==castOther.getRiderstatus()) || ( this.getRiderstatus()!=null && castOther.getRiderstatus()!=null && this.getRiderstatus().equals(castOther.getRiderstatus()) ) )
 && ( (this.getRiderstatusdate()==castOther.getRiderstatusdate()) || ( this.getRiderstatusdate()!=null && castOther.getRiderstatusdate()!=null && this.getRiderstatusdate().equals(castOther.getRiderstatusdate()) ) )
 && ( (this.getReserve()==castOther.getReserve()) || ( this.getReserve()!=null && castOther.getReserve()!=null && this.getReserve().equals(castOther.getReserve()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getRidertype() == null ? 0 : this.getRidertype().hashCode() );
         result = 37 * result + ( getSum() == null ? 0 : this.getSum().hashCode() );
         result = 37 * result + ( getPremium() == null ? 0 : this.getPremium().hashCode() );
         result = 37 * result + ( getExtrapremium() == null ? 0 : this.getExtrapremium().hashCode() );
         result = 37 * result + ( getRiderstatus() == null ? 0 : this.getRiderstatus().hashCode() );
         result = 37 * result + ( getRiderstatusdate() == null ? 0 : this.getRiderstatusdate().hashCode() );
         result = 37 * result + ( getReserve() == null ? 0 : this.getReserve().hashCode() );
         return result;
   }   


}


