package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Certrider generated by hbm2java
 */
@Entity
@Table(name="certrider"
)
public class Certrider  implements java.io.Serializable {


     private CertriderId id;

    public Certrider() {
    }

    public Certrider(CertriderId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="ridertype", column=@Column(name="ridertype") ), 
        @AttributeOverride(name="sum", column=@Column(name="sum") ), 
        @AttributeOverride(name="premium", column=@Column(name="premium") ), 
        @AttributeOverride(name="extrapremium", column=@Column(name="extrapremium") ), 
        @AttributeOverride(name="riderstatus", column=@Column(name="riderstatus") ), 
        @AttributeOverride(name="riderstatusdate", column=@Column(name="riderstatusdate") ), 
        @AttributeOverride(name="reserve", column=@Column(name="reserve") ) } )
    public CertriderId getId() {
        return this.id;
    }
    
    public void setId(CertriderId id) {
        this.id = id;
    }




}


