package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertId generated by hbm2java
 */
@Embeddable
public class CertId  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String appno;
     private String reqdate;
     private String nameid;
     private String age;
     private String smi;
     private String lifesum;
     private String accidentsum;
     private String period;
     private String loanTerm;
     private String lifepremium;
     private String extrapremium;
     private String tpdpremium;
     private String extratpdpremium;
     private String addpremium;
     private String em;
     private String tpd;
     private String effectivedate;
     private String maturedate;
     private String premiumdate;
     private String certyyyymm;
     private String statcer;
     private String statcer2;
     private String statdate2;
     private String informdate1;
     private String paydate1;
     private String amount1;
     private String informdate2;
     private String paydate2;
     private String amount2;
     private String deaddate;
     private String endownmentyear;
     private String deadcause;
     private String receiptflag;
     private String referenceno;
     private String reserve;

    public CertId() {
    }

    public CertId(String policyno, String certno, String appno, String reqdate, String nameid, String age, String smi, String lifesum, String accidentsum, String period, String loanTerm, String lifepremium, String extrapremium, String tpdpremium, String extratpdpremium, String addpremium, String em, String tpd, String effectivedate, String maturedate, String premiumdate, String certyyyymm, String statcer, String statcer2, String statdate2, String informdate1, String paydate1, String amount1, String informdate2, String paydate2, String amount2, String deaddate, String endownmentyear, String deadcause, String receiptflag, String referenceno, String reserve) {
       this.policyno = policyno;
       this.certno = certno;
       this.appno = appno;
       this.reqdate = reqdate;
       this.nameid = nameid;
       this.age = age;
       this.smi = smi;
       this.lifesum = lifesum;
       this.accidentsum = accidentsum;
       this.period = period;
       this.loanTerm = loanTerm;
       this.lifepremium = lifepremium;
       this.extrapremium = extrapremium;
       this.tpdpremium = tpdpremium;
       this.extratpdpremium = extratpdpremium;
       this.addpremium = addpremium;
       this.em = em;
       this.tpd = tpd;
       this.effectivedate = effectivedate;
       this.maturedate = maturedate;
       this.premiumdate = premiumdate;
       this.certyyyymm = certyyyymm;
       this.statcer = statcer;
       this.statcer2 = statcer2;
       this.statdate2 = statdate2;
       this.informdate1 = informdate1;
       this.paydate1 = paydate1;
       this.amount1 = amount1;
       this.informdate2 = informdate2;
       this.paydate2 = paydate2;
       this.amount2 = amount2;
       this.deaddate = deaddate;
       this.endownmentyear = endownmentyear;
       this.deadcause = deadcause;
       this.receiptflag = receiptflag;
       this.referenceno = referenceno;
       this.reserve = reserve;
    }
   

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="appno")
    public String getAppno() {
        return this.appno;
    }
    
    public void setAppno(String appno) {
        this.appno = appno;
    }

    @Column(name="reqdate")
    public String getReqdate() {
        return this.reqdate;
    }
    
    public void setReqdate(String reqdate) {
        this.reqdate = reqdate;
    }

    @Column(name="nameid")
    public String getNameid() {
        return this.nameid;
    }
    
    public void setNameid(String nameid) {
        this.nameid = nameid;
    }

    @Column(name="age")
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }

    @Column(name="smi")
    public String getSmi() {
        return this.smi;
    }
    
    public void setSmi(String smi) {
        this.smi = smi;
    }

    @Column(name="lifesum")
    public String getLifesum() {
        return this.lifesum;
    }
    
    public void setLifesum(String lifesum) {
        this.lifesum = lifesum;
    }

    @Column(name="accidentsum")
    public String getAccidentsum() {
        return this.accidentsum;
    }
    
    public void setAccidentsum(String accidentsum) {
        this.accidentsum = accidentsum;
    }

    @Column(name="period")
    public String getPeriod() {
        return this.period;
    }
    
    public void setPeriod(String period) {
        this.period = period;
    }

    @Column(name="loan_term")
    public String getLoanTerm() {
        return this.loanTerm;
    }
    
    public void setLoanTerm(String loanTerm) {
        this.loanTerm = loanTerm;
    }

    @Column(name="lifepremium")
    public String getLifepremium() {
        return this.lifepremium;
    }
    
    public void setLifepremium(String lifepremium) {
        this.lifepremium = lifepremium;
    }

    @Column(name="extrapremium")
    public String getExtrapremium() {
        return this.extrapremium;
    }
    
    public void setExtrapremium(String extrapremium) {
        this.extrapremium = extrapremium;
    }

    @Column(name="tpdpremium")
    public String getTpdpremium() {
        return this.tpdpremium;
    }
    
    public void setTpdpremium(String tpdpremium) {
        this.tpdpremium = tpdpremium;
    }

    @Column(name="extratpdpremium")
    public String getExtratpdpremium() {
        return this.extratpdpremium;
    }
    
    public void setExtratpdpremium(String extratpdpremium) {
        this.extratpdpremium = extratpdpremium;
    }

    @Column(name="addpremium")
    public String getAddpremium() {
        return this.addpremium;
    }
    
    public void setAddpremium(String addpremium) {
        this.addpremium = addpremium;
    }

    @Column(name="em")
    public String getEm() {
        return this.em;
    }
    
    public void setEm(String em) {
        this.em = em;
    }

    @Column(name="tpd")
    public String getTpd() {
        return this.tpd;
    }
    
    public void setTpd(String tpd) {
        this.tpd = tpd;
    }

    @Column(name="effectivedate")
    public String getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(String effectivedate) {
        this.effectivedate = effectivedate;
    }

    @Column(name="maturedate")
    public String getMaturedate() {
        return this.maturedate;
    }
    
    public void setMaturedate(String maturedate) {
        this.maturedate = maturedate;
    }

    @Column(name="premiumdate")
    public String getPremiumdate() {
        return this.premiumdate;
    }
    
    public void setPremiumdate(String premiumdate) {
        this.premiumdate = premiumdate;
    }

    @Column(name="certyyyymm")
    public String getCertyyyymm() {
        return this.certyyyymm;
    }
    
    public void setCertyyyymm(String certyyyymm) {
        this.certyyyymm = certyyyymm;
    }

    @Column(name="statcer")
    public String getStatcer() {
        return this.statcer;
    }
    
    public void setStatcer(String statcer) {
        this.statcer = statcer;
    }

    @Column(name="statcer2")
    public String getStatcer2() {
        return this.statcer2;
    }
    
    public void setStatcer2(String statcer2) {
        this.statcer2 = statcer2;
    }

    @Column(name="statdate2")
    public String getStatdate2() {
        return this.statdate2;
    }
    
    public void setStatdate2(String statdate2) {
        this.statdate2 = statdate2;
    }

    @Column(name="informdate1")
    public String getInformdate1() {
        return this.informdate1;
    }
    
    public void setInformdate1(String informdate1) {
        this.informdate1 = informdate1;
    }

    @Column(name="paydate1")
    public String getPaydate1() {
        return this.paydate1;
    }
    
    public void setPaydate1(String paydate1) {
        this.paydate1 = paydate1;
    }

    @Column(name="amount1")
    public String getAmount1() {
        return this.amount1;
    }
    
    public void setAmount1(String amount1) {
        this.amount1 = amount1;
    }

    @Column(name="informdate2")
    public String getInformdate2() {
        return this.informdate2;
    }
    
    public void setInformdate2(String informdate2) {
        this.informdate2 = informdate2;
    }

    @Column(name="paydate2")
    public String getPaydate2() {
        return this.paydate2;
    }
    
    public void setPaydate2(String paydate2) {
        this.paydate2 = paydate2;
    }

    @Column(name="amount2")
    public String getAmount2() {
        return this.amount2;
    }
    
    public void setAmount2(String amount2) {
        this.amount2 = amount2;
    }

    @Column(name="deaddate")
    public String getDeaddate() {
        return this.deaddate;
    }
    
    public void setDeaddate(String deaddate) {
        this.deaddate = deaddate;
    }

    @Column(name="endownmentyear ")
    public String getEndownmentyear() {
        return this.endownmentyear;
    }
    
    public void setEndownmentyear(String endownmentyear) {
        this.endownmentyear = endownmentyear;
    }

    @Column(name="deadcause")
    public String getDeadcause() {
        return this.deadcause;
    }
    
    public void setDeadcause(String deadcause) {
        this.deadcause = deadcause;
    }

    @Column(name="receiptflag  ")
    public String getReceiptflag() {
        return this.receiptflag;
    }
    
    public void setReceiptflag(String receiptflag) {
        this.receiptflag = receiptflag;
    }

    @Column(name="referenceno ")
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    @Column(name="reserve")
    public String getReserve() {
        return this.reserve;
    }
    
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CertId) ) return false;
		 CertId castOther = ( CertId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAppno()==castOther.getAppno()) || ( this.getAppno()!=null && castOther.getAppno()!=null && this.getAppno().equals(castOther.getAppno()) ) )
 && ( (this.getReqdate()==castOther.getReqdate()) || ( this.getReqdate()!=null && castOther.getReqdate()!=null && this.getReqdate().equals(castOther.getReqdate()) ) )
 && ( (this.getNameid()==castOther.getNameid()) || ( this.getNameid()!=null && castOther.getNameid()!=null && this.getNameid().equals(castOther.getNameid()) ) )
 && ( (this.getAge()==castOther.getAge()) || ( this.getAge()!=null && castOther.getAge()!=null && this.getAge().equals(castOther.getAge()) ) )
 && ( (this.getSmi()==castOther.getSmi()) || ( this.getSmi()!=null && castOther.getSmi()!=null && this.getSmi().equals(castOther.getSmi()) ) )
 && ( (this.getLifesum()==castOther.getLifesum()) || ( this.getLifesum()!=null && castOther.getLifesum()!=null && this.getLifesum().equals(castOther.getLifesum()) ) )
 && ( (this.getAccidentsum()==castOther.getAccidentsum()) || ( this.getAccidentsum()!=null && castOther.getAccidentsum()!=null && this.getAccidentsum().equals(castOther.getAccidentsum()) ) )
 && ( (this.getPeriod()==castOther.getPeriod()) || ( this.getPeriod()!=null && castOther.getPeriod()!=null && this.getPeriod().equals(castOther.getPeriod()) ) )
 && ( (this.getLoanTerm()==castOther.getLoanTerm()) || ( this.getLoanTerm()!=null && castOther.getLoanTerm()!=null && this.getLoanTerm().equals(castOther.getLoanTerm()) ) )
 && ( (this.getLifepremium()==castOther.getLifepremium()) || ( this.getLifepremium()!=null && castOther.getLifepremium()!=null && this.getLifepremium().equals(castOther.getLifepremium()) ) )
 && ( (this.getExtrapremium()==castOther.getExtrapremium()) || ( this.getExtrapremium()!=null && castOther.getExtrapremium()!=null && this.getExtrapremium().equals(castOther.getExtrapremium()) ) )
 && ( (this.getTpdpremium()==castOther.getTpdpremium()) || ( this.getTpdpremium()!=null && castOther.getTpdpremium()!=null && this.getTpdpremium().equals(castOther.getTpdpremium()) ) )
 && ( (this.getExtratpdpremium()==castOther.getExtratpdpremium()) || ( this.getExtratpdpremium()!=null && castOther.getExtratpdpremium()!=null && this.getExtratpdpremium().equals(castOther.getExtratpdpremium()) ) )
 && ( (this.getAddpremium()==castOther.getAddpremium()) || ( this.getAddpremium()!=null && castOther.getAddpremium()!=null && this.getAddpremium().equals(castOther.getAddpremium()) ) )
 && ( (this.getEm()==castOther.getEm()) || ( this.getEm()!=null && castOther.getEm()!=null && this.getEm().equals(castOther.getEm()) ) )
 && ( (this.getTpd()==castOther.getTpd()) || ( this.getTpd()!=null && castOther.getTpd()!=null && this.getTpd().equals(castOther.getTpd()) ) )
 && ( (this.getEffectivedate()==castOther.getEffectivedate()) || ( this.getEffectivedate()!=null && castOther.getEffectivedate()!=null && this.getEffectivedate().equals(castOther.getEffectivedate()) ) )
 && ( (this.getMaturedate()==castOther.getMaturedate()) || ( this.getMaturedate()!=null && castOther.getMaturedate()!=null && this.getMaturedate().equals(castOther.getMaturedate()) ) )
 && ( (this.getPremiumdate()==castOther.getPremiumdate()) || ( this.getPremiumdate()!=null && castOther.getPremiumdate()!=null && this.getPremiumdate().equals(castOther.getPremiumdate()) ) )
 && ( (this.getCertyyyymm()==castOther.getCertyyyymm()) || ( this.getCertyyyymm()!=null && castOther.getCertyyyymm()!=null && this.getCertyyyymm().equals(castOther.getCertyyyymm()) ) )
 && ( (this.getStatcer()==castOther.getStatcer()) || ( this.getStatcer()!=null && castOther.getStatcer()!=null && this.getStatcer().equals(castOther.getStatcer()) ) )
 && ( (this.getStatcer2()==castOther.getStatcer2()) || ( this.getStatcer2()!=null && castOther.getStatcer2()!=null && this.getStatcer2().equals(castOther.getStatcer2()) ) )
 && ( (this.getStatdate2()==castOther.getStatdate2()) || ( this.getStatdate2()!=null && castOther.getStatdate2()!=null && this.getStatdate2().equals(castOther.getStatdate2()) ) )
 && ( (this.getInformdate1()==castOther.getInformdate1()) || ( this.getInformdate1()!=null && castOther.getInformdate1()!=null && this.getInformdate1().equals(castOther.getInformdate1()) ) )
 && ( (this.getPaydate1()==castOther.getPaydate1()) || ( this.getPaydate1()!=null && castOther.getPaydate1()!=null && this.getPaydate1().equals(castOther.getPaydate1()) ) )
 && ( (this.getAmount1()==castOther.getAmount1()) || ( this.getAmount1()!=null && castOther.getAmount1()!=null && this.getAmount1().equals(castOther.getAmount1()) ) )
 && ( (this.getInformdate2()==castOther.getInformdate2()) || ( this.getInformdate2()!=null && castOther.getInformdate2()!=null && this.getInformdate2().equals(castOther.getInformdate2()) ) )
 && ( (this.getPaydate2()==castOther.getPaydate2()) || ( this.getPaydate2()!=null && castOther.getPaydate2()!=null && this.getPaydate2().equals(castOther.getPaydate2()) ) )
 && ( (this.getAmount2()==castOther.getAmount2()) || ( this.getAmount2()!=null && castOther.getAmount2()!=null && this.getAmount2().equals(castOther.getAmount2()) ) )
 && ( (this.getDeaddate()==castOther.getDeaddate()) || ( this.getDeaddate()!=null && castOther.getDeaddate()!=null && this.getDeaddate().equals(castOther.getDeaddate()) ) )
 && ( (this.getEndownmentyear()==castOther.getEndownmentyear()) || ( this.getEndownmentyear()!=null && castOther.getEndownmentyear()!=null && this.getEndownmentyear().equals(castOther.getEndownmentyear()) ) )
 && ( (this.getDeadcause()==castOther.getDeadcause()) || ( this.getDeadcause()!=null && castOther.getDeadcause()!=null && this.getDeadcause().equals(castOther.getDeadcause()) ) )
 && ( (this.getReceiptflag()==castOther.getReceiptflag()) || ( this.getReceiptflag()!=null && castOther.getReceiptflag()!=null && this.getReceiptflag().equals(castOther.getReceiptflag()) ) )
 && ( (this.getReferenceno()==castOther.getReferenceno()) || ( this.getReferenceno()!=null && castOther.getReferenceno()!=null && this.getReferenceno().equals(castOther.getReferenceno()) ) )
 && ( (this.getReserve()==castOther.getReserve()) || ( this.getReserve()!=null && castOther.getReserve()!=null && this.getReserve().equals(castOther.getReserve()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAppno() == null ? 0 : this.getAppno().hashCode() );
         result = 37 * result + ( getReqdate() == null ? 0 : this.getReqdate().hashCode() );
         result = 37 * result + ( getNameid() == null ? 0 : this.getNameid().hashCode() );
         result = 37 * result + ( getAge() == null ? 0 : this.getAge().hashCode() );
         result = 37 * result + ( getSmi() == null ? 0 : this.getSmi().hashCode() );
         result = 37 * result + ( getLifesum() == null ? 0 : this.getLifesum().hashCode() );
         result = 37 * result + ( getAccidentsum() == null ? 0 : this.getAccidentsum().hashCode() );
         result = 37 * result + ( getPeriod() == null ? 0 : this.getPeriod().hashCode() );
         result = 37 * result + ( getLoanTerm() == null ? 0 : this.getLoanTerm().hashCode() );
         result = 37 * result + ( getLifepremium() == null ? 0 : this.getLifepremium().hashCode() );
         result = 37 * result + ( getExtrapremium() == null ? 0 : this.getExtrapremium().hashCode() );
         result = 37 * result + ( getTpdpremium() == null ? 0 : this.getTpdpremium().hashCode() );
         result = 37 * result + ( getExtratpdpremium() == null ? 0 : this.getExtratpdpremium().hashCode() );
         result = 37 * result + ( getAddpremium() == null ? 0 : this.getAddpremium().hashCode() );
         result = 37 * result + ( getEm() == null ? 0 : this.getEm().hashCode() );
         result = 37 * result + ( getTpd() == null ? 0 : this.getTpd().hashCode() );
         result = 37 * result + ( getEffectivedate() == null ? 0 : this.getEffectivedate().hashCode() );
         result = 37 * result + ( getMaturedate() == null ? 0 : this.getMaturedate().hashCode() );
         result = 37 * result + ( getPremiumdate() == null ? 0 : this.getPremiumdate().hashCode() );
         result = 37 * result + ( getCertyyyymm() == null ? 0 : this.getCertyyyymm().hashCode() );
         result = 37 * result + ( getStatcer() == null ? 0 : this.getStatcer().hashCode() );
         result = 37 * result + ( getStatcer2() == null ? 0 : this.getStatcer2().hashCode() );
         result = 37 * result + ( getStatdate2() == null ? 0 : this.getStatdate2().hashCode() );
         result = 37 * result + ( getInformdate1() == null ? 0 : this.getInformdate1().hashCode() );
         result = 37 * result + ( getPaydate1() == null ? 0 : this.getPaydate1().hashCode() );
         result = 37 * result + ( getAmount1() == null ? 0 : this.getAmount1().hashCode() );
         result = 37 * result + ( getInformdate2() == null ? 0 : this.getInformdate2().hashCode() );
         result = 37 * result + ( getPaydate2() == null ? 0 : this.getPaydate2().hashCode() );
         result = 37 * result + ( getAmount2() == null ? 0 : this.getAmount2().hashCode() );
         result = 37 * result + ( getDeaddate() == null ? 0 : this.getDeaddate().hashCode() );
         result = 37 * result + ( getEndownmentyear() == null ? 0 : this.getEndownmentyear().hashCode() );
         result = 37 * result + ( getDeadcause() == null ? 0 : this.getDeadcause().hashCode() );
         result = 37 * result + ( getReceiptflag() == null ? 0 : this.getReceiptflag().hashCode() );
         result = 37 * result + ( getReferenceno() == null ? 0 : this.getReferenceno().hashCode() );
         result = 37 * result + ( getReserve() == null ? 0 : this.getReserve().hashCode() );
         return result;
   }   


}


