package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cert generated by hbm2java
 */
@Entity
@Table(name="cert"
)
public class Cert  implements java.io.Serializable {


     private CertId id;

    public Cert() {
    }

    public Cert(CertId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="appno", column=@Column(name="appno") ), 
        @AttributeOverride(name="reqdate", column=@Column(name="reqdate") ), 
        @AttributeOverride(name="nameid", column=@Column(name="nameid") ), 
        @AttributeOverride(name="age", column=@Column(name="age") ), 
        @AttributeOverride(name="smi", column=@Column(name="smi") ), 
        @AttributeOverride(name="lifesum", column=@Column(name="lifesum") ), 
        @AttributeOverride(name="accidentsum", column=@Column(name="accidentsum") ), 
        @AttributeOverride(name="period", column=@Column(name="period") ), 
        @AttributeOverride(name="loanTerm", column=@Column(name="loan_term") ), 
        @AttributeOverride(name="lifepremium", column=@Column(name="lifepremium") ), 
        @AttributeOverride(name="extrapremium", column=@Column(name="extrapremium") ), 
        @AttributeOverride(name="tpdpremium", column=@Column(name="tpdpremium") ), 
        @AttributeOverride(name="extratpdpremium", column=@Column(name="extratpdpremium") ), 
        @AttributeOverride(name="addpremium", column=@Column(name="addpremium") ), 
        @AttributeOverride(name="em", column=@Column(name="em") ), 
        @AttributeOverride(name="tpd", column=@Column(name="tpd") ), 
        @AttributeOverride(name="effectivedate", column=@Column(name="effectivedate") ), 
        @AttributeOverride(name="maturedate", column=@Column(name="maturedate") ), 
        @AttributeOverride(name="premiumdate", column=@Column(name="premiumdate") ), 
        @AttributeOverride(name="certyyyymm", column=@Column(name="certyyyymm") ), 
        @AttributeOverride(name="statcer", column=@Column(name="statcer") ), 
        @AttributeOverride(name="statcer2", column=@Column(name="statcer2") ), 
        @AttributeOverride(name="statdate2", column=@Column(name="statdate2") ), 
        @AttributeOverride(name="informdate1", column=@Column(name="informdate1") ), 
        @AttributeOverride(name="paydate1", column=@Column(name="paydate1") ), 
        @AttributeOverride(name="amount1", column=@Column(name="amount1") ), 
        @AttributeOverride(name="informdate2", column=@Column(name="informdate2") ), 
        @AttributeOverride(name="paydate2", column=@Column(name="paydate2") ), 
        @AttributeOverride(name="amount2", column=@Column(name="amount2") ), 
        @AttributeOverride(name="deaddate", column=@Column(name="deaddate") ), 
        @AttributeOverride(name="endownmentyear", column=@Column(name="endownmentyear ") ), 
        @AttributeOverride(name="deadcause", column=@Column(name="deadcause") ), 
        @AttributeOverride(name="receiptflag", column=@Column(name="receiptflag  ") ), 
        @AttributeOverride(name="referenceno", column=@Column(name="referenceno ") ), 
        @AttributeOverride(name="reserve", column=@Column(name="reserve") ) } )
    public CertId getId() {
        return this.id;
    }
    
    public void setId(CertId id) {
        this.id = id;
    }




}


