package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Certlinker generated by hbm2java
 */
@Entity
@Table(name="certlinker"
)
public class Certlinker  implements java.io.Serializable {


     private CertlinkerId id;

    public Certlinker() {
    }

    public Certlinker(CertlinkerId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policynohp", column=@Column(name="policynohp") ), 
        @AttributeOverride(name="certnohp", column=@Column(name="certnohp") ), 
        @AttributeOverride(name="policynocp", column=@Column(name="policynocp") ), 
        @AttributeOverride(name="certnocp", column=@Column(name="certnocp") ) } )
    public CertlinkerId getId() {
        return this.id;
    }
    
    public void setId(CertlinkerId id) {
        this.id = id;
    }




}


