package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertmappingId generated by hbm2java
 */
@Embeddable
public class CertmappingId  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String rpolicyno;
     private String rpolicyn;

    public CertmappingId() {
    }

    public CertmappingId(String policyno, String certno, String rpolicyno, String rpolicyn) {
       this.policyno = policyno;
       this.certno = certno;
       this.rpolicyno = rpolicyno;
       this.rpolicyn = rpolicyn;
    }
   

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="rpolicyno")
    public String getRpolicyno() {
        return this.rpolicyno;
    }
    
    public void setRpolicyno(String rpolicyno) {
        this.rpolicyno = rpolicyno;
    }

    @Column(name="rpolicyn")
    public String getRpolicyn() {
        return this.rpolicyn;
    }
    
    public void setRpolicyn(String rpolicyn) {
        this.rpolicyn = rpolicyn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CertmappingId) ) return false;
		 CertmappingId castOther = ( CertmappingId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getRpolicyno()==castOther.getRpolicyno()) || ( this.getRpolicyno()!=null && castOther.getRpolicyno()!=null && this.getRpolicyno().equals(castOther.getRpolicyno()) ) )
 && ( (this.getRpolicyn()==castOther.getRpolicyn()) || ( this.getRpolicyn()!=null && castOther.getRpolicyn()!=null && this.getRpolicyn().equals(castOther.getRpolicyn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getRpolicyno() == null ? 0 : this.getRpolicyno().hashCode() );
         result = 37 * result + ( getRpolicyn() == null ? 0 : this.getRpolicyn().hashCode() );
         return result;
   }   


}


