package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Compensateid generated by hbm2java
 */
@Entity
@Table(name="compensateid"
)
public class Compensateid  implements java.io.Serializable {


     private CompensateidId id;

    public Compensateid() {
    }

    public Compensateid(CompensateidId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="compensateid", column=@Column(name="compensateid") ), 
        @AttributeOverride(name="referenceid", column=@Column(name="referenceid") ) } )
    public CompensateidId getId() {
        return this.id;
    }
    
    public void setId(CompensateidId id) {
        this.id = id;
    }




}


