package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerId generated by hbm2java
 */
@Embeddable
public class CustomerId  implements java.io.Serializable {


     private String customerid;
     private String referenceid;
     private String referencetype;
     private String birthdate;
     private String sex;
     private String contactnameid;
     private String contactaddressid;

    public CustomerId() {
    }

    public CustomerId(String customerid, String referenceid, String referencetype, String birthdate, String sex, String contactnameid, String contactaddressid) {
       this.customerid = customerid;
       this.referenceid = referenceid;
       this.referencetype = referencetype;
       this.birthdate = birthdate;
       this.sex = sex;
       this.contactnameid = contactnameid;
       this.contactaddressid = contactaddressid;
    }
   

    @Column(name="customerid")
    public String getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    @Column(name="referenceid")
    public String getReferenceid() {
        return this.referenceid;
    }
    
    public void setReferenceid(String referenceid) {
        this.referenceid = referenceid;
    }

    @Column(name="referencetype")
    public String getReferencetype() {
        return this.referencetype;
    }
    
    public void setReferencetype(String referencetype) {
        this.referencetype = referencetype;
    }

    @Column(name="birthdate")
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    @Column(name="sex")
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name="contactnameid")
    public String getContactnameid() {
        return this.contactnameid;
    }
    
    public void setContactnameid(String contactnameid) {
        this.contactnameid = contactnameid;
    }

    @Column(name="contactaddressid")
    public String getContactaddressid() {
        return this.contactaddressid;
    }
    
    public void setContactaddressid(String contactaddressid) {
        this.contactaddressid = contactaddressid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomerId) ) return false;
		 CustomerId castOther = ( CustomerId ) other; 
         
		 return ( (this.getCustomerid()==castOther.getCustomerid()) || ( this.getCustomerid()!=null && castOther.getCustomerid()!=null && this.getCustomerid().equals(castOther.getCustomerid()) ) )
 && ( (this.getReferenceid()==castOther.getReferenceid()) || ( this.getReferenceid()!=null && castOther.getReferenceid()!=null && this.getReferenceid().equals(castOther.getReferenceid()) ) )
 && ( (this.getReferencetype()==castOther.getReferencetype()) || ( this.getReferencetype()!=null && castOther.getReferencetype()!=null && this.getReferencetype().equals(castOther.getReferencetype()) ) )
 && ( (this.getBirthdate()==castOther.getBirthdate()) || ( this.getBirthdate()!=null && castOther.getBirthdate()!=null && this.getBirthdate().equals(castOther.getBirthdate()) ) )
 && ( (this.getSex()==castOther.getSex()) || ( this.getSex()!=null && castOther.getSex()!=null && this.getSex().equals(castOther.getSex()) ) )
 && ( (this.getContactnameid()==castOther.getContactnameid()) || ( this.getContactnameid()!=null && castOther.getContactnameid()!=null && this.getContactnameid().equals(castOther.getContactnameid()) ) )
 && ( (this.getContactaddressid()==castOther.getContactaddressid()) || ( this.getContactaddressid()!=null && castOther.getContactaddressid()!=null && this.getContactaddressid().equals(castOther.getContactaddressid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomerid() == null ? 0 : this.getCustomerid().hashCode() );
         result = 37 * result + ( getReferenceid() == null ? 0 : this.getReferenceid().hashCode() );
         result = 37 * result + ( getReferencetype() == null ? 0 : this.getReferencetype().hashCode() );
         result = 37 * result + ( getBirthdate() == null ? 0 : this.getBirthdate().hashCode() );
         result = 37 * result + ( getSex() == null ? 0 : this.getSex().hashCode() );
         result = 37 * result + ( getContactnameid() == null ? 0 : this.getContactnameid().hashCode() );
         result = 37 * result + ( getContactaddressid() == null ? 0 : this.getContactaddressid().hashCode() );
         return result;
   }   


}


