package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
)
public class Customer  implements java.io.Serializable {


     private CustomerId id;

    public Customer() {
    }

    public Customer(CustomerId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="customerid", column=@Column(name="customerid") ), 
        @AttributeOverride(name="referenceid", column=@Column(name="referenceid") ), 
        @AttributeOverride(name="referencetype", column=@Column(name="referencetype") ), 
        @AttributeOverride(name="birthdate", column=@Column(name="birthdate") ), 
        @AttributeOverride(name="sex", column=@Column(name="sex") ), 
        @AttributeOverride(name="contactnameid", column=@Column(name="contactnameid") ), 
        @AttributeOverride(name="contactaddressid", column=@Column(name="contactaddressid") ) } )
    public CustomerId getId() {
        return this.id;
    }
    
    public void setId(CustomerId id) {
        this.id = id;
    }




}


