package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Detcert generated by hbm2java
 */
@Entity
@Table(name="detcert"
)
public class Detcert  implements java.io.Serializable {


     private DetcertId id;

    public Detcert() {
    }

    public Detcert(DetcertId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="code", column=@Column(name="code") ), 
        @AttributeOverride(name="address1", column=@Column(name="address1") ), 
        @AttributeOverride(name="address2", column=@Column(name="address2") ), 
        @AttributeOverride(name="telephoneno", column=@Column(name="telephoneno") ), 
        @AttributeOverride(name="mariagestatus", column=@Column(name="mariagestatus") ), 
        @AttributeOverride(name="recname1", column=@Column(name="recname1") ), 
        @AttributeOverride(name="percent1", column=@Column(name="percent1") ), 
        @AttributeOverride(name="relationshipcode1", column=@Column(name="relationshipcode1") ), 
        @AttributeOverride(name="recname2", column=@Column(name="recname2") ), 
        @AttributeOverride(name="percent2", column=@Column(name="percent2") ), 
        @AttributeOverride(name="relationshipcode2", column=@Column(name="relationshipcode2") ), 
        @AttributeOverride(name="recname3", column=@Column(name="recname3") ), 
        @AttributeOverride(name="percent3", column=@Column(name="percent3") ), 
        @AttributeOverride(name="relationshipcode3", column=@Column(name="relationshipcode3") ), 
        @AttributeOverride(name="analist", column=@Column(name="analist") ), 
        @AttributeOverride(name="prmiseno", column=@Column(name="prmiseno") ), 
        @AttributeOverride(name="prmiseno2", column=@Column(name="prmiseno2") ), 
        @AttributeOverride(name="loantype", column=@Column(name="loantype") ), 
        @AttributeOverride(name="med", column=@Column(name="med") ), 
        @AttributeOverride(name="reserve", column=@Column(name="reserve") ) } )
    public DetcertId getId() {
        return this.id;
    }
    
    public void setId(DetcertId id) {
        this.id = id;
    }




}


