package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetcertId generated by hbm2java
 */
@Embeddable
public class DetcertId  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String code;
     private String address1;
     private String address2;
     private String telephoneno;
     private String mariagestatus;
     private String recname1;
     private String percent1;
     private String relationshipcode1;
     private String recname2;
     private String percent2;
     private String relationshipcode2;
     private String recname3;
     private String percent3;
     private String relationshipcode3;
     private String analist;
     private String prmiseno;
     private String prmiseno2;
     private String loantype;
     private String med;
     private String reserve;

    public DetcertId() {
    }

    public DetcertId(String policyno, String certno, String code, String address1, String address2, String telephoneno, String mariagestatus, String recname1, String percent1, String relationshipcode1, String recname2, String percent2, String relationshipcode2, String recname3, String percent3, String relationshipcode3, String analist, String prmiseno, String prmiseno2, String loantype, String med, String reserve) {
       this.policyno = policyno;
       this.certno = certno;
       this.code = code;
       this.address1 = address1;
       this.address2 = address2;
       this.telephoneno = telephoneno;
       this.mariagestatus = mariagestatus;
       this.recname1 = recname1;
       this.percent1 = percent1;
       this.relationshipcode1 = relationshipcode1;
       this.recname2 = recname2;
       this.percent2 = percent2;
       this.relationshipcode2 = relationshipcode2;
       this.recname3 = recname3;
       this.percent3 = percent3;
       this.relationshipcode3 = relationshipcode3;
       this.analist = analist;
       this.prmiseno = prmiseno;
       this.prmiseno2 = prmiseno2;
       this.loantype = loantype;
       this.med = med;
       this.reserve = reserve;
    }
   

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="code")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Column(name="address1")
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name="address2")
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name="telephoneno")
    public String getTelephoneno() {
        return this.telephoneno;
    }
    
    public void setTelephoneno(String telephoneno) {
        this.telephoneno = telephoneno;
    }

    @Column(name="mariagestatus")
    public String getMariagestatus() {
        return this.mariagestatus;
    }
    
    public void setMariagestatus(String mariagestatus) {
        this.mariagestatus = mariagestatus;
    }

    @Column(name="recname1")
    public String getRecname1() {
        return this.recname1;
    }
    
    public void setRecname1(String recname1) {
        this.recname1 = recname1;
    }

    @Column(name="percent1")
    public String getPercent1() {
        return this.percent1;
    }
    
    public void setPercent1(String percent1) {
        this.percent1 = percent1;
    }

    @Column(name="relationshipcode1")
    public String getRelationshipcode1() {
        return this.relationshipcode1;
    }
    
    public void setRelationshipcode1(String relationshipcode1) {
        this.relationshipcode1 = relationshipcode1;
    }

    @Column(name="recname2")
    public String getRecname2() {
        return this.recname2;
    }
    
    public void setRecname2(String recname2) {
        this.recname2 = recname2;
    }

    @Column(name="percent2")
    public String getPercent2() {
        return this.percent2;
    }
    
    public void setPercent2(String percent2) {
        this.percent2 = percent2;
    }

    @Column(name="relationshipcode2")
    public String getRelationshipcode2() {
        return this.relationshipcode2;
    }
    
    public void setRelationshipcode2(String relationshipcode2) {
        this.relationshipcode2 = relationshipcode2;
    }

    @Column(name="recname3")
    public String getRecname3() {
        return this.recname3;
    }
    
    public void setRecname3(String recname3) {
        this.recname3 = recname3;
    }

    @Column(name="percent3")
    public String getPercent3() {
        return this.percent3;
    }
    
    public void setPercent3(String percent3) {
        this.percent3 = percent3;
    }

    @Column(name="relationshipcode3")
    public String getRelationshipcode3() {
        return this.relationshipcode3;
    }
    
    public void setRelationshipcode3(String relationshipcode3) {
        this.relationshipcode3 = relationshipcode3;
    }

    @Column(name="analist")
    public String getAnalist() {
        return this.analist;
    }
    
    public void setAnalist(String analist) {
        this.analist = analist;
    }

    @Column(name="prmiseno")
    public String getPrmiseno() {
        return this.prmiseno;
    }
    
    public void setPrmiseno(String prmiseno) {
        this.prmiseno = prmiseno;
    }

    @Column(name="prmiseno2")
    public String getPrmiseno2() {
        return this.prmiseno2;
    }
    
    public void setPrmiseno2(String prmiseno2) {
        this.prmiseno2 = prmiseno2;
    }

    @Column(name="loantype")
    public String getLoantype() {
        return this.loantype;
    }
    
    public void setLoantype(String loantype) {
        this.loantype = loantype;
    }

    @Column(name="med")
    public String getMed() {
        return this.med;
    }
    
    public void setMed(String med) {
        this.med = med;
    }

    @Column(name="reserve")
    public String getReserve() {
        return this.reserve;
    }
    
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetcertId) ) return false;
		 DetcertId castOther = ( DetcertId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getAddress1()==castOther.getAddress1()) || ( this.getAddress1()!=null && castOther.getAddress1()!=null && this.getAddress1().equals(castOther.getAddress1()) ) )
 && ( (this.getAddress2()==castOther.getAddress2()) || ( this.getAddress2()!=null && castOther.getAddress2()!=null && this.getAddress2().equals(castOther.getAddress2()) ) )
 && ( (this.getTelephoneno()==castOther.getTelephoneno()) || ( this.getTelephoneno()!=null && castOther.getTelephoneno()!=null && this.getTelephoneno().equals(castOther.getTelephoneno()) ) )
 && ( (this.getMariagestatus()==castOther.getMariagestatus()) || ( this.getMariagestatus()!=null && castOther.getMariagestatus()!=null && this.getMariagestatus().equals(castOther.getMariagestatus()) ) )
 && ( (this.getRecname1()==castOther.getRecname1()) || ( this.getRecname1()!=null && castOther.getRecname1()!=null && this.getRecname1().equals(castOther.getRecname1()) ) )
 && ( (this.getPercent1()==castOther.getPercent1()) || ( this.getPercent1()!=null && castOther.getPercent1()!=null && this.getPercent1().equals(castOther.getPercent1()) ) )
 && ( (this.getRelationshipcode1()==castOther.getRelationshipcode1()) || ( this.getRelationshipcode1()!=null && castOther.getRelationshipcode1()!=null && this.getRelationshipcode1().equals(castOther.getRelationshipcode1()) ) )
 && ( (this.getRecname2()==castOther.getRecname2()) || ( this.getRecname2()!=null && castOther.getRecname2()!=null && this.getRecname2().equals(castOther.getRecname2()) ) )
 && ( (this.getPercent2()==castOther.getPercent2()) || ( this.getPercent2()!=null && castOther.getPercent2()!=null && this.getPercent2().equals(castOther.getPercent2()) ) )
 && ( (this.getRelationshipcode2()==castOther.getRelationshipcode2()) || ( this.getRelationshipcode2()!=null && castOther.getRelationshipcode2()!=null && this.getRelationshipcode2().equals(castOther.getRelationshipcode2()) ) )
 && ( (this.getRecname3()==castOther.getRecname3()) || ( this.getRecname3()!=null && castOther.getRecname3()!=null && this.getRecname3().equals(castOther.getRecname3()) ) )
 && ( (this.getPercent3()==castOther.getPercent3()) || ( this.getPercent3()!=null && castOther.getPercent3()!=null && this.getPercent3().equals(castOther.getPercent3()) ) )
 && ( (this.getRelationshipcode3()==castOther.getRelationshipcode3()) || ( this.getRelationshipcode3()!=null && castOther.getRelationshipcode3()!=null && this.getRelationshipcode3().equals(castOther.getRelationshipcode3()) ) )
 && ( (this.getAnalist()==castOther.getAnalist()) || ( this.getAnalist()!=null && castOther.getAnalist()!=null && this.getAnalist().equals(castOther.getAnalist()) ) )
 && ( (this.getPrmiseno()==castOther.getPrmiseno()) || ( this.getPrmiseno()!=null && castOther.getPrmiseno()!=null && this.getPrmiseno().equals(castOther.getPrmiseno()) ) )
 && ( (this.getPrmiseno2()==castOther.getPrmiseno2()) || ( this.getPrmiseno2()!=null && castOther.getPrmiseno2()!=null && this.getPrmiseno2().equals(castOther.getPrmiseno2()) ) )
 && ( (this.getLoantype()==castOther.getLoantype()) || ( this.getLoantype()!=null && castOther.getLoantype()!=null && this.getLoantype().equals(castOther.getLoantype()) ) )
 && ( (this.getMed()==castOther.getMed()) || ( this.getMed()!=null && castOther.getMed()!=null && this.getMed().equals(castOther.getMed()) ) )
 && ( (this.getReserve()==castOther.getReserve()) || ( this.getReserve()!=null && castOther.getReserve()!=null && this.getReserve().equals(castOther.getReserve()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getAddress1() == null ? 0 : this.getAddress1().hashCode() );
         result = 37 * result + ( getAddress2() == null ? 0 : this.getAddress2().hashCode() );
         result = 37 * result + ( getTelephoneno() == null ? 0 : this.getTelephoneno().hashCode() );
         result = 37 * result + ( getMariagestatus() == null ? 0 : this.getMariagestatus().hashCode() );
         result = 37 * result + ( getRecname1() == null ? 0 : this.getRecname1().hashCode() );
         result = 37 * result + ( getPercent1() == null ? 0 : this.getPercent1().hashCode() );
         result = 37 * result + ( getRelationshipcode1() == null ? 0 : this.getRelationshipcode1().hashCode() );
         result = 37 * result + ( getRecname2() == null ? 0 : this.getRecname2().hashCode() );
         result = 37 * result + ( getPercent2() == null ? 0 : this.getPercent2().hashCode() );
         result = 37 * result + ( getRelationshipcode2() == null ? 0 : this.getRelationshipcode2().hashCode() );
         result = 37 * result + ( getRecname3() == null ? 0 : this.getRecname3().hashCode() );
         result = 37 * result + ( getPercent3() == null ? 0 : this.getPercent3().hashCode() );
         result = 37 * result + ( getRelationshipcode3() == null ? 0 : this.getRelationshipcode3().hashCode() );
         result = 37 * result + ( getAnalist() == null ? 0 : this.getAnalist().hashCode() );
         result = 37 * result + ( getPrmiseno() == null ? 0 : this.getPrmiseno().hashCode() );
         result = 37 * result + ( getPrmiseno2() == null ? 0 : this.getPrmiseno2().hashCode() );
         result = 37 * result + ( getLoantype() == null ? 0 : this.getLoantype().hashCode() );
         result = 37 * result + ( getMed() == null ? 0 : this.getMed().hashCode() );
         result = 37 * result + ( getReserve() == null ? 0 : this.getReserve().hashCode() );
         return result;
   }   


}


