package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgclaimId generated by hbm2java
 */
@Embeddable
public class MgclaimId  implements java.io.Serializable {


     private String certno;
     private String accidentdate;
     private String receivedate;
     private String claimtype;
     private String sectioncode;
     private String orderno;
     private String referenceno;
     private String linkerno;
     private String okdate;
     private String policyno;
     private String ismigration;

    public MgclaimId() {
    }

    public MgclaimId(String certno, String accidentdate, String receivedate, String claimtype, String sectioncode, String orderno, String referenceno, String linkerno, String okdate, String policyno, String ismigration) {
       this.certno = certno;
       this.accidentdate = accidentdate;
       this.receivedate = receivedate;
       this.claimtype = claimtype;
       this.sectioncode = sectioncode;
       this.orderno = orderno;
       this.referenceno = referenceno;
       this.linkerno = linkerno;
       this.okdate = okdate;
       this.policyno = policyno;
       this.ismigration = ismigration;
    }
   

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="accidentdate")
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="receivedate")
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="claimtype")
    public String getClaimtype() {
        return this.claimtype;
    }
    
    public void setClaimtype(String claimtype) {
        this.claimtype = claimtype;
    }

    @Column(name="sectioncode")
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @Column(name="orderno")
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    @Column(name="referenceno")
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }

    @Column(name="linkerno")
    public String getLinkerno() {
        return this.linkerno;
    }
    
    public void setLinkerno(String linkerno) {
        this.linkerno = linkerno;
    }

    @Column(name="okdate")
    public String getOkdate() {
        return this.okdate;
    }
    
    public void setOkdate(String okdate) {
        this.okdate = okdate;
    }

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }
 
   @Column(name="ismigration")
   public String getIsmigration() {
		return ismigration;
	}

	public void setIsmigration(String ismigration) {
		this.ismigration = ismigration;
	}

public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgclaimId) ) return false;
		 MgclaimId castOther = ( MgclaimId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getClaimtype()==castOther.getClaimtype()) || ( this.getClaimtype()!=null && castOther.getClaimtype()!=null && this.getClaimtype().equals(castOther.getClaimtype()) ) )
 && ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) )
 && ( (this.getOrderno()==castOther.getOrderno()) || ( this.getOrderno()!=null && castOther.getOrderno()!=null && this.getOrderno().equals(castOther.getOrderno()) ) )
 && ( (this.getReferenceno()==castOther.getReferenceno()) || ( this.getReferenceno()!=null && castOther.getReferenceno()!=null && this.getReferenceno().equals(castOther.getReferenceno()) ) )
 && ( (this.getLinkerno()==castOther.getLinkerno()) || ( this.getLinkerno()!=null && castOther.getLinkerno()!=null && this.getLinkerno().equals(castOther.getLinkerno()) ) )
 && ( (this.getOkdate()==castOther.getOkdate()) || ( this.getOkdate()!=null && castOther.getOkdate()!=null && this.getOkdate().equals(castOther.getOkdate()) ) )
 && ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getIsmigration()==castOther.getIsmigration()) || ( this.getIsmigration()!=null && castOther.getIsmigration()!=null && this.getIsmigration().equals(castOther.getIsmigration()) ) )
 ;
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getClaimtype() == null ? 0 : this.getClaimtype().hashCode() );
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         result = 37 * result + ( getOrderno() == null ? 0 : this.getOrderno().hashCode() );
         result = 37 * result + ( getReferenceno() == null ? 0 : this.getReferenceno().hashCode() );
         result = 37 * result + ( getLinkerno() == null ? 0 : this.getLinkerno().hashCode() );
         result = 37 * result + ( getOkdate() == null ? 0 : this.getOkdate().hashCode() );
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getIsmigration() == null ? 0 : this.getIsmigration().hashCode() );
         return result;
   }   


}


