package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgclaim generated by hbm2java
 */
@Entity
@Table(name="mgclaim"
)
public class Mgclaim  implements java.io.Serializable {


     private MgclaimId id;

    public Mgclaim() {
    }

    public Mgclaim(MgclaimId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate") ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate") ), 
        @AttributeOverride(name="claimtype", column=@Column(name="claimtype") ), 
        @AttributeOverride(name="sectioncode", column=@Column(name="sectioncode") ), 
        @AttributeOverride(name="orderno", column=@Column(name="orderno") ), 
        @AttributeOverride(name="referenceno", column=@Column(name="referenceno") ), 
        @AttributeOverride(name="linkerno", column=@Column(name="linkerno") ), 
        @AttributeOverride(name="okdate", column=@Column(name="okdate") ), 
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ) } )
    public MgclaimId getId() {
        return this.id;
    }
    
    public void setId(MgclaimId id) {
        this.id = id;
    }




}


