package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MghisId generated by hbm2java
 */
@Embeddable
public class MghisId  implements java.io.Serializable {


     private String certno;
     private String accidentdate;
     private String receivedate;
     private String claimtype;
     private String seqno;
     private String remarkdate;
     private String remarkno;
     private String remark;
     private String employeeid;
     private String rectime;

    public MghisId() {
    }

    public MghisId(String certno, String accidentdate, String receivedate, String claimtype, String seqno, String remarkdate, String remarkno, String remark, String employeeid, String rectime) {
       this.certno = certno;
       this.accidentdate = accidentdate;
       this.receivedate = receivedate;
       this.claimtype = claimtype;
       this.seqno = seqno;
       this.remarkdate = remarkdate;
       this.remarkno = remarkno;
       this.remark = remark;
       this.employeeid = employeeid;
       this.rectime = rectime;
    }
   

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="accidentdate")
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="receivedate")
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="claimtype")
    public String getClaimtype() {
        return this.claimtype;
    }
    
    public void setClaimtype(String claimtype) {
        this.claimtype = claimtype;
    }

    @Column(name="seqno")
    public String getSeqno() {
        return this.seqno;
    }
    
    public void setSeqno(String seqno) {
        this.seqno = seqno;
    }

    @Column(name="remarkdate")
    public String getRemarkdate() {
        return this.remarkdate;
    }
    
    public void setRemarkdate(String remarkdate) {
        this.remarkdate = remarkdate;
    }

    @Column(name="remarkno")
    public String getRemarkno() {
        return this.remarkno;
    }
    
    public void setRemarkno(String remarkno) {
        this.remarkno = remarkno;
    }

    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name="employeeid")
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    @Column(name="rectime")
    public String getRectime() {
        return this.rectime;
    }
    
    public void setRectime(String rectime) {
        this.rectime = rectime;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MghisId) ) return false;
		 MghisId castOther = ( MghisId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getClaimtype()==castOther.getClaimtype()) || ( this.getClaimtype()!=null && castOther.getClaimtype()!=null && this.getClaimtype().equals(castOther.getClaimtype()) ) )
 && ( (this.getSeqno()==castOther.getSeqno()) || ( this.getSeqno()!=null && castOther.getSeqno()!=null && this.getSeqno().equals(castOther.getSeqno()) ) )
 && ( (this.getRemarkdate()==castOther.getRemarkdate()) || ( this.getRemarkdate()!=null && castOther.getRemarkdate()!=null && this.getRemarkdate().equals(castOther.getRemarkdate()) ) )
 && ( (this.getRemarkno()==castOther.getRemarkno()) || ( this.getRemarkno()!=null && castOther.getRemarkno()!=null && this.getRemarkno().equals(castOther.getRemarkno()) ) )
 && ( (this.getRemark()==castOther.getRemark()) || ( this.getRemark()!=null && castOther.getRemark()!=null && this.getRemark().equals(castOther.getRemark()) ) )
 && ( (this.getEmployeeid()==castOther.getEmployeeid()) || ( this.getEmployeeid()!=null && castOther.getEmployeeid()!=null && this.getEmployeeid().equals(castOther.getEmployeeid()) ) )
 && ( (this.getRectime()==castOther.getRectime()) || ( this.getRectime()!=null && castOther.getRectime()!=null && this.getRectime().equals(castOther.getRectime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getClaimtype() == null ? 0 : this.getClaimtype().hashCode() );
         result = 37 * result + ( getSeqno() == null ? 0 : this.getSeqno().hashCode() );
         result = 37 * result + ( getRemarkdate() == null ? 0 : this.getRemarkdate().hashCode() );
         result = 37 * result + ( getRemarkno() == null ? 0 : this.getRemarkno().hashCode() );
         result = 37 * result + ( getRemark() == null ? 0 : this.getRemark().hashCode() );
         result = 37 * result + ( getEmployeeid() == null ? 0 : this.getEmployeeid().hashCode() );
         result = 37 * result + ( getRectime() == null ? 0 : this.getRectime().hashCode() );
         return result;
   }   


}


