package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mghis generated by hbm2java
 */
@Entity
@Table(name="mghis"
)
public class Mghis  implements java.io.Serializable {


     private MghisId id;

    public Mghis() {
    }

    public Mghis(MghisId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate") ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate") ), 
        @AttributeOverride(name="claimtype", column=@Column(name="claimtype") ), 
        @AttributeOverride(name="seqno", column=@Column(name="seqno") ), 
        @AttributeOverride(name="remarkdate", column=@Column(name="remarkdate") ), 
        @AttributeOverride(name="remarkno", column=@Column(name="remarkno") ), 
        @AttributeOverride(name="remark", column=@Column(name="remark") ), 
        @AttributeOverride(name="employeeid", column=@Column(name="employeeid") ), 
        @AttributeOverride(name="rectime", column=@Column(name="rectime") ) } )
    public MghisId getId() {
        return this.id;
    }
    
    public void setId(MghisId id) {
        this.id = id;
    }




}


