package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MginsmemoId generated by hbm2java
 */
@Embeddable
public class MginsmemoId  implements java.io.Serializable {


     private String certno;
     private String accidentdate;
     private String receivedate;
     private String memocode;
     private String detail1;
     private String detail2;
     private String savedate;

    public MginsmemoId() {
    }

    public MginsmemoId(String certno, String accidentdate, String receivedate, String memocode, String detail1, String detail2, String savedate) {
       this.certno = certno;
       this.accidentdate = accidentdate;
       this.receivedate = receivedate;
       this.memocode = memocode;
       this.detail1 = detail1;
       this.detail2 = detail2;
       this.savedate = savedate;
    }
   

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="accidentdate")
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="receivedate")
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="memocode")
    public String getMemocode() {
        return this.memocode;
    }
    
    public void setMemocode(String memocode) {
        this.memocode = memocode;
    }

    @Column(name="detail1")
    public String getDetail1() {
        return this.detail1;
    }
    
    public void setDetail1(String detail1) {
        this.detail1 = detail1;
    }

    @Column(name="detail2")
    public String getDetail2() {
        return this.detail2;
    }
    
    public void setDetail2(String detail2) {
        this.detail2 = detail2;
    }

    @Column(name="savedate")
    public String getSavedate() {
        return this.savedate;
    }
    
    public void setSavedate(String savedate) {
        this.savedate = savedate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MginsmemoId) ) return false;
		 MginsmemoId castOther = ( MginsmemoId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getMemocode()==castOther.getMemocode()) || ( this.getMemocode()!=null && castOther.getMemocode()!=null && this.getMemocode().equals(castOther.getMemocode()) ) )
 && ( (this.getDetail1()==castOther.getDetail1()) || ( this.getDetail1()!=null && castOther.getDetail1()!=null && this.getDetail1().equals(castOther.getDetail1()) ) )
 && ( (this.getDetail2()==castOther.getDetail2()) || ( this.getDetail2()!=null && castOther.getDetail2()!=null && this.getDetail2().equals(castOther.getDetail2()) ) )
 && ( (this.getSavedate()==castOther.getSavedate()) || ( this.getSavedate()!=null && castOther.getSavedate()!=null && this.getSavedate().equals(castOther.getSavedate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getMemocode() == null ? 0 : this.getMemocode().hashCode() );
         result = 37 * result + ( getDetail1() == null ? 0 : this.getDetail1().hashCode() );
         result = 37 * result + ( getDetail2() == null ? 0 : this.getDetail2().hashCode() );
         result = 37 * result + ( getSavedate() == null ? 0 : this.getSavedate().hashCode() );
         return result;
   }   


}


