package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MginterestId generated by hbm2java
 */
@Embeddable
public class MginterestId  implements java.io.Serializable {


     private String certno;
     private String accidentdate;
     private String receivedate;
     private String ridertype;
     private String paytype;
     private String startdate;
     private String enddate;
     private String day;
     private String payamount;
     private String interestamount;

    public MginterestId() {
    }

    public MginterestId(String certno, String accidentdate, String receivedate, String ridertype, String paytype, String startdate, String enddate, String day, String payamount, String interestamount) {
       this.certno = certno;
       this.accidentdate = accidentdate;
       this.receivedate = receivedate;
       this.ridertype = ridertype;
       this.paytype = paytype;
       this.startdate = startdate;
       this.enddate = enddate;
       this.day = day;
       this.payamount = payamount;
       this.interestamount = interestamount;
    }
   

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="accidentdate")
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="receivedate")
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="ridertype")
    public String getRidertype() {
        return this.ridertype;
    }
    
    public void setRidertype(String ridertype) {
        this.ridertype = ridertype;
    }

    @Column(name="paytype")
    public String getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    @Column(name="startdate")
    public String getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }

    @Column(name="enddate")
    public String getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    @Column(name="day")
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }

    @Column(name="payamount")
    public String getPayamount() {
        return this.payamount;
    }
    
    public void setPayamount(String payamount) {
        this.payamount = payamount;
    }

    @Column(name="interestamount")
    public String getInterestamount() {
        return this.interestamount;
    }
    
    public void setInterestamount(String interestamount) {
        this.interestamount = interestamount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MginterestId) ) return false;
		 MginterestId castOther = ( MginterestId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getRidertype()==castOther.getRidertype()) || ( this.getRidertype()!=null && castOther.getRidertype()!=null && this.getRidertype().equals(castOther.getRidertype()) ) )
 && ( (this.getPaytype()==castOther.getPaytype()) || ( this.getPaytype()!=null && castOther.getPaytype()!=null && this.getPaytype().equals(castOther.getPaytype()) ) )
 && ( (this.getStartdate()==castOther.getStartdate()) || ( this.getStartdate()!=null && castOther.getStartdate()!=null && this.getStartdate().equals(castOther.getStartdate()) ) )
 && ( (this.getEnddate()==castOther.getEnddate()) || ( this.getEnddate()!=null && castOther.getEnddate()!=null && this.getEnddate().equals(castOther.getEnddate()) ) )
 && ( (this.getDay()==castOther.getDay()) || ( this.getDay()!=null && castOther.getDay()!=null && this.getDay().equals(castOther.getDay()) ) )
 && ( (this.getPayamount()==castOther.getPayamount()) || ( this.getPayamount()!=null && castOther.getPayamount()!=null && this.getPayamount().equals(castOther.getPayamount()) ) )
 && ( (this.getInterestamount()==castOther.getInterestamount()) || ( this.getInterestamount()!=null && castOther.getInterestamount()!=null && this.getInterestamount().equals(castOther.getInterestamount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getRidertype() == null ? 0 : this.getRidertype().hashCode() );
         result = 37 * result + ( getPaytype() == null ? 0 : this.getPaytype().hashCode() );
         result = 37 * result + ( getStartdate() == null ? 0 : this.getStartdate().hashCode() );
         result = 37 * result + ( getEnddate() == null ? 0 : this.getEnddate().hashCode() );
         result = 37 * result + ( getDay() == null ? 0 : this.getDay().hashCode() );
         result = 37 * result + ( getPayamount() == null ? 0 : this.getPayamount().hashCode() );
         result = 37 * result + ( getInterestamount() == null ? 0 : this.getInterestamount().hashCode() );
         return result;
   }   


}


