package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgorderId generated by hbm2java
 */
@Embeddable
public class MgorderId  implements java.io.Serializable {


     private String sectioncode;
     private String orderno;
     private String receivetime;
     private String causecode;
     private String causedetail;
     private String receiverid;
     private String considerid;
     private String admitdate;
     private String admitflag;
     private String billingorderno;
     private String interimflag;
     private String hospitalcode;
     private String receivedocdate;

    public MgorderId() {
    }

    public MgorderId(String sectioncode, String orderno, String receivetime, String causecode, String causedetail, String receiverid, String considerid, String admitdate, String admitflag, String billingorderno, String interimflag, String hospitalcode, String receivedocdate) {
       this.sectioncode = sectioncode;
       this.orderno = orderno;
       this.receivetime = receivetime;
       this.causecode = causecode;
       this.causedetail = causedetail;
       this.receiverid = receiverid;
       this.considerid = considerid;
       this.admitdate = admitdate;
       this.admitflag = admitflag;
       this.billingorderno = billingorderno;
       this.interimflag = interimflag;
       this.hospitalcode = hospitalcode;
       this.receivedocdate = receivedocdate;
    }
   

    @Column(name="sectioncode")
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @Column(name="orderno")
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    @Column(name="receivetime")
    public String getReceivetime() {
        return this.receivetime;
    }
    
    public void setReceivetime(String receivetime) {
        this.receivetime = receivetime;
    }

    @Column(name="causecode")
    public String getCausecode() {
        return this.causecode;
    }
    
    public void setCausecode(String causecode) {
        this.causecode = causecode;
    }

    @Column(name="causedetail")
    public String getCausedetail() {
        return this.causedetail;
    }
    
    public void setCausedetail(String causedetail) {
        this.causedetail = causedetail;
    }

    @Column(name="receiverid")
    public String getReceiverid() {
        return this.receiverid;
    }
    
    public void setReceiverid(String receiverid) {
        this.receiverid = receiverid;
    }

    @Column(name="considerid")
    public String getConsiderid() {
        return this.considerid;
    }
    
    public void setConsiderid(String considerid) {
        this.considerid = considerid;
    }

    @Column(name="admitdate")
    public String getAdmitdate() {
        return this.admitdate;
    }
    
    public void setAdmitdate(String admitdate) {
        this.admitdate = admitdate;
    }

    @Column(name="admitflag")
    public String getAdmitflag() {
        return this.admitflag;
    }
    
    public void setAdmitflag(String admitflag) {
        this.admitflag = admitflag;
    }

    @Column(name="billingorderno")
    public String getBillingorderno() {
        return this.billingorderno;
    }
    
    public void setBillingorderno(String billingorderno) {
        this.billingorderno = billingorderno;
    }

    @Column(name="interimflag")
    public String getInterimflag() {
        return this.interimflag;
    }
    
    public void setInterimflag(String interimflag) {
        this.interimflag = interimflag;
    }

    @Column(name="hospitalcode")
    public String getHospitalcode() {
        return this.hospitalcode;
    }
    
    public void setHospitalcode(String hospitalcode) {
        this.hospitalcode = hospitalcode;
    }

    @Column(name="receivedocdate")
    public String getReceivedocdate() {
        return this.receivedocdate;
    }
    
    public void setReceivedocdate(String receivedocdate) {
        this.receivedocdate = receivedocdate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgorderId) ) return false;
		 MgorderId castOther = ( MgorderId ) other; 
         
		 return ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) )
 && ( (this.getOrderno()==castOther.getOrderno()) || ( this.getOrderno()!=null && castOther.getOrderno()!=null && this.getOrderno().equals(castOther.getOrderno()) ) )
 && ( (this.getReceivetime()==castOther.getReceivetime()) || ( this.getReceivetime()!=null && castOther.getReceivetime()!=null && this.getReceivetime().equals(castOther.getReceivetime()) ) )
 && ( (this.getCausecode()==castOther.getCausecode()) || ( this.getCausecode()!=null && castOther.getCausecode()!=null && this.getCausecode().equals(castOther.getCausecode()) ) )
 && ( (this.getCausedetail()==castOther.getCausedetail()) || ( this.getCausedetail()!=null && castOther.getCausedetail()!=null && this.getCausedetail().equals(castOther.getCausedetail()) ) )
 && ( (this.getReceiverid()==castOther.getReceiverid()) || ( this.getReceiverid()!=null && castOther.getReceiverid()!=null && this.getReceiverid().equals(castOther.getReceiverid()) ) )
 && ( (this.getConsiderid()==castOther.getConsiderid()) || ( this.getConsiderid()!=null && castOther.getConsiderid()!=null && this.getConsiderid().equals(castOther.getConsiderid()) ) )
 && ( (this.getAdmitdate()==castOther.getAdmitdate()) || ( this.getAdmitdate()!=null && castOther.getAdmitdate()!=null && this.getAdmitdate().equals(castOther.getAdmitdate()) ) )
 && ( (this.getAdmitflag()==castOther.getAdmitflag()) || ( this.getAdmitflag()!=null && castOther.getAdmitflag()!=null && this.getAdmitflag().equals(castOther.getAdmitflag()) ) )
 && ( (this.getBillingorderno()==castOther.getBillingorderno()) || ( this.getBillingorderno()!=null && castOther.getBillingorderno()!=null && this.getBillingorderno().equals(castOther.getBillingorderno()) ) )
 && ( (this.getInterimflag()==castOther.getInterimflag()) || ( this.getInterimflag()!=null && castOther.getInterimflag()!=null && this.getInterimflag().equals(castOther.getInterimflag()) ) )
 && ( (this.getHospitalcode()==castOther.getHospitalcode()) || ( this.getHospitalcode()!=null && castOther.getHospitalcode()!=null && this.getHospitalcode().equals(castOther.getHospitalcode()) ) )
 && ( (this.getReceivedocdate()==castOther.getReceivedocdate()) || ( this.getReceivedocdate()!=null && castOther.getReceivedocdate()!=null && this.getReceivedocdate().equals(castOther.getReceivedocdate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         result = 37 * result + ( getOrderno() == null ? 0 : this.getOrderno().hashCode() );
         result = 37 * result + ( getReceivetime() == null ? 0 : this.getReceivetime().hashCode() );
         result = 37 * result + ( getCausecode() == null ? 0 : this.getCausecode().hashCode() );
         result = 37 * result + ( getCausedetail() == null ? 0 : this.getCausedetail().hashCode() );
         result = 37 * result + ( getReceiverid() == null ? 0 : this.getReceiverid().hashCode() );
         result = 37 * result + ( getConsiderid() == null ? 0 : this.getConsiderid().hashCode() );
         result = 37 * result + ( getAdmitdate() == null ? 0 : this.getAdmitdate().hashCode() );
         result = 37 * result + ( getAdmitflag() == null ? 0 : this.getAdmitflag().hashCode() );
         result = 37 * result + ( getBillingorderno() == null ? 0 : this.getBillingorderno().hashCode() );
         result = 37 * result + ( getInterimflag() == null ? 0 : this.getInterimflag().hashCode() );
         result = 37 * result + ( getHospitalcode() == null ? 0 : this.getHospitalcode().hashCode() );
         result = 37 * result + ( getReceivedocdate() == null ? 0 : this.getReceivedocdate().hashCode() );
         return result;
   }   


}


