package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgorder generated by hbm2java
 */
@Entity
@Table(name="mgorder"
)
public class Mgorder  implements java.io.Serializable {


     private MgorderId id;

    public Mgorder() {
    }

    public Mgorder(MgorderId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sectioncode", column=@Column(name="sectioncode") ), 
        @AttributeOverride(name="orderno", column=@Column(name="orderno") ), 
        @AttributeOverride(name="receivetime", column=@Column(name="receivetime") ), 
        @AttributeOverride(name="causecode", column=@Column(name="causecode") ), 
        @AttributeOverride(name="causedetail", column=@Column(name="causedetail") ), 
        @AttributeOverride(name="receiverid", column=@Column(name="receiverid") ), 
        @AttributeOverride(name="considerid", column=@Column(name="considerid") ), 
        @AttributeOverride(name="admitdate", column=@Column(name="admitdate") ), 
        @AttributeOverride(name="admitflag", column=@Column(name="admitflag") ), 
        @AttributeOverride(name="billingorderno", column=@Column(name="billingorderno") ), 
        @AttributeOverride(name="interimflag", column=@Column(name="interimflag") ), 
        @AttributeOverride(name="hospitalcode", column=@Column(name="hospitalcode") ), 
        @AttributeOverride(name="receivedocdate", column=@Column(name="receivedocdate") ) } )
    public MgorderId getId() {
        return this.id;
    }
    
    public void setId(MgorderId id) {
        this.id = id;
    }




}


