package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgpayId generated by hbm2java
 */
@Embeddable
public class MgpayId  implements java.io.Serializable {


     private String certno;
     private String receivedate;
     private String accidentdate;
     private String sectioncode;
     private String orderno;
     private String policystatus;
     private String policystatusdate;
     private String policystatus2;
     private String policystatusdate2;
     private String branchcode;
     private String servicebranch;
     private String claimtype;
     private String paytype;
     private String proofinsuredage;
     private String disabilitytype;
     private String disnumber;
     private String payrate;
     private String payamount;
     private String accdamount;
     private String surrenderamount;
     private String returnamount;
     private String deductamount;
     private String claimokdate;
     private String claimpaydate;
     private String allowtype;

    public MgpayId() {
    }

    public MgpayId(String certno, String receivedate, String accidentdate, String sectioncode, String orderno, String policystatus, String policystatusdate, String policystatus2, String policystatusdate2, String branchcode, String servicebranch, String claimtype, String paytype, String proofinsuredage, String disabilitytype, String disnumber, String payrate, String payamount, String accdamount, String surrenderamount, String returnamount, String deductamount, String claimokdate, String claimpaydate, String allowtype) {
       this.certno = certno;
       this.receivedate = receivedate;
       this.accidentdate = accidentdate;
       this.sectioncode = sectioncode;
       this.orderno = orderno;
       this.policystatus = policystatus;
       this.policystatusdate = policystatusdate;
       this.policystatus2 = policystatus2;
       this.policystatusdate2 = policystatusdate2;
       this.branchcode = branchcode;
       this.servicebranch = servicebranch;
       this.claimtype = claimtype;
       this.paytype = paytype;
       this.proofinsuredage = proofinsuredage;
       this.disabilitytype = disabilitytype;
       this.disnumber = disnumber;
       this.payrate = payrate;
       this.payamount = payamount;
       this.accdamount = accdamount;
       this.surrenderamount = surrenderamount;
       this.returnamount = returnamount;
       this.deductamount = deductamount;
       this.claimokdate = claimokdate;
       this.claimpaydate = claimpaydate;
       this.allowtype = allowtype;
    }
   

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="receivedate")
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="accidentdate")
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="sectioncode")
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @Column(name="orderno")
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    @Column(name="policystatus")
    public String getPolicystatus() {
        return this.policystatus;
    }
    
    public void setPolicystatus(String policystatus) {
        this.policystatus = policystatus;
    }

    @Column(name="policystatusdate")
    public String getPolicystatusdate() {
        return this.policystatusdate;
    }
    
    public void setPolicystatusdate(String policystatusdate) {
        this.policystatusdate = policystatusdate;
    }

    @Column(name="policystatus2")
    public String getPolicystatus2() {
        return this.policystatus2;
    }
    
    public void setPolicystatus2(String policystatus2) {
        this.policystatus2 = policystatus2;
    }

    @Column(name="policystatusdate2")
    public String getPolicystatusdate2() {
        return this.policystatusdate2;
    }
    
    public void setPolicystatusdate2(String policystatusdate2) {
        this.policystatusdate2 = policystatusdate2;
    }

    @Column(name="branchcode")
    public String getBranchcode() {
        return this.branchcode;
    }
    
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    @Column(name="servicebranch")
    public String getServicebranch() {
        return this.servicebranch;
    }
    
    public void setServicebranch(String servicebranch) {
        this.servicebranch = servicebranch;
    }

    @Column(name="claimtype")
    public String getClaimtype() {
        return this.claimtype;
    }
    
    public void setClaimtype(String claimtype) {
        this.claimtype = claimtype;
    }

    @Column(name="paytype")
    public String getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    @Column(name="proofinsuredage")
    public String getProofinsuredage() {
        return this.proofinsuredage;
    }
    
    public void setProofinsuredage(String proofinsuredage) {
        this.proofinsuredage = proofinsuredage;
    }

    @Column(name="disabilitytype")
    public String getDisabilitytype() {
        return this.disabilitytype;
    }
    
    public void setDisabilitytype(String disabilitytype) {
        this.disabilitytype = disabilitytype;
    }

    @Column(name="disnumber")
    public String getDisnumber() {
        return this.disnumber;
    }
    
    public void setDisnumber(String disnumber) {
        this.disnumber = disnumber;
    }

    @Column(name="payrate")
    public String getPayrate() {
        return this.payrate;
    }
    
    public void setPayrate(String payrate) {
        this.payrate = payrate;
    }

    @Column(name="payamount")
    public String getPayamount() {
        return this.payamount;
    }
    
    public void setPayamount(String payamount) {
        this.payamount = payamount;
    }

    @Column(name="accdamount")
    public String getAccdamount() {
        return this.accdamount;
    }
    
    public void setAccdamount(String accdamount) {
        this.accdamount = accdamount;
    }

    @Column(name="surrenderamount")
    public String getSurrenderamount() {
        return this.surrenderamount;
    }
    
    public void setSurrenderamount(String surrenderamount) {
        this.surrenderamount = surrenderamount;
    }

    @Column(name="returnamount")
    public String getReturnamount() {
        return this.returnamount;
    }
    
    public void setReturnamount(String returnamount) {
        this.returnamount = returnamount;
    }

    @Column(name="deductamount")
    public String getDeductamount() {
        return this.deductamount;
    }
    
    public void setDeductamount(String deductamount) {
        this.deductamount = deductamount;
    }

    @Column(name="claimokdate")
    public String getClaimokdate() {
        return this.claimokdate;
    }
    
    public void setClaimokdate(String claimokdate) {
        this.claimokdate = claimokdate;
    }

    @Column(name="claimpaydate")
    public String getClaimpaydate() {
        return this.claimpaydate;
    }
    
    public void setClaimpaydate(String claimpaydate) {
        this.claimpaydate = claimpaydate;
    }

    @Column(name="allowtype")
    public String getAllowtype() {
        return this.allowtype;
    }
    
    public void setAllowtype(String allowtype) {
        this.allowtype = allowtype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgpayId) ) return false;
		 MgpayId castOther = ( MgpayId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) )
 && ( (this.getOrderno()==castOther.getOrderno()) || ( this.getOrderno()!=null && castOther.getOrderno()!=null && this.getOrderno().equals(castOther.getOrderno()) ) )
 && ( (this.getPolicystatus()==castOther.getPolicystatus()) || ( this.getPolicystatus()!=null && castOther.getPolicystatus()!=null && this.getPolicystatus().equals(castOther.getPolicystatus()) ) )
 && ( (this.getPolicystatusdate()==castOther.getPolicystatusdate()) || ( this.getPolicystatusdate()!=null && castOther.getPolicystatusdate()!=null && this.getPolicystatusdate().equals(castOther.getPolicystatusdate()) ) )
 && ( (this.getPolicystatus2()==castOther.getPolicystatus2()) || ( this.getPolicystatus2()!=null && castOther.getPolicystatus2()!=null && this.getPolicystatus2().equals(castOther.getPolicystatus2()) ) )
 && ( (this.getPolicystatusdate2()==castOther.getPolicystatusdate2()) || ( this.getPolicystatusdate2()!=null && castOther.getPolicystatusdate2()!=null && this.getPolicystatusdate2().equals(castOther.getPolicystatusdate2()) ) )
 && ( (this.getBranchcode()==castOther.getBranchcode()) || ( this.getBranchcode()!=null && castOther.getBranchcode()!=null && this.getBranchcode().equals(castOther.getBranchcode()) ) )
 && ( (this.getServicebranch()==castOther.getServicebranch()) || ( this.getServicebranch()!=null && castOther.getServicebranch()!=null && this.getServicebranch().equals(castOther.getServicebranch()) ) )
 && ( (this.getClaimtype()==castOther.getClaimtype()) || ( this.getClaimtype()!=null && castOther.getClaimtype()!=null && this.getClaimtype().equals(castOther.getClaimtype()) ) )
 && ( (this.getPaytype()==castOther.getPaytype()) || ( this.getPaytype()!=null && castOther.getPaytype()!=null && this.getPaytype().equals(castOther.getPaytype()) ) )
 && ( (this.getProofinsuredage()==castOther.getProofinsuredage()) || ( this.getProofinsuredage()!=null && castOther.getProofinsuredage()!=null && this.getProofinsuredage().equals(castOther.getProofinsuredage()) ) )
 && ( (this.getDisabilitytype()==castOther.getDisabilitytype()) || ( this.getDisabilitytype()!=null && castOther.getDisabilitytype()!=null && this.getDisabilitytype().equals(castOther.getDisabilitytype()) ) )
 && ( (this.getDisnumber()==castOther.getDisnumber()) || ( this.getDisnumber()!=null && castOther.getDisnumber()!=null && this.getDisnumber().equals(castOther.getDisnumber()) ) )
 && ( (this.getPayrate()==castOther.getPayrate()) || ( this.getPayrate()!=null && castOther.getPayrate()!=null && this.getPayrate().equals(castOther.getPayrate()) ) )
 && ( (this.getPayamount()==castOther.getPayamount()) || ( this.getPayamount()!=null && castOther.getPayamount()!=null && this.getPayamount().equals(castOther.getPayamount()) ) )
 && ( (this.getAccdamount()==castOther.getAccdamount()) || ( this.getAccdamount()!=null && castOther.getAccdamount()!=null && this.getAccdamount().equals(castOther.getAccdamount()) ) )
 && ( (this.getSurrenderamount()==castOther.getSurrenderamount()) || ( this.getSurrenderamount()!=null && castOther.getSurrenderamount()!=null && this.getSurrenderamount().equals(castOther.getSurrenderamount()) ) )
 && ( (this.getReturnamount()==castOther.getReturnamount()) || ( this.getReturnamount()!=null && castOther.getReturnamount()!=null && this.getReturnamount().equals(castOther.getReturnamount()) ) )
 && ( (this.getDeductamount()==castOther.getDeductamount()) || ( this.getDeductamount()!=null && castOther.getDeductamount()!=null && this.getDeductamount().equals(castOther.getDeductamount()) ) )
 && ( (this.getClaimokdate()==castOther.getClaimokdate()) || ( this.getClaimokdate()!=null && castOther.getClaimokdate()!=null && this.getClaimokdate().equals(castOther.getClaimokdate()) ) )
 && ( (this.getClaimpaydate()==castOther.getClaimpaydate()) || ( this.getClaimpaydate()!=null && castOther.getClaimpaydate()!=null && this.getClaimpaydate().equals(castOther.getClaimpaydate()) ) )
 && ( (this.getAllowtype()==castOther.getAllowtype()) || ( this.getAllowtype()!=null && castOther.getAllowtype()!=null && this.getAllowtype().equals(castOther.getAllowtype()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         result = 37 * result + ( getOrderno() == null ? 0 : this.getOrderno().hashCode() );
         result = 37 * result + ( getPolicystatus() == null ? 0 : this.getPolicystatus().hashCode() );
         result = 37 * result + ( getPolicystatusdate() == null ? 0 : this.getPolicystatusdate().hashCode() );
         result = 37 * result + ( getPolicystatus2() == null ? 0 : this.getPolicystatus2().hashCode() );
         result = 37 * result + ( getPolicystatusdate2() == null ? 0 : this.getPolicystatusdate2().hashCode() );
         result = 37 * result + ( getBranchcode() == null ? 0 : this.getBranchcode().hashCode() );
         result = 37 * result + ( getServicebranch() == null ? 0 : this.getServicebranch().hashCode() );
         result = 37 * result + ( getClaimtype() == null ? 0 : this.getClaimtype().hashCode() );
         result = 37 * result + ( getPaytype() == null ? 0 : this.getPaytype().hashCode() );
         result = 37 * result + ( getProofinsuredage() == null ? 0 : this.getProofinsuredage().hashCode() );
         result = 37 * result + ( getDisabilitytype() == null ? 0 : this.getDisabilitytype().hashCode() );
         result = 37 * result + ( getDisnumber() == null ? 0 : this.getDisnumber().hashCode() );
         result = 37 * result + ( getPayrate() == null ? 0 : this.getPayrate().hashCode() );
         result = 37 * result + ( getPayamount() == null ? 0 : this.getPayamount().hashCode() );
         result = 37 * result + ( getAccdamount() == null ? 0 : this.getAccdamount().hashCode() );
         result = 37 * result + ( getSurrenderamount() == null ? 0 : this.getSurrenderamount().hashCode() );
         result = 37 * result + ( getReturnamount() == null ? 0 : this.getReturnamount().hashCode() );
         result = 37 * result + ( getDeductamount() == null ? 0 : this.getDeductamount().hashCode() );
         result = 37 * result + ( getClaimokdate() == null ? 0 : this.getClaimokdate().hashCode() );
         result = 37 * result + ( getClaimpaydate() == null ? 0 : this.getClaimpaydate().hashCode() );
         result = 37 * result + ( getAllowtype() == null ? 0 : this.getAllowtype().hashCode() );
         return result;
   }   


}


