package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgpayrider generated by hbm2java
 */
@Entity
@Table(name="mgpayrider"
)
public class Mgpayrider  implements java.io.Serializable {


     private MgpayriderId id;

    public Mgpayrider() {
    }

    public Mgpayrider(MgpayriderId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate") ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate") ), 
        @AttributeOverride(name="sectioncode", column=@Column(name="sectioncode") ), 
        @AttributeOverride(name="orderno", column=@Column(name="orderno") ), 
        @AttributeOverride(name="policystatus", column=@Column(name="policystatus") ), 
        @AttributeOverride(name="policystatusdate", column=@Column(name="policystatusdate") ), 
        @AttributeOverride(name="policystatus2", column=@Column(name="policystatus2") ), 
        @AttributeOverride(name="policystatusdate2", column=@Column(name="policystatusdate2") ), 
        @AttributeOverride(name="branchcode", column=@Column(name="branchcode") ), 
        @AttributeOverride(name="servicebranch", column=@Column(name="servicebranch") ), 
        @AttributeOverride(name="amestartdate", column=@Column(name="amestartdate") ), 
        @AttributeOverride(name="ameday", column=@Column(name="ameday") ), 
        @AttributeOverride(name="ameexpense", column=@Column(name="ameexpense") ), 
        @AttributeOverride(name="amepayment", column=@Column(name="amepayment") ), 
        @AttributeOverride(name="tdday", column=@Column(name="tdday") ), 
        @AttributeOverride(name="tdstartdate", column=@Column(name="tdstartdate") ), 
        @AttributeOverride(name="tdpayment", column=@Column(name="tdpayment") ), 
        @AttributeOverride(name="returnamount", column=@Column(name="returnamount") ), 
        @AttributeOverride(name="deductamount", column=@Column(name="deductamount") ), 
        @AttributeOverride(name="voiddate", column=@Column(name="voiddate") ), 
        @AttributeOverride(name="claimokdate", column=@Column(name="claimokdate") ), 
        @AttributeOverride(name="claimpaydate", column=@Column(name="claimpaydate") ) } )
    public MgpayriderId getId() {
        return this.id;
    }
    
    public void setId(MgpayriderId id) {
        this.id = id;
    }




}


