package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgpayriderId generated by hbm2java
 */
@Embeddable
public class MgpayriderId  implements java.io.Serializable {


     private String certno;
     private String accidentdate;
     private String receivedate;
     private String sectioncode;
     private String orderno;
     private String policystatus;
     private String policystatusdate;
     private String policystatus2;
     private String policystatusdate2;
     private String branchcode;
     private String servicebranch;
     private String amestartdate;
     private String ameday;
     private String ameexpense;
     private String amepayment;
     private String tdday;
     private String tdstartdate;
     private String tdpayment;
     private String returnamount;
     private String deductamount;
     private String voiddate;
     private String claimokdate;
     private String claimpaydate;

    public MgpayriderId() {
    }

    public MgpayriderId(String certno, String accidentdate, String receivedate, String sectioncode, String orderno, String policystatus, String policystatusdate, String policystatus2, String policystatusdate2, String branchcode, String servicebranch, String amestartdate, String ameday, String ameexpense, String amepayment, String tdday, String tdstartdate, String tdpayment, String returnamount, String deductamount, String voiddate, String claimokdate, String claimpaydate) {
       this.certno = certno;
       this.accidentdate = accidentdate;
       this.receivedate = receivedate;
       this.sectioncode = sectioncode;
       this.orderno = orderno;
       this.policystatus = policystatus;
       this.policystatusdate = policystatusdate;
       this.policystatus2 = policystatus2;
       this.policystatusdate2 = policystatusdate2;
       this.branchcode = branchcode;
       this.servicebranch = servicebranch;
       this.amestartdate = amestartdate;
       this.ameday = ameday;
       this.ameexpense = ameexpense;
       this.amepayment = amepayment;
       this.tdday = tdday;
       this.tdstartdate = tdstartdate;
       this.tdpayment = tdpayment;
       this.returnamount = returnamount;
       this.deductamount = deductamount;
       this.voiddate = voiddate;
       this.claimokdate = claimokdate;
       this.claimpaydate = claimpaydate;
    }
   

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="accidentdate")
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="receivedate")
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="sectioncode")
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @Column(name="orderno")
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    @Column(name="policystatus")
    public String getPolicystatus() {
        return this.policystatus;
    }
    
    public void setPolicystatus(String policystatus) {
        this.policystatus = policystatus;
    }

    @Column(name="policystatusdate")
    public String getPolicystatusdate() {
        return this.policystatusdate;
    }
    
    public void setPolicystatusdate(String policystatusdate) {
        this.policystatusdate = policystatusdate;
    }

    @Column(name="policystatus2")
    public String getPolicystatus2() {
        return this.policystatus2;
    }
    
    public void setPolicystatus2(String policystatus2) {
        this.policystatus2 = policystatus2;
    }

    @Column(name="policystatusdate2")
    public String getPolicystatusdate2() {
        return this.policystatusdate2;
    }
    
    public void setPolicystatusdate2(String policystatusdate2) {
        this.policystatusdate2 = policystatusdate2;
    }

    @Column(name="branchcode")
    public String getBranchcode() {
        return this.branchcode;
    }
    
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    @Column(name="servicebranch")
    public String getServicebranch() {
        return this.servicebranch;
    }
    
    public void setServicebranch(String servicebranch) {
        this.servicebranch = servicebranch;
    }

    @Column(name="amestartdate")
    public String getAmestartdate() {
        return this.amestartdate;
    }
    
    public void setAmestartdate(String amestartdate) {
        this.amestartdate = amestartdate;
    }

    @Column(name="ameday")
    public String getAmeday() {
        return this.ameday;
    }
    
    public void setAmeday(String ameday) {
        this.ameday = ameday;
    }

    @Column(name="ameexpense")
    public String getAmeexpense() {
        return this.ameexpense;
    }
    
    public void setAmeexpense(String ameexpense) {
        this.ameexpense = ameexpense;
    }

    @Column(name="amepayment")
    public String getAmepayment() {
        return this.amepayment;
    }
    
    public void setAmepayment(String amepayment) {
        this.amepayment = amepayment;
    }

    @Column(name="tdday")
    public String getTdday() {
        return this.tdday;
    }
    
    public void setTdday(String tdday) {
        this.tdday = tdday;
    }

    @Column(name="tdstartdate")
    public String getTdstartdate() {
        return this.tdstartdate;
    }
    
    public void setTdstartdate(String tdstartdate) {
        this.tdstartdate = tdstartdate;
    }

    @Column(name="tdpayment")
    public String getTdpayment() {
        return this.tdpayment;
    }
    
    public void setTdpayment(String tdpayment) {
        this.tdpayment = tdpayment;
    }

    @Column(name="returnamount")
    public String getReturnamount() {
        return this.returnamount;
    }
    
    public void setReturnamount(String returnamount) {
        this.returnamount = returnamount;
    }

    @Column(name="deductamount")
    public String getDeductamount() {
        return this.deductamount;
    }
    
    public void setDeductamount(String deductamount) {
        this.deductamount = deductamount;
    }

    @Column(name="voiddate")
    public String getVoiddate() {
        return this.voiddate;
    }
    
    public void setVoiddate(String voiddate) {
        this.voiddate = voiddate;
    }

    @Column(name="claimokdate")
    public String getClaimokdate() {
        return this.claimokdate;
    }
    
    public void setClaimokdate(String claimokdate) {
        this.claimokdate = claimokdate;
    }

    @Column(name="claimpaydate")
    public String getClaimpaydate() {
        return this.claimpaydate;
    }
    
    public void setClaimpaydate(String claimpaydate) {
        this.claimpaydate = claimpaydate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgpayriderId) ) return false;
		 MgpayriderId castOther = ( MgpayriderId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) )
 && ( (this.getOrderno()==castOther.getOrderno()) || ( this.getOrderno()!=null && castOther.getOrderno()!=null && this.getOrderno().equals(castOther.getOrderno()) ) )
 && ( (this.getPolicystatus()==castOther.getPolicystatus()) || ( this.getPolicystatus()!=null && castOther.getPolicystatus()!=null && this.getPolicystatus().equals(castOther.getPolicystatus()) ) )
 && ( (this.getPolicystatusdate()==castOther.getPolicystatusdate()) || ( this.getPolicystatusdate()!=null && castOther.getPolicystatusdate()!=null && this.getPolicystatusdate().equals(castOther.getPolicystatusdate()) ) )
 && ( (this.getPolicystatus2()==castOther.getPolicystatus2()) || ( this.getPolicystatus2()!=null && castOther.getPolicystatus2()!=null && this.getPolicystatus2().equals(castOther.getPolicystatus2()) ) )
 && ( (this.getPolicystatusdate2()==castOther.getPolicystatusdate2()) || ( this.getPolicystatusdate2()!=null && castOther.getPolicystatusdate2()!=null && this.getPolicystatusdate2().equals(castOther.getPolicystatusdate2()) ) )
 && ( (this.getBranchcode()==castOther.getBranchcode()) || ( this.getBranchcode()!=null && castOther.getBranchcode()!=null && this.getBranchcode().equals(castOther.getBranchcode()) ) )
 && ( (this.getServicebranch()==castOther.getServicebranch()) || ( this.getServicebranch()!=null && castOther.getServicebranch()!=null && this.getServicebranch().equals(castOther.getServicebranch()) ) )
 && ( (this.getAmestartdate()==castOther.getAmestartdate()) || ( this.getAmestartdate()!=null && castOther.getAmestartdate()!=null && this.getAmestartdate().equals(castOther.getAmestartdate()) ) )
 && ( (this.getAmeday()==castOther.getAmeday()) || ( this.getAmeday()!=null && castOther.getAmeday()!=null && this.getAmeday().equals(castOther.getAmeday()) ) )
 && ( (this.getAmeexpense()==castOther.getAmeexpense()) || ( this.getAmeexpense()!=null && castOther.getAmeexpense()!=null && this.getAmeexpense().equals(castOther.getAmeexpense()) ) )
 && ( (this.getAmepayment()==castOther.getAmepayment()) || ( this.getAmepayment()!=null && castOther.getAmepayment()!=null && this.getAmepayment().equals(castOther.getAmepayment()) ) )
 && ( (this.getTdday()==castOther.getTdday()) || ( this.getTdday()!=null && castOther.getTdday()!=null && this.getTdday().equals(castOther.getTdday()) ) )
 && ( (this.getTdstartdate()==castOther.getTdstartdate()) || ( this.getTdstartdate()!=null && castOther.getTdstartdate()!=null && this.getTdstartdate().equals(castOther.getTdstartdate()) ) )
 && ( (this.getTdpayment()==castOther.getTdpayment()) || ( this.getTdpayment()!=null && castOther.getTdpayment()!=null && this.getTdpayment().equals(castOther.getTdpayment()) ) )
 && ( (this.getReturnamount()==castOther.getReturnamount()) || ( this.getReturnamount()!=null && castOther.getReturnamount()!=null && this.getReturnamount().equals(castOther.getReturnamount()) ) )
 && ( (this.getDeductamount()==castOther.getDeductamount()) || ( this.getDeductamount()!=null && castOther.getDeductamount()!=null && this.getDeductamount().equals(castOther.getDeductamount()) ) )
 && ( (this.getVoiddate()==castOther.getVoiddate()) || ( this.getVoiddate()!=null && castOther.getVoiddate()!=null && this.getVoiddate().equals(castOther.getVoiddate()) ) )
 && ( (this.getClaimokdate()==castOther.getClaimokdate()) || ( this.getClaimokdate()!=null && castOther.getClaimokdate()!=null && this.getClaimokdate().equals(castOther.getClaimokdate()) ) )
 && ( (this.getClaimpaydate()==castOther.getClaimpaydate()) || ( this.getClaimpaydate()!=null && castOther.getClaimpaydate()!=null && this.getClaimpaydate().equals(castOther.getClaimpaydate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         result = 37 * result + ( getOrderno() == null ? 0 : this.getOrderno().hashCode() );
         result = 37 * result + ( getPolicystatus() == null ? 0 : this.getPolicystatus().hashCode() );
         result = 37 * result + ( getPolicystatusdate() == null ? 0 : this.getPolicystatusdate().hashCode() );
         result = 37 * result + ( getPolicystatus2() == null ? 0 : this.getPolicystatus2().hashCode() );
         result = 37 * result + ( getPolicystatusdate2() == null ? 0 : this.getPolicystatusdate2().hashCode() );
         result = 37 * result + ( getBranchcode() == null ? 0 : this.getBranchcode().hashCode() );
         result = 37 * result + ( getServicebranch() == null ? 0 : this.getServicebranch().hashCode() );
         result = 37 * result + ( getAmestartdate() == null ? 0 : this.getAmestartdate().hashCode() );
         result = 37 * result + ( getAmeday() == null ? 0 : this.getAmeday().hashCode() );
         result = 37 * result + ( getAmeexpense() == null ? 0 : this.getAmeexpense().hashCode() );
         result = 37 * result + ( getAmepayment() == null ? 0 : this.getAmepayment().hashCode() );
         result = 37 * result + ( getTdday() == null ? 0 : this.getTdday().hashCode() );
         result = 37 * result + ( getTdstartdate() == null ? 0 : this.getTdstartdate().hashCode() );
         result = 37 * result + ( getTdpayment() == null ? 0 : this.getTdpayment().hashCode() );
         result = 37 * result + ( getReturnamount() == null ? 0 : this.getReturnamount().hashCode() );
         result = 37 * result + ( getDeductamount() == null ? 0 : this.getDeductamount().hashCode() );
         result = 37 * result + ( getVoiddate() == null ? 0 : this.getVoiddate().hashCode() );
         result = 37 * result + ( getClaimokdate() == null ? 0 : this.getClaimokdate().hashCode() );
         result = 37 * result + ( getClaimpaydate() == null ? 0 : this.getClaimpaydate().hashCode() );
         return result;
   }   


}


