package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgpay generated by hbm2java
 */
@Entity
@Table(name="mgpay"
)
public class Mgpay  implements java.io.Serializable {


     private MgpayId id;

    public Mgpay() {
    }

    public Mgpay(MgpayId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate") ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate") ), 
        @AttributeOverride(name="sectioncode", column=@Column(name="sectioncode") ), 
        @AttributeOverride(name="orderno", column=@Column(name="orderno") ), 
        @AttributeOverride(name="policystatus", column=@Column(name="policystatus") ), 
        @AttributeOverride(name="policystatusdate", column=@Column(name="policystatusdate") ), 
        @AttributeOverride(name="policystatus2", column=@Column(name="policystatus2") ), 
        @AttributeOverride(name="policystatusdate2", column=@Column(name="policystatusdate2") ), 
        @AttributeOverride(name="branchcode", column=@Column(name="branchcode") ), 
        @AttributeOverride(name="servicebranch", column=@Column(name="servicebranch") ), 
        @AttributeOverride(name="claimtype", column=@Column(name="claimtype") ), 
        @AttributeOverride(name="paytype", column=@Column(name="paytype") ), 
        @AttributeOverride(name="proofinsuredage", column=@Column(name="proofinsuredage") ), 
        @AttributeOverride(name="disabilitytype", column=@Column(name="disabilitytype") ), 
        @AttributeOverride(name="disnumber", column=@Column(name="disnumber") ), 
        @AttributeOverride(name="payrate", column=@Column(name="payrate") ), 
        @AttributeOverride(name="payamount", column=@Column(name="payamount") ), 
        @AttributeOverride(name="accdamount", column=@Column(name="accdamount") ), 
        @AttributeOverride(name="surrenderamount", column=@Column(name="surrenderamount") ), 
        @AttributeOverride(name="returnamount", column=@Column(name="returnamount") ), 
        @AttributeOverride(name="deductamount", column=@Column(name="deductamount") ), 
        @AttributeOverride(name="claimokdate", column=@Column(name="claimokdate") ), 
        @AttributeOverride(name="claimpaydate", column=@Column(name="claimpaydate") ), 
        @AttributeOverride(name="allowtype", column=@Column(name="allowtype") ) } )
    public MgpayId getId() {
        return this.id;
    }
    
    public void setId(MgpayId id) {
        this.id = id;
    }




}


