package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgreceiver generated by hbm2java
 */
@Entity
@Table(name="mgreceiver"
)
public class Mgreceiver  implements java.io.Serializable {


     private MgreceiverId id;

    public Mgreceiver() {
    }

    public Mgreceiver(MgreceiverId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate") ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate") ), 
        @AttributeOverride(name="seqno", column=@Column(name="seqno") ), 
        @AttributeOverride(name="prename", column=@Column(name="prename") ), 
        @AttributeOverride(name="firstname", column=@Column(name="firstname") ), 
        @AttributeOverride(name="lastname", column=@Column(name="lastname") ), 
        @AttributeOverride(name="type", column=@Column(name="type") ), 
        @AttributeOverride(name="payamount", column=@Column(name="payamount") ), 
        @AttributeOverride(name="address", column=@Column(name="address") ), 
        @AttributeOverride(name="tumbon", column=@Column(name="tumbon") ), 
        @AttributeOverride(name="zipcode", column=@Column(name="zipcode") ), 
        @AttributeOverride(name="mobilephone", column=@Column(name="mobilephone") ), 
        @AttributeOverride(name="citizenid", column=@Column(name="citizenid") ), 
        @AttributeOverride(name="paytype", column=@Column(name="paytype") ), 
        @AttributeOverride(name="banktype", column=@Column(name="banktype") ), 
        @AttributeOverride(name="bankcode", column=@Column(name="bankcode") ), 
        @AttributeOverride(name="bankbranch", column=@Column(name="bankbranch") ), 
        @AttributeOverride(name="bankaccount", column=@Column(name="bankaccount") ), 
        @AttributeOverride(name="guardianbeneficiary", column=@Column(name="guardianbeneficiary") ), 
        @AttributeOverride(name="ispay", column=@Column(name="ispay") ), 
        @AttributeOverride(name="haveindicia", column=@Column(name="haveindicia") ), 
        @AttributeOverride(name="countrycode", column=@Column(name="countrycode") ), 
        @AttributeOverride(name="claimpaydate", column=@Column(name="claimpaydate ") ), 
        @AttributeOverride(name="bookstatus", column=@Column(name="bookstatus") ), 
        @AttributeOverride(name="chqdate", column=@Column(name="chqdate") ), 
        @AttributeOverride(name="chqno", column=@Column(name="chqno") ), 
        @AttributeOverride(name="docno", column=@Column(name="docno") ), 
        @AttributeOverride(name="isbeneficiarykilled", column=@Column(name="isbeneficiarykilled") ), 
        @AttributeOverride(name="birthdate", column=@Column(name="birthdate") ) } )
    public MgreceiverId getId() {
        return this.id;
    }
    
    public void setId(MgreceiverId id) {
        this.id = id;
    }




}


