package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NameId generated by hbm2java
 */
@Embeddable
public class NameId  implements java.io.Serializable {


     private String nameid;
     private String personid;
     private String prename;
     private String firstname;
     private String lastname;
     private String startdate;

    public NameId() {
    }

    public NameId(String nameid, String personid, String prename, String firstname, String lastname, String startdate) {
       this.nameid = nameid;
       this.personid = personid;
       this.prename = prename;
       this.firstname = firstname;
       this.lastname = lastname;
       this.startdate = startdate;
    }
   

    @Column(name="nameid")
    public String getNameid() {
        return this.nameid;
    }
    
    public void setNameid(String nameid) {
        this.nameid = nameid;
    }

    @Column(name="personid")
    public String getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(String personid) {
        this.personid = personid;
    }

    @Column(name="prename")
    public String getPrename() {
        return this.prename;
    }
    
    public void setPrename(String prename) {
        this.prename = prename;
    }

    @Column(name="firstname")
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column(name="lastname")
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name="startdate")
    public String getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NameId) ) return false;
		 NameId castOther = ( NameId ) other; 
         
		 return ( (this.getNameid()==castOther.getNameid()) || ( this.getNameid()!=null && castOther.getNameid()!=null && this.getNameid().equals(castOther.getNameid()) ) )
 && ( (this.getPersonid()==castOther.getPersonid()) || ( this.getPersonid()!=null && castOther.getPersonid()!=null && this.getPersonid().equals(castOther.getPersonid()) ) )
 && ( (this.getPrename()==castOther.getPrename()) || ( this.getPrename()!=null && castOther.getPrename()!=null && this.getPrename().equals(castOther.getPrename()) ) )
 && ( (this.getFirstname()==castOther.getFirstname()) || ( this.getFirstname()!=null && castOther.getFirstname()!=null && this.getFirstname().equals(castOther.getFirstname()) ) )
 && ( (this.getLastname()==castOther.getLastname()) || ( this.getLastname()!=null && castOther.getLastname()!=null && this.getLastname().equals(castOther.getLastname()) ) )
 && ( (this.getStartdate()==castOther.getStartdate()) || ( this.getStartdate()!=null && castOther.getStartdate()!=null && this.getStartdate().equals(castOther.getStartdate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNameid() == null ? 0 : this.getNameid().hashCode() );
         result = 37 * result + ( getPersonid() == null ? 0 : this.getPersonid().hashCode() );
         result = 37 * result + ( getPrename() == null ? 0 : this.getPrename().hashCode() );
         result = 37 * result + ( getFirstname() == null ? 0 : this.getFirstname().hashCode() );
         result = 37 * result + ( getLastname() == null ? 0 : this.getLastname().hashCode() );
         result = 37 * result + ( getStartdate() == null ? 0 : this.getStartdate().hashCode() );
         return result;
   }   


}


