package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonId generated by hbm2java
 */
@Embeddable
public class PersonId  implements java.io.Serializable {


     private String personid;
     private String referenceid;
     private String referencetype;
     private String birthdate;
     private String sex;
     private String customerid;
     private String bluecard;
     private String reserve;

    public PersonId() {
    }

    public PersonId(String personid, String referenceid, String referencetype, String birthdate, String sex, String customerid, String bluecard, String reserve) {
       this.personid = personid;
       this.referenceid = referenceid;
       this.referencetype = referencetype;
       this.birthdate = birthdate;
       this.sex = sex;
       this.customerid = customerid;
       this.bluecard = bluecard;
       this.reserve = reserve;
    }
   

    @Column(name="personid")
    public String getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(String personid) {
        this.personid = personid;
    }

    @Column(name="referenceid")
    public String getReferenceid() {
        return this.referenceid;
    }
    
    public void setReferenceid(String referenceid) {
        this.referenceid = referenceid;
    }

    @Column(name="referencetype")
    public String getReferencetype() {
        return this.referencetype;
    }
    
    public void setReferencetype(String referencetype) {
        this.referencetype = referencetype;
    }

    @Column(name="birthdate")
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    @Column(name="sex")
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    @Column(name="customerid")
    public String getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    @Column(name="bluecard")
    public String getBluecard() {
        return this.bluecard;
    }
    
    public void setBluecard(String bluecard) {
        this.bluecard = bluecard;
    }

    @Column(name="reserve")
    public String getReserve() {
        return this.reserve;
    }
    
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonId) ) return false;
		 PersonId castOther = ( PersonId ) other; 
         
		 return ( (this.getPersonid()==castOther.getPersonid()) || ( this.getPersonid()!=null && castOther.getPersonid()!=null && this.getPersonid().equals(castOther.getPersonid()) ) )
 && ( (this.getReferenceid()==castOther.getReferenceid()) || ( this.getReferenceid()!=null && castOther.getReferenceid()!=null && this.getReferenceid().equals(castOther.getReferenceid()) ) )
 && ( (this.getReferencetype()==castOther.getReferencetype()) || ( this.getReferencetype()!=null && castOther.getReferencetype()!=null && this.getReferencetype().equals(castOther.getReferencetype()) ) )
 && ( (this.getBirthdate()==castOther.getBirthdate()) || ( this.getBirthdate()!=null && castOther.getBirthdate()!=null && this.getBirthdate().equals(castOther.getBirthdate()) ) )
 && ( (this.getSex()==castOther.getSex()) || ( this.getSex()!=null && castOther.getSex()!=null && this.getSex().equals(castOther.getSex()) ) )
 && ( (this.getCustomerid()==castOther.getCustomerid()) || ( this.getCustomerid()!=null && castOther.getCustomerid()!=null && this.getCustomerid().equals(castOther.getCustomerid()) ) )
 && ( (this.getBluecard()==castOther.getBluecard()) || ( this.getBluecard()!=null && castOther.getBluecard()!=null && this.getBluecard().equals(castOther.getBluecard()) ) )
 && ( (this.getReserve()==castOther.getReserve()) || ( this.getReserve()!=null && castOther.getReserve()!=null && this.getReserve().equals(castOther.getReserve()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPersonid() == null ? 0 : this.getPersonid().hashCode() );
         result = 37 * result + ( getReferenceid() == null ? 0 : this.getReferenceid().hashCode() );
         result = 37 * result + ( getReferencetype() == null ? 0 : this.getReferencetype().hashCode() );
         result = 37 * result + ( getBirthdate() == null ? 0 : this.getBirthdate().hashCode() );
         result = 37 * result + ( getSex() == null ? 0 : this.getSex().hashCode() );
         result = 37 * result + ( getCustomerid() == null ? 0 : this.getCustomerid().hashCode() );
         result = 37 * result + ( getBluecard() == null ? 0 : this.getBluecard().hashCode() );
         result = 37 * result + ( getReserve() == null ? 0 : this.getReserve().hashCode() );
         return result;
   }   


}


