package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
)
public class Person  implements java.io.Serializable {


     private PersonId id;

    public Person() {
    }

    public Person(PersonId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="personid", column=@Column(name="personid") ), 
        @AttributeOverride(name="referenceid", column=@Column(name="referenceid") ), 
        @AttributeOverride(name="referencetype", column=@Column(name="referencetype") ), 
        @AttributeOverride(name="birthdate", column=@Column(name="birthdate") ), 
        @AttributeOverride(name="sex", column=@Column(name="sex") ), 
        @AttributeOverride(name="customerid", column=@Column(name="customerid") ), 
        @AttributeOverride(name="bluecard", column=@Column(name="bluecard") ), 
        @AttributeOverride(name="reserve", column=@Column(name="reserve") ) } )
    public PersonId getId() {
        return this.id;
    }
    
    public void setId(PersonId id) {
        this.id = id;
    }




}


