package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Policy generated by hbm2java
 */
@Entity
@Table(name="policy"
)
public class Policy  implements java.io.Serializable {


     private PolicyId id;

    public Policy() {
    }

    public Policy(PolicyId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="rate", column=@Column(name="rate") ), 
        @AttributeOverride(name="name", column=@Column(name="name") ), 
        @AttributeOverride(name="type", column=@Column(name="type") ), 
        @AttributeOverride(name="effectivedate", column=@Column(name="effectivedate") ), 
        @AttributeOverride(name="planname", column=@Column(name="planname") ), 
        @AttributeOverride(name="riderplan", column=@Column(name="riderplan") ), 
        @AttributeOverride(name="tlbranch", column=@Column(name="tlbranch") ) } )
    public PolicyId getId() {
        return this.id;
    }
    
    public void setId(PolicyId id) {
        this.id = id;
    }




}


