package th.co.ipassion.testtool.entity.tlitext;
// Generated Dec 29, 2017 9:15:09 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PolicyId generated by hbm2java
 */
@Embeddable
public class PolicyId  implements java.io.Serializable {


     private String policyno;
     private String rate;
     private String name;
     private String type;
     private String effectivedate;
     private String planname;
     private String riderplan;
     private String tlbranch;

    public PolicyId() {
    }

    public PolicyId(String policyno, String rate, String name, String type, String effectivedate, String planname, String riderplan, String tlbranch) {
       this.policyno = policyno;
       this.rate = rate;
       this.name = name;
       this.type = type;
       this.effectivedate = effectivedate;
       this.planname = planname;
       this.riderplan = riderplan;
       this.tlbranch = tlbranch;
    }
   

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="rate")
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }

    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Column(name="type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Column(name="effectivedate")
    public String getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(String effectivedate) {
        this.effectivedate = effectivedate;
    }

    @Column(name="planname")
    public String getPlanname() {
        return this.planname;
    }
    
    public void setPlanname(String planname) {
        this.planname = planname;
    }

    @Column(name="riderplan")
    public String getRiderplan() {
        return this.riderplan;
    }
    
    public void setRiderplan(String riderplan) {
        this.riderplan = riderplan;
    }

    @Column(name="tlbranch")
    public String getTlbranch() {
        return this.tlbranch;
    }
    
    public void setTlbranch(String tlbranch) {
        this.tlbranch = tlbranch;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PolicyId) ) return false;
		 PolicyId castOther = ( PolicyId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getRate()==castOther.getRate()) || ( this.getRate()!=null && castOther.getRate()!=null && this.getRate().equals(castOther.getRate()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getEffectivedate()==castOther.getEffectivedate()) || ( this.getEffectivedate()!=null && castOther.getEffectivedate()!=null && this.getEffectivedate().equals(castOther.getEffectivedate()) ) )
 && ( (this.getPlanname()==castOther.getPlanname()) || ( this.getPlanname()!=null && castOther.getPlanname()!=null && this.getPlanname().equals(castOther.getPlanname()) ) )
 && ( (this.getRiderplan()==castOther.getRiderplan()) || ( this.getRiderplan()!=null && castOther.getRiderplan()!=null && this.getRiderplan().equals(castOther.getRiderplan()) ) )
 && ( (this.getTlbranch()==castOther.getTlbranch()) || ( this.getTlbranch()!=null && castOther.getTlbranch()!=null && this.getTlbranch().equals(castOther.getTlbranch()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getRate() == null ? 0 : this.getRate().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getEffectivedate() == null ? 0 : this.getEffectivedate().hashCode() );
         result = 37 * result + ( getPlanname() == null ? 0 : this.getPlanname().hashCode() );
         result = 37 * result + ( getRiderplan() == null ? 0 : this.getRiderplan().hashCode() );
         result = 37 * result + ( getTlbranch() == null ? 0 : this.getTlbranch().hashCode() );
         return result;
   }   


}


