package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomersaId generated by hbm2java
 */
@Embeddable
public class CustomersaId  implements java.io.Serializable {


     private String customercode;
     private String policyno;
     private String saLifetpd;
     private String saLife;
     private String saTpd;
     private String saTd;
     private String saAdd;
     private String saAdb;
     private String saHa;
     private String saHb;
     private String saMe;
     private String saPa;
     private String saPh;
     private String saCi;
     private String flaglife;
     private String flaglifetpd;
     private String ia;
     private String sa;
     private String transdate;
     private String miAmount;
     private String mexpiryLife;
     private String expiryTpd;
     private String expiryTd;
     private String expiryAdd;
     private String expiryAdb;
     private String expiryHa;
     private String expiryHb;
     private String expiryMe;
     private String expiryPa;
     private String expiryPh;
     private String expiryCi;
     private String saMa;
     private String expiryMa;
     private String saMc;
     private String expiryMc;

    public CustomersaId() {
    }

    public CustomersaId(String customercode, String policyno, String saLifetpd, String saLife, String saTpd, String saTd, String saAdd, String saAdb, String saHa, String saHb, String saMe, String saPa, String saPh, String saCi, String flaglife, String flaglifetpd, String ia, String sa, String transdate, String miAmount, String mexpiryLife, String expiryTpd, String expiryTd, String expiryAdd, String expiryAdb, String expiryHa, String expiryHb, String expiryMe, String expiryPa, String expiryPh, String expiryCi, String saMa, String expiryMa, String saMc, String expiryMc) {
       this.customercode = customercode;
       this.policyno = policyno;
       this.saLifetpd = saLifetpd;
       this.saLife = saLife;
       this.saTpd = saTpd;
       this.saTd = saTd;
       this.saAdd = saAdd;
       this.saAdb = saAdb;
       this.saHa = saHa;
       this.saHb = saHb;
       this.saMe = saMe;
       this.saPa = saPa;
       this.saPh = saPh;
       this.saCi = saCi;
       this.flaglife = flaglife;
       this.flaglifetpd = flaglifetpd;
       this.ia = ia;
       this.sa = sa;
       this.transdate = transdate;
       this.miAmount = miAmount;
       this.mexpiryLife = mexpiryLife;
       this.expiryTpd = expiryTpd;
       this.expiryTd = expiryTd;
       this.expiryAdd = expiryAdd;
       this.expiryAdb = expiryAdb;
       this.expiryHa = expiryHa;
       this.expiryHb = expiryHb;
       this.expiryMe = expiryMe;
       this.expiryPa = expiryPa;
       this.expiryPh = expiryPh;
       this.expiryCi = expiryCi;
       this.saMa = saMa;
       this.expiryMa = expiryMa;
       this.saMc = saMc;
       this.expiryMc = expiryMc;
    }
   

    @Column(name="customercode")
    public String getCustomercode() {
        return this.customercode;
    }
    
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="sa_lifetpd")
    public String getSaLifetpd() {
        return this.saLifetpd;
    }
    
    public void setSaLifetpd(String saLifetpd) {
        this.saLifetpd = saLifetpd;
    }

    @Column(name="sa_life")
    public String getSaLife() {
        return this.saLife;
    }
    
    public void setSaLife(String saLife) {
        this.saLife = saLife;
    }

    @Column(name="sa_tpd")
    public String getSaTpd() {
        return this.saTpd;
    }
    
    public void setSaTpd(String saTpd) {
        this.saTpd = saTpd;
    }

    @Column(name="sa_td")
    public String getSaTd() {
        return this.saTd;
    }
    
    public void setSaTd(String saTd) {
        this.saTd = saTd;
    }

    @Column(name="sa_add")
    public String getSaAdd() {
        return this.saAdd;
    }
    
    public void setSaAdd(String saAdd) {
        this.saAdd = saAdd;
    }

    @Column(name="sa_adb")
    public String getSaAdb() {
        return this.saAdb;
    }
    
    public void setSaAdb(String saAdb) {
        this.saAdb = saAdb;
    }

    @Column(name="sa_ha")
    public String getSaHa() {
        return this.saHa;
    }
    
    public void setSaHa(String saHa) {
        this.saHa = saHa;
    }

    @Column(name="sa_hb")
    public String getSaHb() {
        return this.saHb;
    }
    
    public void setSaHb(String saHb) {
        this.saHb = saHb;
    }

    @Column(name="sa_me")
    public String getSaMe() {
        return this.saMe;
    }
    
    public void setSaMe(String saMe) {
        this.saMe = saMe;
    }

    @Column(name="sa_pa")
    public String getSaPa() {
        return this.saPa;
    }
    
    public void setSaPa(String saPa) {
        this.saPa = saPa;
    }

    @Column(name="sa_ph")
    public String getSaPh() {
        return this.saPh;
    }
    
    public void setSaPh(String saPh) {
        this.saPh = saPh;
    }

    @Column(name="sa_ci")
    public String getSaCi() {
        return this.saCi;
    }
    
    public void setSaCi(String saCi) {
        this.saCi = saCi;
    }

    @Column(name="flaglife")
    public String getFlaglife() {
        return this.flaglife;
    }
    
    public void setFlaglife(String flaglife) {
        this.flaglife = flaglife;
    }

    @Column(name="flaglifetpd")
    public String getFlaglifetpd() {
        return this.flaglifetpd;
    }
    
    public void setFlaglifetpd(String flaglifetpd) {
        this.flaglifetpd = flaglifetpd;
    }

    @Column(name="ia")
    public String getIa() {
        return this.ia;
    }
    
    public void setIa(String ia) {
        this.ia = ia;
    }

    @Column(name="sa")
    public String getSa() {
        return this.sa;
    }
    
    public void setSa(String sa) {
        this.sa = sa;
    }

    @Column(name="transdate")
    public String getTransdate() {
        return this.transdate;
    }
    
    public void setTransdate(String transdate) {
        this.transdate = transdate;
    }

    @Column(name="mi_amount")
    public String getMiAmount() {
        return this.miAmount;
    }
    
    public void setMiAmount(String miAmount) {
        this.miAmount = miAmount;
    }

    @Column(name="mexpiry_life")
    public String getMexpiryLife() {
        return this.mexpiryLife;
    }
    
    public void setMexpiryLife(String mexpiryLife) {
        this.mexpiryLife = mexpiryLife;
    }

    @Column(name="expiry_tpd")
    public String getExpiryTpd() {
        return this.expiryTpd;
    }
    
    public void setExpiryTpd(String expiryTpd) {
        this.expiryTpd = expiryTpd;
    }

    @Column(name="expiry_td")
    public String getExpiryTd() {
        return this.expiryTd;
    }
    
    public void setExpiryTd(String expiryTd) {
        this.expiryTd = expiryTd;
    }

    @Column(name="expiry_add")
    public String getExpiryAdd() {
        return this.expiryAdd;
    }
    
    public void setExpiryAdd(String expiryAdd) {
        this.expiryAdd = expiryAdd;
    }

    @Column(name="expiry_adb")
    public String getExpiryAdb() {
        return this.expiryAdb;
    }
    
    public void setExpiryAdb(String expiryAdb) {
        this.expiryAdb = expiryAdb;
    }

    @Column(name="expiry_ha")
    public String getExpiryHa() {
        return this.expiryHa;
    }
    
    public void setExpiryHa(String expiryHa) {
        this.expiryHa = expiryHa;
    }

    @Column(name="expiry_hb")
    public String getExpiryHb() {
        return this.expiryHb;
    }
    
    public void setExpiryHb(String expiryHb) {
        this.expiryHb = expiryHb;
    }

    @Column(name="expiry_me")
    public String getExpiryMe() {
        return this.expiryMe;
    }
    
    public void setExpiryMe(String expiryMe) {
        this.expiryMe = expiryMe;
    }

    @Column(name="expiry_pa")
    public String getExpiryPa() {
        return this.expiryPa;
    }
    
    public void setExpiryPa(String expiryPa) {
        this.expiryPa = expiryPa;
    }

    @Column(name="expiry_ph")
    public String getExpiryPh() {
        return this.expiryPh;
    }
    
    public void setExpiryPh(String expiryPh) {
        this.expiryPh = expiryPh;
    }

    @Column(name="expiry_ci")
    public String getExpiryCi() {
        return this.expiryCi;
    }
    
    public void setExpiryCi(String expiryCi) {
        this.expiryCi = expiryCi;
    }

    @Column(name="sa_ma")
    public String getSaMa() {
        return this.saMa;
    }
    
    public void setSaMa(String saMa) {
        this.saMa = saMa;
    }

    @Column(name="expiry_ma")
    public String getExpiryMa() {
        return this.expiryMa;
    }
    
    public void setExpiryMa(String expiryMa) {
        this.expiryMa = expiryMa;
    }

    @Column(name="sa_mc")
    public String getSaMc() {
        return this.saMc;
    }
    
    public void setSaMc(String saMc) {
        this.saMc = saMc;
    }

    @Column(name="expiry_mc")
    public String getExpiryMc() {
        return this.expiryMc;
    }
    
    public void setExpiryMc(String expiryMc) {
        this.expiryMc = expiryMc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomersaId) ) return false;
		 CustomersaId castOther = ( CustomersaId ) other; 
         
		 return ( (this.getCustomercode()==castOther.getCustomercode()) || ( this.getCustomercode()!=null && castOther.getCustomercode()!=null && this.getCustomercode().equals(castOther.getCustomercode()) ) )
 && ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getSaLifetpd()==castOther.getSaLifetpd()) || ( this.getSaLifetpd()!=null && castOther.getSaLifetpd()!=null && this.getSaLifetpd().equals(castOther.getSaLifetpd()) ) )
 && ( (this.getSaLife()==castOther.getSaLife()) || ( this.getSaLife()!=null && castOther.getSaLife()!=null && this.getSaLife().equals(castOther.getSaLife()) ) )
 && ( (this.getSaTpd()==castOther.getSaTpd()) || ( this.getSaTpd()!=null && castOther.getSaTpd()!=null && this.getSaTpd().equals(castOther.getSaTpd()) ) )
 && ( (this.getSaTd()==castOther.getSaTd()) || ( this.getSaTd()!=null && castOther.getSaTd()!=null && this.getSaTd().equals(castOther.getSaTd()) ) )
 && ( (this.getSaAdd()==castOther.getSaAdd()) || ( this.getSaAdd()!=null && castOther.getSaAdd()!=null && this.getSaAdd().equals(castOther.getSaAdd()) ) )
 && ( (this.getSaAdb()==castOther.getSaAdb()) || ( this.getSaAdb()!=null && castOther.getSaAdb()!=null && this.getSaAdb().equals(castOther.getSaAdb()) ) )
 && ( (this.getSaHa()==castOther.getSaHa()) || ( this.getSaHa()!=null && castOther.getSaHa()!=null && this.getSaHa().equals(castOther.getSaHa()) ) )
 && ( (this.getSaHb()==castOther.getSaHb()) || ( this.getSaHb()!=null && castOther.getSaHb()!=null && this.getSaHb().equals(castOther.getSaHb()) ) )
 && ( (this.getSaMe()==castOther.getSaMe()) || ( this.getSaMe()!=null && castOther.getSaMe()!=null && this.getSaMe().equals(castOther.getSaMe()) ) )
 && ( (this.getSaPa()==castOther.getSaPa()) || ( this.getSaPa()!=null && castOther.getSaPa()!=null && this.getSaPa().equals(castOther.getSaPa()) ) )
 && ( (this.getSaPh()==castOther.getSaPh()) || ( this.getSaPh()!=null && castOther.getSaPh()!=null && this.getSaPh().equals(castOther.getSaPh()) ) )
 && ( (this.getSaCi()==castOther.getSaCi()) || ( this.getSaCi()!=null && castOther.getSaCi()!=null && this.getSaCi().equals(castOther.getSaCi()) ) )
 && ( (this.getFlaglife()==castOther.getFlaglife()) || ( this.getFlaglife()!=null && castOther.getFlaglife()!=null && this.getFlaglife().equals(castOther.getFlaglife()) ) )
 && ( (this.getFlaglifetpd()==castOther.getFlaglifetpd()) || ( this.getFlaglifetpd()!=null && castOther.getFlaglifetpd()!=null && this.getFlaglifetpd().equals(castOther.getFlaglifetpd()) ) )
 && ( (this.getIa()==castOther.getIa()) || ( this.getIa()!=null && castOther.getIa()!=null && this.getIa().equals(castOther.getIa()) ) )
 && ( (this.getSa()==castOther.getSa()) || ( this.getSa()!=null && castOther.getSa()!=null && this.getSa().equals(castOther.getSa()) ) )
 && ( (this.getTransdate()==castOther.getTransdate()) || ( this.getTransdate()!=null && castOther.getTransdate()!=null && this.getTransdate().equals(castOther.getTransdate()) ) )
 && ( (this.getMiAmount()==castOther.getMiAmount()) || ( this.getMiAmount()!=null && castOther.getMiAmount()!=null && this.getMiAmount().equals(castOther.getMiAmount()) ) )
 && ( (this.getMexpiryLife()==castOther.getMexpiryLife()) || ( this.getMexpiryLife()!=null && castOther.getMexpiryLife()!=null && this.getMexpiryLife().equals(castOther.getMexpiryLife()) ) )
 && ( (this.getExpiryTpd()==castOther.getExpiryTpd()) || ( this.getExpiryTpd()!=null && castOther.getExpiryTpd()!=null && this.getExpiryTpd().equals(castOther.getExpiryTpd()) ) )
 && ( (this.getExpiryTd()==castOther.getExpiryTd()) || ( this.getExpiryTd()!=null && castOther.getExpiryTd()!=null && this.getExpiryTd().equals(castOther.getExpiryTd()) ) )
 && ( (this.getExpiryAdd()==castOther.getExpiryAdd()) || ( this.getExpiryAdd()!=null && castOther.getExpiryAdd()!=null && this.getExpiryAdd().equals(castOther.getExpiryAdd()) ) )
 && ( (this.getExpiryAdb()==castOther.getExpiryAdb()) || ( this.getExpiryAdb()!=null && castOther.getExpiryAdb()!=null && this.getExpiryAdb().equals(castOther.getExpiryAdb()) ) )
 && ( (this.getExpiryHa()==castOther.getExpiryHa()) || ( this.getExpiryHa()!=null && castOther.getExpiryHa()!=null && this.getExpiryHa().equals(castOther.getExpiryHa()) ) )
 && ( (this.getExpiryHb()==castOther.getExpiryHb()) || ( this.getExpiryHb()!=null && castOther.getExpiryHb()!=null && this.getExpiryHb().equals(castOther.getExpiryHb()) ) )
 && ( (this.getExpiryMe()==castOther.getExpiryMe()) || ( this.getExpiryMe()!=null && castOther.getExpiryMe()!=null && this.getExpiryMe().equals(castOther.getExpiryMe()) ) )
 && ( (this.getExpiryPa()==castOther.getExpiryPa()) || ( this.getExpiryPa()!=null && castOther.getExpiryPa()!=null && this.getExpiryPa().equals(castOther.getExpiryPa()) ) )
 && ( (this.getExpiryPh()==castOther.getExpiryPh()) || ( this.getExpiryPh()!=null && castOther.getExpiryPh()!=null && this.getExpiryPh().equals(castOther.getExpiryPh()) ) )
 && ( (this.getExpiryCi()==castOther.getExpiryCi()) || ( this.getExpiryCi()!=null && castOther.getExpiryCi()!=null && this.getExpiryCi().equals(castOther.getExpiryCi()) ) )
 && ( (this.getSaMa()==castOther.getSaMa()) || ( this.getSaMa()!=null && castOther.getSaMa()!=null && this.getSaMa().equals(castOther.getSaMa()) ) )
 && ( (this.getExpiryMa()==castOther.getExpiryMa()) || ( this.getExpiryMa()!=null && castOther.getExpiryMa()!=null && this.getExpiryMa().equals(castOther.getExpiryMa()) ) )
 && ( (this.getSaMc()==castOther.getSaMc()) || ( this.getSaMc()!=null && castOther.getSaMc()!=null && this.getSaMc().equals(castOther.getSaMc()) ) )
 && ( (this.getExpiryMc()==castOther.getExpiryMc()) || ( this.getExpiryMc()!=null && castOther.getExpiryMc()!=null && this.getExpiryMc().equals(castOther.getExpiryMc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomercode() == null ? 0 : this.getCustomercode().hashCode() );
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getSaLifetpd() == null ? 0 : this.getSaLifetpd().hashCode() );
         result = 37 * result + ( getSaLife() == null ? 0 : this.getSaLife().hashCode() );
         result = 37 * result + ( getSaTpd() == null ? 0 : this.getSaTpd().hashCode() );
         result = 37 * result + ( getSaTd() == null ? 0 : this.getSaTd().hashCode() );
         result = 37 * result + ( getSaAdd() == null ? 0 : this.getSaAdd().hashCode() );
         result = 37 * result + ( getSaAdb() == null ? 0 : this.getSaAdb().hashCode() );
         result = 37 * result + ( getSaHa() == null ? 0 : this.getSaHa().hashCode() );
         result = 37 * result + ( getSaHb() == null ? 0 : this.getSaHb().hashCode() );
         result = 37 * result + ( getSaMe() == null ? 0 : this.getSaMe().hashCode() );
         result = 37 * result + ( getSaPa() == null ? 0 : this.getSaPa().hashCode() );
         result = 37 * result + ( getSaPh() == null ? 0 : this.getSaPh().hashCode() );
         result = 37 * result + ( getSaCi() == null ? 0 : this.getSaCi().hashCode() );
         result = 37 * result + ( getFlaglife() == null ? 0 : this.getFlaglife().hashCode() );
         result = 37 * result + ( getFlaglifetpd() == null ? 0 : this.getFlaglifetpd().hashCode() );
         result = 37 * result + ( getIa() == null ? 0 : this.getIa().hashCode() );
         result = 37 * result + ( getSa() == null ? 0 : this.getSa().hashCode() );
         result = 37 * result + ( getTransdate() == null ? 0 : this.getTransdate().hashCode() );
         result = 37 * result + ( getMiAmount() == null ? 0 : this.getMiAmount().hashCode() );
         result = 37 * result + ( getMexpiryLife() == null ? 0 : this.getMexpiryLife().hashCode() );
         result = 37 * result + ( getExpiryTpd() == null ? 0 : this.getExpiryTpd().hashCode() );
         result = 37 * result + ( getExpiryTd() == null ? 0 : this.getExpiryTd().hashCode() );
         result = 37 * result + ( getExpiryAdd() == null ? 0 : this.getExpiryAdd().hashCode() );
         result = 37 * result + ( getExpiryAdb() == null ? 0 : this.getExpiryAdb().hashCode() );
         result = 37 * result + ( getExpiryHa() == null ? 0 : this.getExpiryHa().hashCode() );
         result = 37 * result + ( getExpiryHb() == null ? 0 : this.getExpiryHb().hashCode() );
         result = 37 * result + ( getExpiryMe() == null ? 0 : this.getExpiryMe().hashCode() );
         result = 37 * result + ( getExpiryPa() == null ? 0 : this.getExpiryPa().hashCode() );
         result = 37 * result + ( getExpiryPh() == null ? 0 : this.getExpiryPh().hashCode() );
         result = 37 * result + ( getExpiryCi() == null ? 0 : this.getExpiryCi().hashCode() );
         result = 37 * result + ( getSaMa() == null ? 0 : this.getSaMa().hashCode() );
         result = 37 * result + ( getExpiryMa() == null ? 0 : this.getExpiryMa().hashCode() );
         result = 37 * result + ( getSaMc() == null ? 0 : this.getSaMc().hashCode() );
         result = 37 * result + ( getExpiryMc() == null ? 0 : this.getExpiryMc().hashCode() );
         return result;
   }   


}


