package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Customerballoon generated by hbm2java
 */
@Entity
@Table(name="customerballoon"
)
public class Customerballoon  implements java.io.Serializable {


     private CustomerballoonId id;

    public Customerballoon() {
    }

    public Customerballoon(CustomerballoonId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="certno", column=@Column(name="certno") ), 
        @AttributeOverride(name="policynoballoon", column=@Column(name="policynoballoon") ), 
        @AttributeOverride(name="certnobolloon", column=@Column(name="certnobolloon") ), 
        @AttributeOverride(name="loancontractno", column=@Column(name="loancontractno") ) } )
    public CustomerballoonId getId() {
        return this.id;
    }
    
    public void setId(CustomerballoonId id) {
        this.id = id;
    }




}


