package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerballoonId generated by hbm2java
 */
@Embeddable
public class CustomerballoonId  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String policynoballoon;
     private String certnobolloon;
     private String loancontractno;

    public CustomerballoonId() {
    }

    public CustomerballoonId(String policyno, String certno, String policynoballoon, String certnobolloon, String loancontractno) {
       this.policyno = policyno;
       this.certno = certno;
       this.policynoballoon = policynoballoon;
       this.certnobolloon = certnobolloon;
       this.loancontractno = loancontractno;
    }
   

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno")
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="policynoballoon")
    public String getPolicynoballoon() {
        return this.policynoballoon;
    }
    
    public void setPolicynoballoon(String policynoballoon) {
        this.policynoballoon = policynoballoon;
    }

    @Column(name="certnobolloon")
    public String getCertnobolloon() {
        return this.certnobolloon;
    }
    
    public void setCertnobolloon(String certnobolloon) {
        this.certnobolloon = certnobolloon;
    }

    @Column(name="loancontractno")
    public String getLoancontractno() {
        return this.loancontractno;
    }
    
    public void setLoancontractno(String loancontractno) {
        this.loancontractno = loancontractno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomerballoonId) ) return false;
		 CustomerballoonId castOther = ( CustomerballoonId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getPolicynoballoon()==castOther.getPolicynoballoon()) || ( this.getPolicynoballoon()!=null && castOther.getPolicynoballoon()!=null && this.getPolicynoballoon().equals(castOther.getPolicynoballoon()) ) )
 && ( (this.getCertnobolloon()==castOther.getCertnobolloon()) || ( this.getCertnobolloon()!=null && castOther.getCertnobolloon()!=null && this.getCertnobolloon().equals(castOther.getCertnobolloon()) ) )
 && ( (this.getLoancontractno()==castOther.getLoancontractno()) || ( this.getLoancontractno()!=null && castOther.getLoancontractno()!=null && this.getLoancontractno().equals(castOther.getLoancontractno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getPolicynoballoon() == null ? 0 : this.getPolicynoballoon().hashCode() );
         result = 37 * result + ( getCertnobolloon() == null ? 0 : this.getCertnobolloon().hashCode() );
         result = 37 * result + ( getLoancontractno() == null ? 0 : this.getLoancontractno().hashCode() );
         return result;
   }   


}


