package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Customerinfo generated by hbm2java
 */
@Entity
@Table(name="customerinfo"
)
public class Customerinfo  implements java.io.Serializable {


     private CustomerinfoId id;

    public Customerinfo() {
    }

    public Customerinfo(CustomerinfoId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="productname", column=@Column(name="productname") ), 
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="productcode", column=@Column(name="productcode") ), 
        @AttributeOverride(name="certificateno", column=@Column(name="certificateno") ), 
        @AttributeOverride(name="saledate", column=@Column(name="saledate") ), 
        @AttributeOverride(name="branchname", column=@Column(name="branchname") ), 
        @AttributeOverride(name="customercode", column=@Column(name="customercode") ), 
        @AttributeOverride(name="accountno", column=@Column(name="accountno") ), 
        @AttributeOverride(name="loanno", column=@Column(name="loanno") ), 
        @AttributeOverride(name="totalofloan", column=@Column(name="totalofloan") ), 
        @AttributeOverride(name="sa", column=@Column(name="sa") ), 
        @AttributeOverride(name="prem", column=@Column(name="prem") ), 
        @AttributeOverride(name="durationinsurance", column=@Column(name="durationinsurance") ), 
        @AttributeOverride(name="insurancestatus", column=@Column(name="insurancestatus") ), 
        @AttributeOverride(name="effectivedate", column=@Column(name="effectivedate") ), 
        @AttributeOverride(name="expireddate", column=@Column(name="expireddate") ), 
        @AttributeOverride(name="customerstatus", column=@Column(name="customerstatus") ), 
        @AttributeOverride(name="canceldate", column=@Column(name="canceldate") ), 
        @AttributeOverride(name="cancelreason", column=@Column(name="cancelreason") ), 
        @AttributeOverride(name="canceldescription", column=@Column(name="canceldescription") ), 
        @AttributeOverride(name="channel", column=@Column(name="channel") ), 
        @AttributeOverride(name="prefix", column=@Column(name="prefix") ), 
        @AttributeOverride(name="nameth", column=@Column(name="nameth") ), 
        @AttributeOverride(name="surnameth", column=@Column(name="surnameth") ), 
        @AttributeOverride(name="birthdate", column=@Column(name="birthdate") ), 
        @AttributeOverride(name="age", column=@Column(name="age") ), 
        @AttributeOverride(name="weight", column=@Column(name="weight") ), 
        @AttributeOverride(name="height", column=@Column(name="height") ), 
        @AttributeOverride(name="gender", column=@Column(name="gender") ), 
        @AttributeOverride(name="status", column=@Column(name="status") ), 
        @AttributeOverride(name="nationid", column=@Column(name="nationid") ), 
        @AttributeOverride(name="creditcardno", column=@Column(name="creditcardno") ), 
        @AttributeOverride(name="expiredcreditcard", column=@Column(name="expiredcreditcard") ), 
        @AttributeOverride(name="address1", column=@Column(name="address1") ), 
        @AttributeOverride(name="address2", column=@Column(name="address2") ), 
        @AttributeOverride(name="addressoffice1", column=@Column(name="addressoffice1") ), 
        @AttributeOverride(name="addressoffice2", column=@Column(name="addressoffice2") ), 
        @AttributeOverride(name="nameofbenefit1", column=@Column(name="nameofbenefit1") ), 
        @AttributeOverride(name="nameofbenefit2", column=@Column(name="nameofbenefit2") ), 
        @AttributeOverride(name="nameofbenefit3", column=@Column(name="nameofbenefit3") ), 
        @AttributeOverride(name="nameofbenefit4", column=@Column(name="nameofbenefit4") ), 
        @AttributeOverride(name="relationship1", column=@Column(name="relationship1") ), 
        @AttributeOverride(name="relationship2", column=@Column(name="relationship2") ), 
        @AttributeOverride(name="relationship3", column=@Column(name="relationship3") ), 
        @AttributeOverride(name="relationship4", column=@Column(name="relationship4") ), 
        @AttributeOverride(name="hometel", column=@Column(name="hometel") ), 
        @AttributeOverride(name="mobiletel", column=@Column(name="mobiletel") ), 
        @AttributeOverride(name="officetel", column=@Column(name="officetel") ), 
        @AttributeOverride(name="officercodesale", column=@Column(name="officercodesale") ), 
        @AttributeOverride(name="salenameth", column=@Column(name="salenameth") ), 
        @AttributeOverride(name="managercode", column=@Column(name="managercode") ), 
        @AttributeOverride(name="dateprintcert", column=@Column(name="dateprintcert") ), 
        @AttributeOverride(name="postbackdate", column=@Column(name="postbackdate") ), 
        @AttributeOverride(name="cancelletterno", column=@Column(name="cancelletterno") ), 
        @AttributeOverride(name="printcancelletterdate", column=@Column(name="printcancelletterdate") ), 
        @AttributeOverride(name="partnercode", column=@Column(name="partnercode") ), 
        @AttributeOverride(name="partnername", column=@Column(name="partnername") ), 
        @AttributeOverride(name="databasesource", column=@Column(name="databasesource") ), 
        @AttributeOverride(name="refname", column=@Column(name="refname") ), 
        @AttributeOverride(name="refnationid", column=@Column(name="refnationid") ), 
        @AttributeOverride(name="refcreditcardno", column=@Column(name="refcreditcardno") ), 
        @AttributeOverride(name="facility", column=@Column(name="facility") ), 
        @AttributeOverride(name="uwdescription", column=@Column(name="uwdescription") ), 
        @AttributeOverride(name="uwstatus", column=@Column(name="uwstatus") ), 
        @AttributeOverride(name="tmksaledate", column=@Column(name="tmksaledate") ), 
        @AttributeOverride(name="coverage", column=@Column(name="coverage") ), 
        @AttributeOverride(name="paidtodate", column=@Column(name="paidtodate") ), 
        @AttributeOverride(name="extrarate", column=@Column(name="extrarate") ), 
        @AttributeOverride(name="voicetag", column=@Column(name="voicetag") ), 
        @AttributeOverride(name="deathdate", column=@Column(name="deathdate") ), 
        @AttributeOverride(name="customerloanapprovedate", column=@Column(name="customerloanapprovedate") ), 
        @AttributeOverride(name="lob", column=@Column(name="lob") ), 
        @AttributeOverride(name="canceltransactiondate", column=@Column(name="canceltransactiondate") ), 
        @AttributeOverride(name="oldaccountno", column=@Column(name="oldaccountno") ), 
        @AttributeOverride(name="customeroccupationtext", column=@Column(name="customeroccupationtext") ), 
        @AttributeOverride(name="loaninstallment1stdue", column=@Column(name="loaninstallment1stdue") ), 
        @AttributeOverride(name="customercontactofficepay", column=@Column(name="customercontactofficepay") ), 
        @AttributeOverride(name="percentofbenefitciary1", column=@Column(name="percentofbenefitciary1") ), 
        @AttributeOverride(name="percentofbenefitciary2", column=@Column(name="percentofbenefitciary2") ), 
        @AttributeOverride(name="percentofbenefitciary3", column=@Column(name="percentofbenefitciary3") ), 
        @AttributeOverride(name="percentofbenefitciary4", column=@Column(name="percentofbenefitciary4") ), 
        @AttributeOverride(name="downplaneffectivedate", column=@Column(name="downplaneffectivedate") ), 
        @AttributeOverride(name="dateSosover", column=@Column(name="date_sosover") ), 
        @AttributeOverride(name="customerduration", column=@Column(name="customerduration") ), 
        @AttributeOverride(name="med", column=@Column(name="med") ), 
        @AttributeOverride(name="customernation", column=@Column(name="customernation") ), 
        @AttributeOverride(name="endorsedate", column=@Column(name="endorsedate") ), 
        @AttributeOverride(name="informdate1", column=@Column(name="informdate1") ), 
        @AttributeOverride(name="paydate1", column=@Column(name="paydate1") ), 
        @AttributeOverride(name="amount1", column=@Column(name="amount1") ), 
        @AttributeOverride(name="informdate2", column=@Column(name="informdate2") ), 
        @AttributeOverride(name="paydate2", column=@Column(name="paydate2") ), 
        @AttributeOverride(name="amount2", column=@Column(name="amount2") ), 
        @AttributeOverride(name="deaddate", column=@Column(name="deaddate") ) } )
    public CustomerinfoId getId() {
        return this.id;
    }
    
    public void setId(CustomerinfoId id) {
        this.id = id;
    }




}


