package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustomerinfoId generated by hbm2java
 */
@Embeddable
public class CustomerinfoId  implements java.io.Serializable {


     private String productname;
     private String policyno;
     private String productcode;
     private String certificateno;
     private String saledate;
     private String branchname;
     private String customercode;
     private String accountno;
     private String loanno;
     private String totalofloan;
     private String sa;
     private String prem;
     private String durationinsurance;
     private String insurancestatus;
     private String effectivedate;
     private String expireddate;
     private String customerstatus;
     private String canceldate;
     private String cancelreason;
     private String canceldescription;
     private String channel;
     private String prefix;
     private String nameth;
     private String surnameth;
     private String birthdate;
     private String age;
     private String weight;
     private String height;
     private String gender;
     private String status;
     private String nationid;
     private String creditcardno;
     private String expiredcreditcard;
     private String address1;
     private String address2;
     private String addressoffice1;
     private String addressoffice2;
     private String nameofbenefit1;
     private String nameofbenefit2;
     private String nameofbenefit3;
     private String nameofbenefit4;
     private String relationship1;
     private String relationship2;
     private String relationship3;
     private String relationship4;
     private String hometel;
     private String mobiletel;
     private String officetel;
     private String officercodesale;
     private String salenameth;
     private String managercode;
     private String dateprintcert;
     private String postbackdate;
     private String cancelletterno;
     private String printcancelletterdate;
     private String partnercode;
     private String partnername;
     private String databasesource;
     private String refname;
     private String refnationid;
     private String refcreditcardno;
     private String facility;
     private String uwdescription;
     private String uwstatus;
     private String tmksaledate;
     private String coverage;
     private String paidtodate;
     private String extrarate;
     private String voicetag;
     private String deathdate;
     private String customerloanapprovedate;
     private String lob;
     private String canceltransactiondate;
     private String oldaccountno;
     private String customeroccupationtext;
     private String loaninstallment1stdue;
     private String customercontactofficepay;
     private String percentofbenefitciary1;
     private String percentofbenefitciary2;
     private String percentofbenefitciary3;
     private String percentofbenefitciary4;
     private String downplaneffectivedate;
     private String dateSosover;
     private String customerduration;
     private String med;
     private String customernation;
     private String endorsedate;
     private String informdate1;
     private String paydate1;
     private String amount1;
     private String informdate2;
     private String paydate2;
     private String amount2;
     private String deaddate;

    public CustomerinfoId() {
    }

    public CustomerinfoId(String productname, String policyno, String productcode, String certificateno, String saledate, String branchname, String customercode, String accountno, String loanno, String totalofloan, String sa, String prem, String durationinsurance, String insurancestatus, String effectivedate, String expireddate, String customerstatus, String canceldate, String cancelreason, String canceldescription, String channel, String prefix, String nameth, String surnameth, String birthdate, String age, String weight, String height, String gender, String status, String nationid, String creditcardno, String expiredcreditcard, String address1, String address2, String addressoffice1, String addressoffice2, String nameofbenefit1, String nameofbenefit2, String nameofbenefit3, String nameofbenefit4, String relationship1, String relationship2, String relationship3, String relationship4, String hometel, String mobiletel, String officetel, String officercodesale, String salenameth, String managercode, String dateprintcert, String postbackdate, String cancelletterno, String printcancelletterdate, String partnercode, String partnername, String databasesource, String refname, String refnationid, String refcreditcardno, String facility, String uwdescription, String uwstatus, String tmksaledate, String coverage, String paidtodate, String extrarate, String voicetag, String deathdate, String customerloanapprovedate, String lob, String canceltransactiondate, String oldaccountno, String customeroccupationtext, String loaninstallment1stdue, String customercontactofficepay, String percentofbenefitciary1, String percentofbenefitciary2, String percentofbenefitciary3, String percentofbenefitciary4, String downplaneffectivedate, String dateSosover, String customerduration, String med, String customernation, String endorsedate, String informdate1, String paydate1, String amount1, String informdate2, String paydate2, String amount2, String deaddate) {
       this.productname = productname;
       this.policyno = policyno;
       this.productcode = productcode;
       this.certificateno = certificateno;
       this.saledate = saledate;
       this.branchname = branchname;
       this.customercode = customercode;
       this.accountno = accountno;
       this.loanno = loanno;
       this.totalofloan = totalofloan;
       this.sa = sa;
       this.prem = prem;
       this.durationinsurance = durationinsurance;
       this.insurancestatus = insurancestatus;
       this.effectivedate = effectivedate;
       this.expireddate = expireddate;
       this.customerstatus = customerstatus;
       this.canceldate = canceldate;
       this.cancelreason = cancelreason;
       this.canceldescription = canceldescription;
       this.channel = channel;
       this.prefix = prefix;
       this.nameth = nameth;
       this.surnameth = surnameth;
       this.birthdate = birthdate;
       this.age = age;
       this.weight = weight;
       this.height = height;
       this.gender = gender;
       this.status = status;
       this.nationid = nationid;
       this.creditcardno = creditcardno;
       this.expiredcreditcard = expiredcreditcard;
       this.address1 = address1;
       this.address2 = address2;
       this.addressoffice1 = addressoffice1;
       this.addressoffice2 = addressoffice2;
       this.nameofbenefit1 = nameofbenefit1;
       this.nameofbenefit2 = nameofbenefit2;
       this.nameofbenefit3 = nameofbenefit3;
       this.nameofbenefit4 = nameofbenefit4;
       this.relationship1 = relationship1;
       this.relationship2 = relationship2;
       this.relationship3 = relationship3;
       this.relationship4 = relationship4;
       this.hometel = hometel;
       this.mobiletel = mobiletel;
       this.officetel = officetel;
       this.officercodesale = officercodesale;
       this.salenameth = salenameth;
       this.managercode = managercode;
       this.dateprintcert = dateprintcert;
       this.postbackdate = postbackdate;
       this.cancelletterno = cancelletterno;
       this.printcancelletterdate = printcancelletterdate;
       this.partnercode = partnercode;
       this.partnername = partnername;
       this.databasesource = databasesource;
       this.refname = refname;
       this.refnationid = refnationid;
       this.refcreditcardno = refcreditcardno;
       this.facility = facility;
       this.uwdescription = uwdescription;
       this.uwstatus = uwstatus;
       this.tmksaledate = tmksaledate;
       this.coverage = coverage;
       this.paidtodate = paidtodate;
       this.extrarate = extrarate;
       this.voicetag = voicetag;
       this.deathdate = deathdate;
       this.customerloanapprovedate = customerloanapprovedate;
       this.lob = lob;
       this.canceltransactiondate = canceltransactiondate;
       this.oldaccountno = oldaccountno;
       this.customeroccupationtext = customeroccupationtext;
       this.loaninstallment1stdue = loaninstallment1stdue;
       this.customercontactofficepay = customercontactofficepay;
       this.percentofbenefitciary1 = percentofbenefitciary1;
       this.percentofbenefitciary2 = percentofbenefitciary2;
       this.percentofbenefitciary3 = percentofbenefitciary3;
       this.percentofbenefitciary4 = percentofbenefitciary4;
       this.downplaneffectivedate = downplaneffectivedate;
       this.dateSosover = dateSosover;
       this.customerduration = customerduration;
       this.med = med;
       this.customernation = customernation;
       this.endorsedate = endorsedate;
       this.informdate1 = informdate1;
       this.paydate1 = paydate1;
       this.amount1 = amount1;
       this.informdate2 = informdate2;
       this.paydate2 = paydate2;
       this.amount2 = amount2;
       this.deaddate = deaddate;
    }
   

    @Column(name="productname")
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="productcode")
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    @Column(name="certificateno")
    public String getCertificateno() {
        return this.certificateno;
    }
    
    public void setCertificateno(String certificateno) {
        this.certificateno = certificateno;
    }

    @Column(name="saledate")
    public String getSaledate() {
        return this.saledate;
    }
    
    public void setSaledate(String saledate) {
        this.saledate = saledate;
    }

    @Column(name="branchname")
    public String getBranchname() {
        return this.branchname;
    }
    
    public void setBranchname(String branchname) {
        this.branchname = branchname;
    }

    @Column(name="customercode")
    public String getCustomercode() {
        return this.customercode;
    }
    
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    @Column(name="accountno")
    public String getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    @Column(name="loanno")
    public String getLoanno() {
        return this.loanno;
    }
    
    public void setLoanno(String loanno) {
        this.loanno = loanno;
    }

    @Column(name="totalofloan")
    public String getTotalofloan() {
        return this.totalofloan;
    }
    
    public void setTotalofloan(String totalofloan) {
        this.totalofloan = totalofloan;
    }

    @Column(name="sa")
    public String getSa() {
        return this.sa;
    }
    
    public void setSa(String sa) {
        this.sa = sa;
    }

    @Column(name="prem")
    public String getPrem() {
        return this.prem;
    }
    
    public void setPrem(String prem) {
        this.prem = prem;
    }

    @Column(name="durationinsurance")
    public String getDurationinsurance() {
        return this.durationinsurance;
    }
    
    public void setDurationinsurance(String durationinsurance) {
        this.durationinsurance = durationinsurance;
    }

    @Column(name="insurancestatus")
    public String getInsurancestatus() {
        return this.insurancestatus;
    }
    
    public void setInsurancestatus(String insurancestatus) {
        this.insurancestatus = insurancestatus;
    }

    @Column(name="effectivedate")
    public String getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(String effectivedate) {
        this.effectivedate = effectivedate;
    }

    @Column(name="expireddate")
    public String getExpireddate() {
        return this.expireddate;
    }
    
    public void setExpireddate(String expireddate) {
        this.expireddate = expireddate;
    }

    @Column(name="customerstatus")
    public String getCustomerstatus() {
        return this.customerstatus;
    }
    
    public void setCustomerstatus(String customerstatus) {
        this.customerstatus = customerstatus;
    }

    @Column(name="canceldate")
    public String getCanceldate() {
        return this.canceldate;
    }
    
    public void setCanceldate(String canceldate) {
        this.canceldate = canceldate;
    }

    @Column(name="cancelreason")
    public String getCancelreason() {
        return this.cancelreason;
    }
    
    public void setCancelreason(String cancelreason) {
        this.cancelreason = cancelreason;
    }

    @Column(name="canceldescription")
    public String getCanceldescription() {
        return this.canceldescription;
    }
    
    public void setCanceldescription(String canceldescription) {
        this.canceldescription = canceldescription;
    }

    @Column(name="channel")
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }

    @Column(name="prefix")
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    @Column(name="nameth")
    public String getNameth() {
        return this.nameth;
    }
    
    public void setNameth(String nameth) {
        this.nameth = nameth;
    }

    @Column(name="surnameth")
    public String getSurnameth() {
        return this.surnameth;
    }
    
    public void setSurnameth(String surnameth) {
        this.surnameth = surnameth;
    }

    @Column(name="birthdate")
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    @Column(name="age")
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }

    @Column(name="weight")
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }

    @Column(name="height")
    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }

    @Column(name="gender")
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name="nationid")
    public String getNationid() {
        return this.nationid;
    }
    
    public void setNationid(String nationid) {
        this.nationid = nationid;
    }

    @Column(name="creditcardno")
    public String getCreditcardno() {
        return this.creditcardno;
    }
    
    public void setCreditcardno(String creditcardno) {
        this.creditcardno = creditcardno;
    }

    @Column(name="expiredcreditcard")
    public String getExpiredcreditcard() {
        return this.expiredcreditcard;
    }
    
    public void setExpiredcreditcard(String expiredcreditcard) {
        this.expiredcreditcard = expiredcreditcard;
    }

    @Column(name="address1")
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    @Column(name="address2")
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    @Column(name="addressoffice1")
    public String getAddressoffice1() {
        return this.addressoffice1;
    }
    
    public void setAddressoffice1(String addressoffice1) {
        this.addressoffice1 = addressoffice1;
    }

    @Column(name="addressoffice2")
    public String getAddressoffice2() {
        return this.addressoffice2;
    }
    
    public void setAddressoffice2(String addressoffice2) {
        this.addressoffice2 = addressoffice2;
    }

    @Column(name="nameofbenefit1")
    public String getNameofbenefit1() {
        return this.nameofbenefit1;
    }
    
    public void setNameofbenefit1(String nameofbenefit1) {
        this.nameofbenefit1 = nameofbenefit1;
    }

    @Column(name="nameofbenefit2")
    public String getNameofbenefit2() {
        return this.nameofbenefit2;
    }
    
    public void setNameofbenefit2(String nameofbenefit2) {
        this.nameofbenefit2 = nameofbenefit2;
    }

    @Column(name="nameofbenefit3")
    public String getNameofbenefit3() {
        return this.nameofbenefit3;
    }
    
    public void setNameofbenefit3(String nameofbenefit3) {
        this.nameofbenefit3 = nameofbenefit3;
    }

    @Column(name="nameofbenefit4")
    public String getNameofbenefit4() {
        return this.nameofbenefit4;
    }
    
    public void setNameofbenefit4(String nameofbenefit4) {
        this.nameofbenefit4 = nameofbenefit4;
    }

    @Column(name="relationship1")
    public String getRelationship1() {
        return this.relationship1;
    }
    
    public void setRelationship1(String relationship1) {
        this.relationship1 = relationship1;
    }

    @Column(name="relationship2")
    public String getRelationship2() {
        return this.relationship2;
    }
    
    public void setRelationship2(String relationship2) {
        this.relationship2 = relationship2;
    }

    @Column(name="relationship3")
    public String getRelationship3() {
        return this.relationship3;
    }
    
    public void setRelationship3(String relationship3) {
        this.relationship3 = relationship3;
    }

    @Column(name="relationship4")
    public String getRelationship4() {
        return this.relationship4;
    }
    
    public void setRelationship4(String relationship4) {
        this.relationship4 = relationship4;
    }

    @Column(name="hometel")
    public String getHometel() {
        return this.hometel;
    }
    
    public void setHometel(String hometel) {
        this.hometel = hometel;
    }

    @Column(name="mobiletel")
    public String getMobiletel() {
        return this.mobiletel;
    }
    
    public void setMobiletel(String mobiletel) {
        this.mobiletel = mobiletel;
    }

    @Column(name="officetel")
    public String getOfficetel() {
        return this.officetel;
    }
    
    public void setOfficetel(String officetel) {
        this.officetel = officetel;
    }

    @Column(name="officercodesale")
    public String getOfficercodesale() {
        return this.officercodesale;
    }
    
    public void setOfficercodesale(String officercodesale) {
        this.officercodesale = officercodesale;
    }

    @Column(name="salenameth")
    public String getSalenameth() {
        return this.salenameth;
    }
    
    public void setSalenameth(String salenameth) {
        this.salenameth = salenameth;
    }

    @Column(name="managercode")
    public String getManagercode() {
        return this.managercode;
    }
    
    public void setManagercode(String managercode) {
        this.managercode = managercode;
    }

    @Column(name="dateprintcert")
    public String getDateprintcert() {
        return this.dateprintcert;
    }
    
    public void setDateprintcert(String dateprintcert) {
        this.dateprintcert = dateprintcert;
    }

    @Column(name="postbackdate")
    public String getPostbackdate() {
        return this.postbackdate;
    }
    
    public void setPostbackdate(String postbackdate) {
        this.postbackdate = postbackdate;
    }

    @Column(name="cancelletterno")
    public String getCancelletterno() {
        return this.cancelletterno;
    }
    
    public void setCancelletterno(String cancelletterno) {
        this.cancelletterno = cancelletterno;
    }

    @Column(name="printcancelletterdate")
    public String getPrintcancelletterdate() {
        return this.printcancelletterdate;
    }
    
    public void setPrintcancelletterdate(String printcancelletterdate) {
        this.printcancelletterdate = printcancelletterdate;
    }

    @Column(name="partnercode")
    public String getPartnercode() {
        return this.partnercode;
    }
    
    public void setPartnercode(String partnercode) {
        this.partnercode = partnercode;
    }

    @Column(name="partnername")
    public String getPartnername() {
        return this.partnername;
    }
    
    public void setPartnername(String partnername) {
        this.partnername = partnername;
    }

    @Column(name="databasesource")
    public String getDatabasesource() {
        return this.databasesource;
    }
    
    public void setDatabasesource(String databasesource) {
        this.databasesource = databasesource;
    }

    @Column(name="refname")
    public String getRefname() {
        return this.refname;
    }
    
    public void setRefname(String refname) {
        this.refname = refname;
    }

    @Column(name="refnationid")
    public String getRefnationid() {
        return this.refnationid;
    }
    
    public void setRefnationid(String refnationid) {
        this.refnationid = refnationid;
    }

    @Column(name="refcreditcardno")
    public String getRefcreditcardno() {
        return this.refcreditcardno;
    }
    
    public void setRefcreditcardno(String refcreditcardno) {
        this.refcreditcardno = refcreditcardno;
    }

    @Column(name="facility")
    public String getFacility() {
        return this.facility;
    }
    
    public void setFacility(String facility) {
        this.facility = facility;
    }

    @Column(name="uwdescription")
    public String getUwdescription() {
        return this.uwdescription;
    }
    
    public void setUwdescription(String uwdescription) {
        this.uwdescription = uwdescription;
    }

    @Column(name="uwstatus")
    public String getUwstatus() {
        return this.uwstatus;
    }
    
    public void setUwstatus(String uwstatus) {
        this.uwstatus = uwstatus;
    }

    @Column(name="tmksaledate")
    public String getTmksaledate() {
        return this.tmksaledate;
    }
    
    public void setTmksaledate(String tmksaledate) {
        this.tmksaledate = tmksaledate;
    }

    @Column(name="coverage")
    public String getCoverage() {
        return this.coverage;
    }
    
    public void setCoverage(String coverage) {
        this.coverage = coverage;
    }

    @Column(name="paidtodate")
    public String getPaidtodate() {
        return this.paidtodate;
    }
    
    public void setPaidtodate(String paidtodate) {
        this.paidtodate = paidtodate;
    }

    @Column(name="extrarate")
    public String getExtrarate() {
        return this.extrarate;
    }
    
    public void setExtrarate(String extrarate) {
        this.extrarate = extrarate;
    }

    @Column(name="voicetag")
    public String getVoicetag() {
        return this.voicetag;
    }
    
    public void setVoicetag(String voicetag) {
        this.voicetag = voicetag;
    }

    @Column(name="deathdate")
    public String getDeathdate() {
        return this.deathdate;
    }
    
    public void setDeathdate(String deathdate) {
        this.deathdate = deathdate;
    }

    @Column(name="customerloanapprovedate")
    public String getCustomerloanapprovedate() {
        return this.customerloanapprovedate;
    }
    
    public void setCustomerloanapprovedate(String customerloanapprovedate) {
        this.customerloanapprovedate = customerloanapprovedate;
    }

    @Column(name="lob")
    public String getLob() {
        return this.lob;
    }
    
    public void setLob(String lob) {
        this.lob = lob;
    }

    @Column(name="canceltransactiondate")
    public String getCanceltransactiondate() {
        return this.canceltransactiondate;
    }
    
    public void setCanceltransactiondate(String canceltransactiondate) {
        this.canceltransactiondate = canceltransactiondate;
    }

    @Column(name="oldaccountno")
    public String getOldaccountno() {
        return this.oldaccountno;
    }
    
    public void setOldaccountno(String oldaccountno) {
        this.oldaccountno = oldaccountno;
    }

    @Column(name="customeroccupationtext")
    public String getCustomeroccupationtext() {
        return this.customeroccupationtext;
    }
    
    public void setCustomeroccupationtext(String customeroccupationtext) {
        this.customeroccupationtext = customeroccupationtext;
    }

    @Column(name="loaninstallment1stdue")
    public String getLoaninstallment1stdue() {
        return this.loaninstallment1stdue;
    }
    
    public void setLoaninstallment1stdue(String loaninstallment1stdue) {
        this.loaninstallment1stdue = loaninstallment1stdue;
    }

    @Column(name="customercontactofficepay")
    public String getCustomercontactofficepay() {
        return this.customercontactofficepay;
    }
    
    public void setCustomercontactofficepay(String customercontactofficepay) {
        this.customercontactofficepay = customercontactofficepay;
    }

    @Column(name="percentofbenefitciary1")
    public String getPercentofbenefitciary1() {
        return this.percentofbenefitciary1;
    }
    
    public void setPercentofbenefitciary1(String percentofbenefitciary1) {
        this.percentofbenefitciary1 = percentofbenefitciary1;
    }

    @Column(name="percentofbenefitciary2")
    public String getPercentofbenefitciary2() {
        return this.percentofbenefitciary2;
    }
    
    public void setPercentofbenefitciary2(String percentofbenefitciary2) {
        this.percentofbenefitciary2 = percentofbenefitciary2;
    }

    @Column(name="percentofbenefitciary3")
    public String getPercentofbenefitciary3() {
        return this.percentofbenefitciary3;
    }
    
    public void setPercentofbenefitciary3(String percentofbenefitciary3) {
        this.percentofbenefitciary3 = percentofbenefitciary3;
    }

    @Column(name="percentofbenefitciary4")
    public String getPercentofbenefitciary4() {
        return this.percentofbenefitciary4;
    }
    
    public void setPercentofbenefitciary4(String percentofbenefitciary4) {
        this.percentofbenefitciary4 = percentofbenefitciary4;
    }

    @Column(name="downplaneffectivedate")
    public String getDownplaneffectivedate() {
        return this.downplaneffectivedate;
    }
    
    public void setDownplaneffectivedate(String downplaneffectivedate) {
        this.downplaneffectivedate = downplaneffectivedate;
    }

    @Column(name="date_sosover")
    public String getDateSosover() {
        return this.dateSosover;
    }
    
    public void setDateSosover(String dateSosover) {
        this.dateSosover = dateSosover;
    }

    @Column(name="customerduration")
    public String getCustomerduration() {
        return this.customerduration;
    }
    
    public void setCustomerduration(String customerduration) {
        this.customerduration = customerduration;
    }

    @Column(name="med")
    public String getMed() {
        return this.med;
    }
    
    public void setMed(String med) {
        this.med = med;
    }

    @Column(name="customernation")
    public String getCustomernation() {
        return this.customernation;
    }
    
    public void setCustomernation(String customernation) {
        this.customernation = customernation;
    }

    @Column(name="endorsedate")
    public String getEndorsedate() {
        return this.endorsedate;
    }
    
    public void setEndorsedate(String endorsedate) {
        this.endorsedate = endorsedate;
    }

    @Column(name="informdate1")
    public String getInformdate1() {
        return this.informdate1;
    }
    
    public void setInformdate1(String informdate1) {
        this.informdate1 = informdate1;
    }

    @Column(name="paydate1")
    public String getPaydate1() {
        return this.paydate1;
    }
    
    public void setPaydate1(String paydate1) {
        this.paydate1 = paydate1;
    }

    @Column(name="amount1")
    public String getAmount1() {
        return this.amount1;
    }
    
    public void setAmount1(String amount1) {
        this.amount1 = amount1;
    }

    @Column(name="informdate2")
    public String getInformdate2() {
        return this.informdate2;
    }
    
    public void setInformdate2(String informdate2) {
        this.informdate2 = informdate2;
    }

    @Column(name="paydate2")
    public String getPaydate2() {
        return this.paydate2;
    }
    
    public void setPaydate2(String paydate2) {
        this.paydate2 = paydate2;
    }

    @Column(name="amount2")
    public String getAmount2() {
        return this.amount2;
    }
    
    public void setAmount2(String amount2) {
        this.amount2 = amount2;
    }

    @Column(name="deaddate")
    public String getDeaddate() {
        return this.deaddate;
    }
    
    public void setDeaddate(String deaddate) {
        this.deaddate = deaddate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomerinfoId) ) return false;
		 CustomerinfoId castOther = ( CustomerinfoId ) other; 
         
		 return ( (this.getProductname()==castOther.getProductname()) || ( this.getProductname()!=null && castOther.getProductname()!=null && this.getProductname().equals(castOther.getProductname()) ) )
 && ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getProductcode()==castOther.getProductcode()) || ( this.getProductcode()!=null && castOther.getProductcode()!=null && this.getProductcode().equals(castOther.getProductcode()) ) )
 && ( (this.getCertificateno()==castOther.getCertificateno()) || ( this.getCertificateno()!=null && castOther.getCertificateno()!=null && this.getCertificateno().equals(castOther.getCertificateno()) ) )
 && ( (this.getSaledate()==castOther.getSaledate()) || ( this.getSaledate()!=null && castOther.getSaledate()!=null && this.getSaledate().equals(castOther.getSaledate()) ) )
 && ( (this.getBranchname()==castOther.getBranchname()) || ( this.getBranchname()!=null && castOther.getBranchname()!=null && this.getBranchname().equals(castOther.getBranchname()) ) )
 && ( (this.getCustomercode()==castOther.getCustomercode()) || ( this.getCustomercode()!=null && castOther.getCustomercode()!=null && this.getCustomercode().equals(castOther.getCustomercode()) ) )
 && ( (this.getAccountno()==castOther.getAccountno()) || ( this.getAccountno()!=null && castOther.getAccountno()!=null && this.getAccountno().equals(castOther.getAccountno()) ) )
 && ( (this.getLoanno()==castOther.getLoanno()) || ( this.getLoanno()!=null && castOther.getLoanno()!=null && this.getLoanno().equals(castOther.getLoanno()) ) )
 && ( (this.getTotalofloan()==castOther.getTotalofloan()) || ( this.getTotalofloan()!=null && castOther.getTotalofloan()!=null && this.getTotalofloan().equals(castOther.getTotalofloan()) ) )
 && ( (this.getSa()==castOther.getSa()) || ( this.getSa()!=null && castOther.getSa()!=null && this.getSa().equals(castOther.getSa()) ) )
 && ( (this.getPrem()==castOther.getPrem()) || ( this.getPrem()!=null && castOther.getPrem()!=null && this.getPrem().equals(castOther.getPrem()) ) )
 && ( (this.getDurationinsurance()==castOther.getDurationinsurance()) || ( this.getDurationinsurance()!=null && castOther.getDurationinsurance()!=null && this.getDurationinsurance().equals(castOther.getDurationinsurance()) ) )
 && ( (this.getInsurancestatus()==castOther.getInsurancestatus()) || ( this.getInsurancestatus()!=null && castOther.getInsurancestatus()!=null && this.getInsurancestatus().equals(castOther.getInsurancestatus()) ) )
 && ( (this.getEffectivedate()==castOther.getEffectivedate()) || ( this.getEffectivedate()!=null && castOther.getEffectivedate()!=null && this.getEffectivedate().equals(castOther.getEffectivedate()) ) )
 && ( (this.getExpireddate()==castOther.getExpireddate()) || ( this.getExpireddate()!=null && castOther.getExpireddate()!=null && this.getExpireddate().equals(castOther.getExpireddate()) ) )
 && ( (this.getCustomerstatus()==castOther.getCustomerstatus()) || ( this.getCustomerstatus()!=null && castOther.getCustomerstatus()!=null && this.getCustomerstatus().equals(castOther.getCustomerstatus()) ) )
 && ( (this.getCanceldate()==castOther.getCanceldate()) || ( this.getCanceldate()!=null && castOther.getCanceldate()!=null && this.getCanceldate().equals(castOther.getCanceldate()) ) )
 && ( (this.getCancelreason()==castOther.getCancelreason()) || ( this.getCancelreason()!=null && castOther.getCancelreason()!=null && this.getCancelreason().equals(castOther.getCancelreason()) ) )
 && ( (this.getCanceldescription()==castOther.getCanceldescription()) || ( this.getCanceldescription()!=null && castOther.getCanceldescription()!=null && this.getCanceldescription().equals(castOther.getCanceldescription()) ) )
 && ( (this.getChannel()==castOther.getChannel()) || ( this.getChannel()!=null && castOther.getChannel()!=null && this.getChannel().equals(castOther.getChannel()) ) )
 && ( (this.getPrefix()==castOther.getPrefix()) || ( this.getPrefix()!=null && castOther.getPrefix()!=null && this.getPrefix().equals(castOther.getPrefix()) ) )
 && ( (this.getNameth()==castOther.getNameth()) || ( this.getNameth()!=null && castOther.getNameth()!=null && this.getNameth().equals(castOther.getNameth()) ) )
 && ( (this.getSurnameth()==castOther.getSurnameth()) || ( this.getSurnameth()!=null && castOther.getSurnameth()!=null && this.getSurnameth().equals(castOther.getSurnameth()) ) )
 && ( (this.getBirthdate()==castOther.getBirthdate()) || ( this.getBirthdate()!=null && castOther.getBirthdate()!=null && this.getBirthdate().equals(castOther.getBirthdate()) ) )
 && ( (this.getAge()==castOther.getAge()) || ( this.getAge()!=null && castOther.getAge()!=null && this.getAge().equals(castOther.getAge()) ) )
 && ( (this.getWeight()==castOther.getWeight()) || ( this.getWeight()!=null && castOther.getWeight()!=null && this.getWeight().equals(castOther.getWeight()) ) )
 && ( (this.getHeight()==castOther.getHeight()) || ( this.getHeight()!=null && castOther.getHeight()!=null && this.getHeight().equals(castOther.getHeight()) ) )
 && ( (this.getGender()==castOther.getGender()) || ( this.getGender()!=null && castOther.getGender()!=null && this.getGender().equals(castOther.getGender()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getNationid()==castOther.getNationid()) || ( this.getNationid()!=null && castOther.getNationid()!=null && this.getNationid().equals(castOther.getNationid()) ) )
 && ( (this.getCreditcardno()==castOther.getCreditcardno()) || ( this.getCreditcardno()!=null && castOther.getCreditcardno()!=null && this.getCreditcardno().equals(castOther.getCreditcardno()) ) )
 && ( (this.getExpiredcreditcard()==castOther.getExpiredcreditcard()) || ( this.getExpiredcreditcard()!=null && castOther.getExpiredcreditcard()!=null && this.getExpiredcreditcard().equals(castOther.getExpiredcreditcard()) ) )
 && ( (this.getAddress1()==castOther.getAddress1()) || ( this.getAddress1()!=null && castOther.getAddress1()!=null && this.getAddress1().equals(castOther.getAddress1()) ) )
 && ( (this.getAddress2()==castOther.getAddress2()) || ( this.getAddress2()!=null && castOther.getAddress2()!=null && this.getAddress2().equals(castOther.getAddress2()) ) )
 && ( (this.getAddressoffice1()==castOther.getAddressoffice1()) || ( this.getAddressoffice1()!=null && castOther.getAddressoffice1()!=null && this.getAddressoffice1().equals(castOther.getAddressoffice1()) ) )
 && ( (this.getAddressoffice2()==castOther.getAddressoffice2()) || ( this.getAddressoffice2()!=null && castOther.getAddressoffice2()!=null && this.getAddressoffice2().equals(castOther.getAddressoffice2()) ) )
 && ( (this.getNameofbenefit1()==castOther.getNameofbenefit1()) || ( this.getNameofbenefit1()!=null && castOther.getNameofbenefit1()!=null && this.getNameofbenefit1().equals(castOther.getNameofbenefit1()) ) )
 && ( (this.getNameofbenefit2()==castOther.getNameofbenefit2()) || ( this.getNameofbenefit2()!=null && castOther.getNameofbenefit2()!=null && this.getNameofbenefit2().equals(castOther.getNameofbenefit2()) ) )
 && ( (this.getNameofbenefit3()==castOther.getNameofbenefit3()) || ( this.getNameofbenefit3()!=null && castOther.getNameofbenefit3()!=null && this.getNameofbenefit3().equals(castOther.getNameofbenefit3()) ) )
 && ( (this.getNameofbenefit4()==castOther.getNameofbenefit4()) || ( this.getNameofbenefit4()!=null && castOther.getNameofbenefit4()!=null && this.getNameofbenefit4().equals(castOther.getNameofbenefit4()) ) )
 && ( (this.getRelationship1()==castOther.getRelationship1()) || ( this.getRelationship1()!=null && castOther.getRelationship1()!=null && this.getRelationship1().equals(castOther.getRelationship1()) ) )
 && ( (this.getRelationship2()==castOther.getRelationship2()) || ( this.getRelationship2()!=null && castOther.getRelationship2()!=null && this.getRelationship2().equals(castOther.getRelationship2()) ) )
 && ( (this.getRelationship3()==castOther.getRelationship3()) || ( this.getRelationship3()!=null && castOther.getRelationship3()!=null && this.getRelationship3().equals(castOther.getRelationship3()) ) )
 && ( (this.getRelationship4()==castOther.getRelationship4()) || ( this.getRelationship4()!=null && castOther.getRelationship4()!=null && this.getRelationship4().equals(castOther.getRelationship4()) ) )
 && ( (this.getHometel()==castOther.getHometel()) || ( this.getHometel()!=null && castOther.getHometel()!=null && this.getHometel().equals(castOther.getHometel()) ) )
 && ( (this.getMobiletel()==castOther.getMobiletel()) || ( this.getMobiletel()!=null && castOther.getMobiletel()!=null && this.getMobiletel().equals(castOther.getMobiletel()) ) )
 && ( (this.getOfficetel()==castOther.getOfficetel()) || ( this.getOfficetel()!=null && castOther.getOfficetel()!=null && this.getOfficetel().equals(castOther.getOfficetel()) ) )
 && ( (this.getOfficercodesale()==castOther.getOfficercodesale()) || ( this.getOfficercodesale()!=null && castOther.getOfficercodesale()!=null && this.getOfficercodesale().equals(castOther.getOfficercodesale()) ) )
 && ( (this.getSalenameth()==castOther.getSalenameth()) || ( this.getSalenameth()!=null && castOther.getSalenameth()!=null && this.getSalenameth().equals(castOther.getSalenameth()) ) )
 && ( (this.getManagercode()==castOther.getManagercode()) || ( this.getManagercode()!=null && castOther.getManagercode()!=null && this.getManagercode().equals(castOther.getManagercode()) ) )
 && ( (this.getDateprintcert()==castOther.getDateprintcert()) || ( this.getDateprintcert()!=null && castOther.getDateprintcert()!=null && this.getDateprintcert().equals(castOther.getDateprintcert()) ) )
 && ( (this.getPostbackdate()==castOther.getPostbackdate()) || ( this.getPostbackdate()!=null && castOther.getPostbackdate()!=null && this.getPostbackdate().equals(castOther.getPostbackdate()) ) )
 && ( (this.getCancelletterno()==castOther.getCancelletterno()) || ( this.getCancelletterno()!=null && castOther.getCancelletterno()!=null && this.getCancelletterno().equals(castOther.getCancelletterno()) ) )
 && ( (this.getPrintcancelletterdate()==castOther.getPrintcancelletterdate()) || ( this.getPrintcancelletterdate()!=null && castOther.getPrintcancelletterdate()!=null && this.getPrintcancelletterdate().equals(castOther.getPrintcancelletterdate()) ) )
 && ( (this.getPartnercode()==castOther.getPartnercode()) || ( this.getPartnercode()!=null && castOther.getPartnercode()!=null && this.getPartnercode().equals(castOther.getPartnercode()) ) )
 && ( (this.getPartnername()==castOther.getPartnername()) || ( this.getPartnername()!=null && castOther.getPartnername()!=null && this.getPartnername().equals(castOther.getPartnername()) ) )
 && ( (this.getDatabasesource()==castOther.getDatabasesource()) || ( this.getDatabasesource()!=null && castOther.getDatabasesource()!=null && this.getDatabasesource().equals(castOther.getDatabasesource()) ) )
 && ( (this.getRefname()==castOther.getRefname()) || ( this.getRefname()!=null && castOther.getRefname()!=null && this.getRefname().equals(castOther.getRefname()) ) )
 && ( (this.getRefnationid()==castOther.getRefnationid()) || ( this.getRefnationid()!=null && castOther.getRefnationid()!=null && this.getRefnationid().equals(castOther.getRefnationid()) ) )
 && ( (this.getRefcreditcardno()==castOther.getRefcreditcardno()) || ( this.getRefcreditcardno()!=null && castOther.getRefcreditcardno()!=null && this.getRefcreditcardno().equals(castOther.getRefcreditcardno()) ) )
 && ( (this.getFacility()==castOther.getFacility()) || ( this.getFacility()!=null && castOther.getFacility()!=null && this.getFacility().equals(castOther.getFacility()) ) )
 && ( (this.getUwdescription()==castOther.getUwdescription()) || ( this.getUwdescription()!=null && castOther.getUwdescription()!=null && this.getUwdescription().equals(castOther.getUwdescription()) ) )
 && ( (this.getUwstatus()==castOther.getUwstatus()) || ( this.getUwstatus()!=null && castOther.getUwstatus()!=null && this.getUwstatus().equals(castOther.getUwstatus()) ) )
 && ( (this.getTmksaledate()==castOther.getTmksaledate()) || ( this.getTmksaledate()!=null && castOther.getTmksaledate()!=null && this.getTmksaledate().equals(castOther.getTmksaledate()) ) )
 && ( (this.getCoverage()==castOther.getCoverage()) || ( this.getCoverage()!=null && castOther.getCoverage()!=null && this.getCoverage().equals(castOther.getCoverage()) ) )
 && ( (this.getPaidtodate()==castOther.getPaidtodate()) || ( this.getPaidtodate()!=null && castOther.getPaidtodate()!=null && this.getPaidtodate().equals(castOther.getPaidtodate()) ) )
 && ( (this.getExtrarate()==castOther.getExtrarate()) || ( this.getExtrarate()!=null && castOther.getExtrarate()!=null && this.getExtrarate().equals(castOther.getExtrarate()) ) )
 && ( (this.getVoicetag()==castOther.getVoicetag()) || ( this.getVoicetag()!=null && castOther.getVoicetag()!=null && this.getVoicetag().equals(castOther.getVoicetag()) ) )
 && ( (this.getDeathdate()==castOther.getDeathdate()) || ( this.getDeathdate()!=null && castOther.getDeathdate()!=null && this.getDeathdate().equals(castOther.getDeathdate()) ) )
 && ( (this.getCustomerloanapprovedate()==castOther.getCustomerloanapprovedate()) || ( this.getCustomerloanapprovedate()!=null && castOther.getCustomerloanapprovedate()!=null && this.getCustomerloanapprovedate().equals(castOther.getCustomerloanapprovedate()) ) )
 && ( (this.getLob()==castOther.getLob()) || ( this.getLob()!=null && castOther.getLob()!=null && this.getLob().equals(castOther.getLob()) ) )
 && ( (this.getCanceltransactiondate()==castOther.getCanceltransactiondate()) || ( this.getCanceltransactiondate()!=null && castOther.getCanceltransactiondate()!=null && this.getCanceltransactiondate().equals(castOther.getCanceltransactiondate()) ) )
 && ( (this.getOldaccountno()==castOther.getOldaccountno()) || ( this.getOldaccountno()!=null && castOther.getOldaccountno()!=null && this.getOldaccountno().equals(castOther.getOldaccountno()) ) )
 && ( (this.getCustomeroccupationtext()==castOther.getCustomeroccupationtext()) || ( this.getCustomeroccupationtext()!=null && castOther.getCustomeroccupationtext()!=null && this.getCustomeroccupationtext().equals(castOther.getCustomeroccupationtext()) ) )
 && ( (this.getLoaninstallment1stdue()==castOther.getLoaninstallment1stdue()) || ( this.getLoaninstallment1stdue()!=null && castOther.getLoaninstallment1stdue()!=null && this.getLoaninstallment1stdue().equals(castOther.getLoaninstallment1stdue()) ) )
 && ( (this.getCustomercontactofficepay()==castOther.getCustomercontactofficepay()) || ( this.getCustomercontactofficepay()!=null && castOther.getCustomercontactofficepay()!=null && this.getCustomercontactofficepay().equals(castOther.getCustomercontactofficepay()) ) )
 && ( (this.getPercentofbenefitciary1()==castOther.getPercentofbenefitciary1()) || ( this.getPercentofbenefitciary1()!=null && castOther.getPercentofbenefitciary1()!=null && this.getPercentofbenefitciary1().equals(castOther.getPercentofbenefitciary1()) ) )
 && ( (this.getPercentofbenefitciary2()==castOther.getPercentofbenefitciary2()) || ( this.getPercentofbenefitciary2()!=null && castOther.getPercentofbenefitciary2()!=null && this.getPercentofbenefitciary2().equals(castOther.getPercentofbenefitciary2()) ) )
 && ( (this.getPercentofbenefitciary3()==castOther.getPercentofbenefitciary3()) || ( this.getPercentofbenefitciary3()!=null && castOther.getPercentofbenefitciary3()!=null && this.getPercentofbenefitciary3().equals(castOther.getPercentofbenefitciary3()) ) )
 && ( (this.getPercentofbenefitciary4()==castOther.getPercentofbenefitciary4()) || ( this.getPercentofbenefitciary4()!=null && castOther.getPercentofbenefitciary4()!=null && this.getPercentofbenefitciary4().equals(castOther.getPercentofbenefitciary4()) ) )
 && ( (this.getDownplaneffectivedate()==castOther.getDownplaneffectivedate()) || ( this.getDownplaneffectivedate()!=null && castOther.getDownplaneffectivedate()!=null && this.getDownplaneffectivedate().equals(castOther.getDownplaneffectivedate()) ) )
 && ( (this.getDateSosover()==castOther.getDateSosover()) || ( this.getDateSosover()!=null && castOther.getDateSosover()!=null && this.getDateSosover().equals(castOther.getDateSosover()) ) )
 && ( (this.getCustomerduration()==castOther.getCustomerduration()) || ( this.getCustomerduration()!=null && castOther.getCustomerduration()!=null && this.getCustomerduration().equals(castOther.getCustomerduration()) ) )
 && ( (this.getMed()==castOther.getMed()) || ( this.getMed()!=null && castOther.getMed()!=null && this.getMed().equals(castOther.getMed()) ) )
 && ( (this.getCustomernation()==castOther.getCustomernation()) || ( this.getCustomernation()!=null && castOther.getCustomernation()!=null && this.getCustomernation().equals(castOther.getCustomernation()) ) )
 && ( (this.getEndorsedate()==castOther.getEndorsedate()) || ( this.getEndorsedate()!=null && castOther.getEndorsedate()!=null && this.getEndorsedate().equals(castOther.getEndorsedate()) ) )
 && ( (this.getInformdate1()==castOther.getInformdate1()) || ( this.getInformdate1()!=null && castOther.getInformdate1()!=null && this.getInformdate1().equals(castOther.getInformdate1()) ) )
 && ( (this.getPaydate1()==castOther.getPaydate1()) || ( this.getPaydate1()!=null && castOther.getPaydate1()!=null && this.getPaydate1().equals(castOther.getPaydate1()) ) )
 && ( (this.getAmount1()==castOther.getAmount1()) || ( this.getAmount1()!=null && castOther.getAmount1()!=null && this.getAmount1().equals(castOther.getAmount1()) ) )
 && ( (this.getInformdate2()==castOther.getInformdate2()) || ( this.getInformdate2()!=null && castOther.getInformdate2()!=null && this.getInformdate2().equals(castOther.getInformdate2()) ) )
 && ( (this.getPaydate2()==castOther.getPaydate2()) || ( this.getPaydate2()!=null && castOther.getPaydate2()!=null && this.getPaydate2().equals(castOther.getPaydate2()) ) )
 && ( (this.getAmount2()==castOther.getAmount2()) || ( this.getAmount2()!=null && castOther.getAmount2()!=null && this.getAmount2().equals(castOther.getAmount2()) ) )
 && ( (this.getDeaddate()==castOther.getDeaddate()) || ( this.getDeaddate()!=null && castOther.getDeaddate()!=null && this.getDeaddate().equals(castOther.getDeaddate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProductname() == null ? 0 : this.getProductname().hashCode() );
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getProductcode() == null ? 0 : this.getProductcode().hashCode() );
         result = 37 * result + ( getCertificateno() == null ? 0 : this.getCertificateno().hashCode() );
         result = 37 * result + ( getSaledate() == null ? 0 : this.getSaledate().hashCode() );
         result = 37 * result + ( getBranchname() == null ? 0 : this.getBranchname().hashCode() );
         result = 37 * result + ( getCustomercode() == null ? 0 : this.getCustomercode().hashCode() );
         result = 37 * result + ( getAccountno() == null ? 0 : this.getAccountno().hashCode() );
         result = 37 * result + ( getLoanno() == null ? 0 : this.getLoanno().hashCode() );
         result = 37 * result + ( getTotalofloan() == null ? 0 : this.getTotalofloan().hashCode() );
         result = 37 * result + ( getSa() == null ? 0 : this.getSa().hashCode() );
         result = 37 * result + ( getPrem() == null ? 0 : this.getPrem().hashCode() );
         result = 37 * result + ( getDurationinsurance() == null ? 0 : this.getDurationinsurance().hashCode() );
         result = 37 * result + ( getInsurancestatus() == null ? 0 : this.getInsurancestatus().hashCode() );
         result = 37 * result + ( getEffectivedate() == null ? 0 : this.getEffectivedate().hashCode() );
         result = 37 * result + ( getExpireddate() == null ? 0 : this.getExpireddate().hashCode() );
         result = 37 * result + ( getCustomerstatus() == null ? 0 : this.getCustomerstatus().hashCode() );
         result = 37 * result + ( getCanceldate() == null ? 0 : this.getCanceldate().hashCode() );
         result = 37 * result + ( getCancelreason() == null ? 0 : this.getCancelreason().hashCode() );
         result = 37 * result + ( getCanceldescription() == null ? 0 : this.getCanceldescription().hashCode() );
         result = 37 * result + ( getChannel() == null ? 0 : this.getChannel().hashCode() );
         result = 37 * result + ( getPrefix() == null ? 0 : this.getPrefix().hashCode() );
         result = 37 * result + ( getNameth() == null ? 0 : this.getNameth().hashCode() );
         result = 37 * result + ( getSurnameth() == null ? 0 : this.getSurnameth().hashCode() );
         result = 37 * result + ( getBirthdate() == null ? 0 : this.getBirthdate().hashCode() );
         result = 37 * result + ( getAge() == null ? 0 : this.getAge().hashCode() );
         result = 37 * result + ( getWeight() == null ? 0 : this.getWeight().hashCode() );
         result = 37 * result + ( getHeight() == null ? 0 : this.getHeight().hashCode() );
         result = 37 * result + ( getGender() == null ? 0 : this.getGender().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getNationid() == null ? 0 : this.getNationid().hashCode() );
         result = 37 * result + ( getCreditcardno() == null ? 0 : this.getCreditcardno().hashCode() );
         result = 37 * result + ( getExpiredcreditcard() == null ? 0 : this.getExpiredcreditcard().hashCode() );
         result = 37 * result + ( getAddress1() == null ? 0 : this.getAddress1().hashCode() );
         result = 37 * result + ( getAddress2() == null ? 0 : this.getAddress2().hashCode() );
         result = 37 * result + ( getAddressoffice1() == null ? 0 : this.getAddressoffice1().hashCode() );
         result = 37 * result + ( getAddressoffice2() == null ? 0 : this.getAddressoffice2().hashCode() );
         result = 37 * result + ( getNameofbenefit1() == null ? 0 : this.getNameofbenefit1().hashCode() );
         result = 37 * result + ( getNameofbenefit2() == null ? 0 : this.getNameofbenefit2().hashCode() );
         result = 37 * result + ( getNameofbenefit3() == null ? 0 : this.getNameofbenefit3().hashCode() );
         result = 37 * result + ( getNameofbenefit4() == null ? 0 : this.getNameofbenefit4().hashCode() );
         result = 37 * result + ( getRelationship1() == null ? 0 : this.getRelationship1().hashCode() );
         result = 37 * result + ( getRelationship2() == null ? 0 : this.getRelationship2().hashCode() );
         result = 37 * result + ( getRelationship3() == null ? 0 : this.getRelationship3().hashCode() );
         result = 37 * result + ( getRelationship4() == null ? 0 : this.getRelationship4().hashCode() );
         result = 37 * result + ( getHometel() == null ? 0 : this.getHometel().hashCode() );
         result = 37 * result + ( getMobiletel() == null ? 0 : this.getMobiletel().hashCode() );
         result = 37 * result + ( getOfficetel() == null ? 0 : this.getOfficetel().hashCode() );
         result = 37 * result + ( getOfficercodesale() == null ? 0 : this.getOfficercodesale().hashCode() );
         result = 37 * result + ( getSalenameth() == null ? 0 : this.getSalenameth().hashCode() );
         result = 37 * result + ( getManagercode() == null ? 0 : this.getManagercode().hashCode() );
         result = 37 * result + ( getDateprintcert() == null ? 0 : this.getDateprintcert().hashCode() );
         result = 37 * result + ( getPostbackdate() == null ? 0 : this.getPostbackdate().hashCode() );
         result = 37 * result + ( getCancelletterno() == null ? 0 : this.getCancelletterno().hashCode() );
         result = 37 * result + ( getPrintcancelletterdate() == null ? 0 : this.getPrintcancelletterdate().hashCode() );
         result = 37 * result + ( getPartnercode() == null ? 0 : this.getPartnercode().hashCode() );
         result = 37 * result + ( getPartnername() == null ? 0 : this.getPartnername().hashCode() );
         result = 37 * result + ( getDatabasesource() == null ? 0 : this.getDatabasesource().hashCode() );
         result = 37 * result + ( getRefname() == null ? 0 : this.getRefname().hashCode() );
         result = 37 * result + ( getRefnationid() == null ? 0 : this.getRefnationid().hashCode() );
         result = 37 * result + ( getRefcreditcardno() == null ? 0 : this.getRefcreditcardno().hashCode() );
         result = 37 * result + ( getFacility() == null ? 0 : this.getFacility().hashCode() );
         result = 37 * result + ( getUwdescription() == null ? 0 : this.getUwdescription().hashCode() );
         result = 37 * result + ( getUwstatus() == null ? 0 : this.getUwstatus().hashCode() );
         result = 37 * result + ( getTmksaledate() == null ? 0 : this.getTmksaledate().hashCode() );
         result = 37 * result + ( getCoverage() == null ? 0 : this.getCoverage().hashCode() );
         result = 37 * result + ( getPaidtodate() == null ? 0 : this.getPaidtodate().hashCode() );
         result = 37 * result + ( getExtrarate() == null ? 0 : this.getExtrarate().hashCode() );
         result = 37 * result + ( getVoicetag() == null ? 0 : this.getVoicetag().hashCode() );
         result = 37 * result + ( getDeathdate() == null ? 0 : this.getDeathdate().hashCode() );
         result = 37 * result + ( getCustomerloanapprovedate() == null ? 0 : this.getCustomerloanapprovedate().hashCode() );
         result = 37 * result + ( getLob() == null ? 0 : this.getLob().hashCode() );
         result = 37 * result + ( getCanceltransactiondate() == null ? 0 : this.getCanceltransactiondate().hashCode() );
         result = 37 * result + ( getOldaccountno() == null ? 0 : this.getOldaccountno().hashCode() );
         result = 37 * result + ( getCustomeroccupationtext() == null ? 0 : this.getCustomeroccupationtext().hashCode() );
         result = 37 * result + ( getLoaninstallment1stdue() == null ? 0 : this.getLoaninstallment1stdue().hashCode() );
         result = 37 * result + ( getCustomercontactofficepay() == null ? 0 : this.getCustomercontactofficepay().hashCode() );
         result = 37 * result + ( getPercentofbenefitciary1() == null ? 0 : this.getPercentofbenefitciary1().hashCode() );
         result = 37 * result + ( getPercentofbenefitciary2() == null ? 0 : this.getPercentofbenefitciary2().hashCode() );
         result = 37 * result + ( getPercentofbenefitciary3() == null ? 0 : this.getPercentofbenefitciary3().hashCode() );
         result = 37 * result + ( getPercentofbenefitciary4() == null ? 0 : this.getPercentofbenefitciary4().hashCode() );
         result = 37 * result + ( getDownplaneffectivedate() == null ? 0 : this.getDownplaneffectivedate().hashCode() );
         result = 37 * result + ( getDateSosover() == null ? 0 : this.getDateSosover().hashCode() );
         result = 37 * result + ( getCustomerduration() == null ? 0 : this.getCustomerduration().hashCode() );
         result = 37 * result + ( getMed() == null ? 0 : this.getMed().hashCode() );
         result = 37 * result + ( getCustomernation() == null ? 0 : this.getCustomernation().hashCode() );
         result = 37 * result + ( getEndorsedate() == null ? 0 : this.getEndorsedate().hashCode() );
         result = 37 * result + ( getInformdate1() == null ? 0 : this.getInformdate1().hashCode() );
         result = 37 * result + ( getPaydate1() == null ? 0 : this.getPaydate1().hashCode() );
         result = 37 * result + ( getAmount1() == null ? 0 : this.getAmount1().hashCode() );
         result = 37 * result + ( getInformdate2() == null ? 0 : this.getInformdate2().hashCode() );
         result = 37 * result + ( getPaydate2() == null ? 0 : this.getPaydate2().hashCode() );
         result = 37 * result + ( getAmount2() == null ? 0 : this.getAmount2().hashCode() );
         result = 37 * result + ( getDeaddate() == null ? 0 : this.getDeaddate().hashCode() );
         return result;
   }   


}


