package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
)
public class Payment  implements java.io.Serializable {


     private PaymentId id;

    public Payment() {
    }

    public Payment(PaymentId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="partnercode", column=@Column(name="partnercode") ), 
        @AttributeOverride(name="policyno", column=@Column(name="policyno") ), 
        @AttributeOverride(name="productcode", column=@Column(name="productcode") ), 
        @AttributeOverride(name="customercode", column=@Column(name="customercode") ), 
        @AttributeOverride(name="duedate", column=@Column(name="duedate") ), 
        @AttributeOverride(name="senddate", column=@Column(name="senddate") ), 
        @AttributeOverride(name="ob", column=@Column(name="ob") ), 
        @AttributeOverride(name="paymentdate", column=@Column(name="paymentdate") ), 
        @AttributeOverride(name="premiumamt", column=@Column(name="premiumamt") ), 
        @AttributeOverride(name="adjustpremium", column=@Column(name="adjustpremium") ), 
        @AttributeOverride(name="typeofpayment", column=@Column(name="typeofpayment") ), 
        @AttributeOverride(name="accno", column=@Column(name="accno") ), 
        @AttributeOverride(name="refund", column=@Column(name="refund") ), 
        @AttributeOverride(name="dateofrefund", column=@Column(name="dateofrefund") ), 
        @AttributeOverride(name="invoiceno", column=@Column(name="invoiceno") ), 
        @AttributeOverride(name="monthenddate", column=@Column(name="monthenddate") ), 
        @AttributeOverride(name="payDate", column=@Column(name="pay_date") ), 
        @AttributeOverride(name="refundAmount", column=@Column(name="refund_amount") ), 
        @AttributeOverride(name="collecteddate", column=@Column(name="collecteddate") ) } )
    public PaymentId getId() {
        return this.id;
    }
    
    public void setId(PaymentId id) {
        this.id = id;
    }




}


