package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentId generated by hbm2java
 */
@Embeddable
public class PaymentId  implements java.io.Serializable {


     private String partnercode;
     private String policyno;
     private String productcode;
     private String customercode;
     private String duedate;
     private String senddate;
     private String ob;
     private String paymentdate;
     private String premiumamt;
     private String adjustpremium;
     private String typeofpayment;
     private String accno;
     private String refund;
     private String dateofrefund;
     private String invoiceno;
     private String monthenddate;
     private String payDate;
     private String refundAmount;
     private String collecteddate;

    public PaymentId() {
    }

    public PaymentId(String partnercode, String policyno, String productcode, String customercode, String duedate, String senddate, String ob, String paymentdate, String premiumamt, String adjustpremium, String typeofpayment, String accno, String refund, String dateofrefund, String invoiceno, String monthenddate, String payDate, String refundAmount, String collecteddate) {
       this.partnercode = partnercode;
       this.policyno = policyno;
       this.productcode = productcode;
       this.customercode = customercode;
       this.duedate = duedate;
       this.senddate = senddate;
       this.ob = ob;
       this.paymentdate = paymentdate;
       this.premiumamt = premiumamt;
       this.adjustpremium = adjustpremium;
       this.typeofpayment = typeofpayment;
       this.accno = accno;
       this.refund = refund;
       this.dateofrefund = dateofrefund;
       this.invoiceno = invoiceno;
       this.monthenddate = monthenddate;
       this.payDate = payDate;
       this.refundAmount = refundAmount;
       this.collecteddate = collecteddate;
    }
   

    @Column(name="partnercode")
    public String getPartnercode() {
        return this.partnercode;
    }
    
    public void setPartnercode(String partnercode) {
        this.partnercode = partnercode;
    }

    @Column(name="policyno")
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="productcode")
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

    @Column(name="customercode")
    public String getCustomercode() {
        return this.customercode;
    }
    
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    @Column(name="duedate")
    public String getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(String duedate) {
        this.duedate = duedate;
    }

    @Column(name="senddate")
    public String getSenddate() {
        return this.senddate;
    }
    
    public void setSenddate(String senddate) {
        this.senddate = senddate;
    }

    @Column(name="ob")
    public String getOb() {
        return this.ob;
    }
    
    public void setOb(String ob) {
        this.ob = ob;
    }

    @Column(name="paymentdate")
    public String getPaymentdate() {
        return this.paymentdate;
    }
    
    public void setPaymentdate(String paymentdate) {
        this.paymentdate = paymentdate;
    }

    @Column(name="premiumamt")
    public String getPremiumamt() {
        return this.premiumamt;
    }
    
    public void setPremiumamt(String premiumamt) {
        this.premiumamt = premiumamt;
    }

    @Column(name="adjustpremium")
    public String getAdjustpremium() {
        return this.adjustpremium;
    }
    
    public void setAdjustpremium(String adjustpremium) {
        this.adjustpremium = adjustpremium;
    }

    @Column(name="typeofpayment")
    public String getTypeofpayment() {
        return this.typeofpayment;
    }
    
    public void setTypeofpayment(String typeofpayment) {
        this.typeofpayment = typeofpayment;
    }

    @Column(name="accno")
    public String getAccno() {
        return this.accno;
    }
    
    public void setAccno(String accno) {
        this.accno = accno;
    }

    @Column(name="refund")
    public String getRefund() {
        return this.refund;
    }
    
    public void setRefund(String refund) {
        this.refund = refund;
    }

    @Column(name="dateofrefund")
    public String getDateofrefund() {
        return this.dateofrefund;
    }
    
    public void setDateofrefund(String dateofrefund) {
        this.dateofrefund = dateofrefund;
    }

    @Column(name="invoiceno")
    public String getInvoiceno() {
        return this.invoiceno;
    }
    
    public void setInvoiceno(String invoiceno) {
        this.invoiceno = invoiceno;
    }

    @Column(name="monthenddate")
    public String getMonthenddate() {
        return this.monthenddate;
    }
    
    public void setMonthenddate(String monthenddate) {
        this.monthenddate = monthenddate;
    }

    @Column(name="pay_date")
    public String getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }

    @Column(name="refund_amount")
    public String getRefundAmount() {
        return this.refundAmount;
    }
    
    public void setRefundAmount(String refundAmount) {
        this.refundAmount = refundAmount;
    }

    @Column(name="collecteddate")
    public String getCollecteddate() {
        return this.collecteddate;
    }
    
    public void setCollecteddate(String collecteddate) {
        this.collecteddate = collecteddate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaymentId) ) return false;
		 PaymentId castOther = ( PaymentId ) other; 
         
		 return ( (this.getPartnercode()==castOther.getPartnercode()) || ( this.getPartnercode()!=null && castOther.getPartnercode()!=null && this.getPartnercode().equals(castOther.getPartnercode()) ) )
 && ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getProductcode()==castOther.getProductcode()) || ( this.getProductcode()!=null && castOther.getProductcode()!=null && this.getProductcode().equals(castOther.getProductcode()) ) )
 && ( (this.getCustomercode()==castOther.getCustomercode()) || ( this.getCustomercode()!=null && castOther.getCustomercode()!=null && this.getCustomercode().equals(castOther.getCustomercode()) ) )
 && ( (this.getDuedate()==castOther.getDuedate()) || ( this.getDuedate()!=null && castOther.getDuedate()!=null && this.getDuedate().equals(castOther.getDuedate()) ) )
 && ( (this.getSenddate()==castOther.getSenddate()) || ( this.getSenddate()!=null && castOther.getSenddate()!=null && this.getSenddate().equals(castOther.getSenddate()) ) )
 && ( (this.getOb()==castOther.getOb()) || ( this.getOb()!=null && castOther.getOb()!=null && this.getOb().equals(castOther.getOb()) ) )
 && ( (this.getPaymentdate()==castOther.getPaymentdate()) || ( this.getPaymentdate()!=null && castOther.getPaymentdate()!=null && this.getPaymentdate().equals(castOther.getPaymentdate()) ) )
 && ( (this.getPremiumamt()==castOther.getPremiumamt()) || ( this.getPremiumamt()!=null && castOther.getPremiumamt()!=null && this.getPremiumamt().equals(castOther.getPremiumamt()) ) )
 && ( (this.getAdjustpremium()==castOther.getAdjustpremium()) || ( this.getAdjustpremium()!=null && castOther.getAdjustpremium()!=null && this.getAdjustpremium().equals(castOther.getAdjustpremium()) ) )
 && ( (this.getTypeofpayment()==castOther.getTypeofpayment()) || ( this.getTypeofpayment()!=null && castOther.getTypeofpayment()!=null && this.getTypeofpayment().equals(castOther.getTypeofpayment()) ) )
 && ( (this.getAccno()==castOther.getAccno()) || ( this.getAccno()!=null && castOther.getAccno()!=null && this.getAccno().equals(castOther.getAccno()) ) )
 && ( (this.getRefund()==castOther.getRefund()) || ( this.getRefund()!=null && castOther.getRefund()!=null && this.getRefund().equals(castOther.getRefund()) ) )
 && ( (this.getDateofrefund()==castOther.getDateofrefund()) || ( this.getDateofrefund()!=null && castOther.getDateofrefund()!=null && this.getDateofrefund().equals(castOther.getDateofrefund()) ) )
 && ( (this.getInvoiceno()==castOther.getInvoiceno()) || ( this.getInvoiceno()!=null && castOther.getInvoiceno()!=null && this.getInvoiceno().equals(castOther.getInvoiceno()) ) )
 && ( (this.getMonthenddate()==castOther.getMonthenddate()) || ( this.getMonthenddate()!=null && castOther.getMonthenddate()!=null && this.getMonthenddate().equals(castOther.getMonthenddate()) ) )
 && ( (this.getPayDate()==castOther.getPayDate()) || ( this.getPayDate()!=null && castOther.getPayDate()!=null && this.getPayDate().equals(castOther.getPayDate()) ) )
 && ( (this.getRefundAmount()==castOther.getRefundAmount()) || ( this.getRefundAmount()!=null && castOther.getRefundAmount()!=null && this.getRefundAmount().equals(castOther.getRefundAmount()) ) )
 && ( (this.getCollecteddate()==castOther.getCollecteddate()) || ( this.getCollecteddate()!=null && castOther.getCollecteddate()!=null && this.getCollecteddate().equals(castOther.getCollecteddate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPartnercode() == null ? 0 : this.getPartnercode().hashCode() );
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getProductcode() == null ? 0 : this.getProductcode().hashCode() );
         result = 37 * result + ( getCustomercode() == null ? 0 : this.getCustomercode().hashCode() );
         result = 37 * result + ( getDuedate() == null ? 0 : this.getDuedate().hashCode() );
         result = 37 * result + ( getSenddate() == null ? 0 : this.getSenddate().hashCode() );
         result = 37 * result + ( getOb() == null ? 0 : this.getOb().hashCode() );
         result = 37 * result + ( getPaymentdate() == null ? 0 : this.getPaymentdate().hashCode() );
         result = 37 * result + ( getPremiumamt() == null ? 0 : this.getPremiumamt().hashCode() );
         result = 37 * result + ( getAdjustpremium() == null ? 0 : this.getAdjustpremium().hashCode() );
         result = 37 * result + ( getTypeofpayment() == null ? 0 : this.getTypeofpayment().hashCode() );
         result = 37 * result + ( getAccno() == null ? 0 : this.getAccno().hashCode() );
         result = 37 * result + ( getRefund() == null ? 0 : this.getRefund().hashCode() );
         result = 37 * result + ( getDateofrefund() == null ? 0 : this.getDateofrefund().hashCode() );
         result = 37 * result + ( getInvoiceno() == null ? 0 : this.getInvoiceno().hashCode() );
         result = 37 * result + ( getMonthenddate() == null ? 0 : this.getMonthenddate().hashCode() );
         result = 37 * result + ( getPayDate() == null ? 0 : this.getPayDate().hashCode() );
         result = 37 * result + ( getRefundAmount() == null ? 0 : this.getRefundAmount().hashCode() );
         result = 37 * result + ( getCollecteddate() == null ? 0 : this.getCollecteddate().hashCode() );
         return result;
   }   


}


