package th.co.ipassion.testtool.entity.tlp;
// Generated Dec 18, 2017 12:26:51 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Splitpremiumamount generated by hbm2java
 */
@Entity
@Table(name="splitpremiumamount"
)
public class Splitpremiumamount  implements java.io.Serializable {


     private SplitpremiumamountId id;

    public Splitpremiumamount() {
    }

    public Splitpremiumamount(SplitpremiumamountId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="productid", column=@Column(name="productid") ), 
        @AttributeOverride(name="grouppolicyno", column=@Column(name="grouppolicyno") ), 
        @AttributeOverride(name="customercode", column=@Column(name="customercode") ), 
        @AttributeOverride(name="totpremium", column=@Column(name="totpremium") ), 
        @AttributeOverride(name="lifepremium", column=@Column(name="lifepremium") ), 
        @AttributeOverride(name="deathpremium", column=@Column(name="deathpremium") ), 
        @AttributeOverride(name="tpdpremium", column=@Column(name="tpdpremium") ), 
        @AttributeOverride(name="ttdpremium", column=@Column(name="ttdpremium") ), 
        @AttributeOverride(name="tdpremium", column=@Column(name="tdpremium") ), 
        @AttributeOverride(name="papremium", column=@Column(name="papremium") ), 
        @AttributeOverride(name="adbpremium", column=@Column(name="adbpremium") ), 
        @AttributeOverride(name="addpremium", column=@Column(name="addpremium") ), 
        @AttributeOverride(name="rccpremium", column=@Column(name="rccpremium") ), 
        @AttributeOverride(name="mapremium", column=@Column(name="mapremium") ), 
        @AttributeOverride(name="mcpremium", column=@Column(name="mcpremium") ), 
        @AttributeOverride(name="mepremium", column=@Column(name="mepremium") ), 
        @AttributeOverride(name="hbpremium", column=@Column(name="hbpremium") ), 
        @AttributeOverride(name="hapremium", column=@Column(name="hapremium") ), 
        @AttributeOverride(name="hspremium", column=@Column(name="hspremium") ), 
        @AttributeOverride(name="ddpremium", column=@Column(name="ddpremium") ), 
        @AttributeOverride(name="lifetpdpremium", column=@Column(name="lifetpdpremium") ) } )
    public SplitpremiumamountId getId() {
        return this.id;
    }
    
    public void setId(SplitpremiumamountId id) {
        this.id = id;
    }




}


