package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertriderId generated by hbm2java
 */
@Embeddable
public class CertriderId  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String ridertype;

    public CertriderId() {
    }

    public CertriderId(String policyno, String certno, String ridertype) {
       this.policyno = policyno;
       this.certno = certno;
       this.ridertype = ridertype;
    }
   

    @Column(name="policyno", nullable=false, length=4)
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno", nullable=false, length=8)
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="ridertype", nullable=false, length=3)
    public String getRidertype() {
        return this.ridertype;
    }
    
    public void setRidertype(String ridertype) {
        this.ridertype = ridertype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CertriderId) ) return false;
		 CertriderId castOther = ( CertriderId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getRidertype()==castOther.getRidertype()) || ( this.getRidertype()!=null && castOther.getRidertype()!=null && this.getRidertype().equals(castOther.getRidertype()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getRidertype() == null ? 0 : this.getRidertype().hashCode() );
         return result;
   }   


}


