package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Certrider generated by hbm2java
 */
@Entity
@Table(name="certrider"
)
public class Certrider  implements java.io.Serializable {


     private CertriderId id;
     private Integer sum;
     private BigDecimal premium;
     private BigDecimal extrapremium;
     private String riderstatus;
     private String riderstatusdate;

    public Certrider() {
    }

	
    public Certrider(CertriderId id) {
        this.id = id;
    }
    public Certrider(CertriderId id, Integer sum, BigDecimal premium, BigDecimal extrapremium, String riderstatus, String riderstatusdate) {
       this.id = id;
       this.sum = sum;
       this.premium = premium;
       this.extrapremium = extrapremium;
       this.riderstatus = riderstatus;
       this.riderstatusdate = riderstatusdate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno", nullable=false, length=4) ), 
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="ridertype", column=@Column(name="ridertype", nullable=false, length=3) ) } )
    public CertriderId getId() {
        return this.id;
    }
    
    public void setId(CertriderId id) {
        this.id = id;
    }
    
    @Column(name="sum")
    public Integer getSum() {
        return this.sum;
    }
    
    public void setSum(Integer sum) {
        this.sum = sum;
    }
    
    @Column(name="premium", precision=10)
    public BigDecimal getPremium() {
        return this.premium;
    }
    
    public void setPremium(BigDecimal premium) {
        this.premium = premium;
    }
    
    @Column(name="extrapremium", precision=10)
    public BigDecimal getExtrapremium() {
        return this.extrapremium;
    }
    
    public void setExtrapremium(BigDecimal extrapremium) {
        this.extrapremium = extrapremium;
    }
    
    @Column(name="riderstatus", length=8)
    public String getRiderstatus() {
        return this.riderstatus;
    }
    
    public void setRiderstatus(String riderstatus) {
        this.riderstatus = riderstatus;
    }
    
    @Column(name="riderstatusdate", length=1)
    public String getRiderstatusdate() {
        return this.riderstatusdate;
    }
    
    public void setRiderstatusdate(String riderstatusdate) {
        this.riderstatusdate = riderstatusdate;
    }




}


