package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertmappingId generated by hbm2java
 */
@Embeddable
public class CertmappingId  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String rpolicyno;
     private String rcertno;

    public CertmappingId() {
    }

    public CertmappingId(String policyno, String certno, String rpolicyno, String rcertno) {
       this.policyno = policyno;
       this.certno = certno;
       this.rpolicyno = rpolicyno;
       this.rcertno = rcertno;
    }
   

    @Column(name="policyno", nullable=false, length=4)
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno", nullable=false, length=8)
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="rpolicyno", nullable=false, length=8)
    public String getRpolicyno() {
        return this.rpolicyno;
    }
    
    public void setRpolicyno(String rpolicyno) {
        this.rpolicyno = rpolicyno;
    }

    @Column(name="rcertno", nullable=false, length=15)
    public String getRcertno() {
        return this.rcertno;
    }
    
    public void setRcertno(String rcertno) {
        this.rcertno = rcertno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CertmappingId) ) return false;
		 CertmappingId castOther = ( CertmappingId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getRpolicyno()==castOther.getRpolicyno()) || ( this.getRpolicyno()!=null && castOther.getRpolicyno()!=null && this.getRpolicyno().equals(castOther.getRpolicyno()) ) )
 && ( (this.getRcertno()==castOther.getRcertno()) || ( this.getRcertno()!=null && castOther.getRcertno()!=null && this.getRcertno().equals(castOther.getRcertno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getRpolicyno() == null ? 0 : this.getRpolicyno().hashCode() );
         result = 37 * result + ( getRcertno() == null ? 0 : this.getRcertno().hashCode() );
         return result;
   }   


}


