package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertlinkerId generated by hbm2java
 */
@Embeddable
public class CertlinkerId  implements java.io.Serializable {


     private String policynohp;
     private String certnohp;
     private String policynocp;
     private String certnocp;

    public CertlinkerId() {
    }

    public CertlinkerId(String policynohp, String certnohp, String policynocp, String certnocp) {
       this.policynohp = policynohp;
       this.certnohp = certnohp;
       this.policynocp = policynocp;
       this.certnocp = certnocp;
    }
   

    @Column(name="policynohp", nullable=false, length=4)
    public String getPolicynohp() {
        return this.policynohp;
    }
    
    public void setPolicynohp(String policynohp) {
        this.policynohp = policynohp;
    }

    @Column(name="certnohp", nullable=false, length=8)
    public String getCertnohp() {
        return this.certnohp;
    }
    
    public void setCertnohp(String certnohp) {
        this.certnohp = certnohp;
    }

    @Column(name="policynocp", nullable=false, length=4)
    public String getPolicynocp() {
        return this.policynocp;
    }
    
    public void setPolicynocp(String policynocp) {
        this.policynocp = policynocp;
    }

    @Column(name="certnocp", nullable=false, length=8)
    public String getCertnocp() {
        return this.certnocp;
    }
    
    public void setCertnocp(String certnocp) {
        this.certnocp = certnocp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CertlinkerId) ) return false;
		 CertlinkerId castOther = ( CertlinkerId ) other; 
         
		 return ( (this.getPolicynohp()==castOther.getPolicynohp()) || ( this.getPolicynohp()!=null && castOther.getPolicynohp()!=null && this.getPolicynohp().equals(castOther.getPolicynohp()) ) )
 && ( (this.getCertnohp()==castOther.getCertnohp()) || ( this.getCertnohp()!=null && castOther.getCertnohp()!=null && this.getCertnohp().equals(castOther.getCertnohp()) ) )
 && ( (this.getPolicynocp()==castOther.getPolicynocp()) || ( this.getPolicynocp()!=null && castOther.getPolicynocp()!=null && this.getPolicynocp().equals(castOther.getPolicynocp()) ) )
 && ( (this.getCertnocp()==castOther.getCertnocp()) || ( this.getCertnocp()!=null && castOther.getCertnocp()!=null && this.getCertnocp().equals(castOther.getCertnocp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicynohp() == null ? 0 : this.getPolicynohp().hashCode() );
         result = 37 * result + ( getCertnohp() == null ? 0 : this.getCertnohp().hashCode() );
         result = 37 * result + ( getPolicynocp() == null ? 0 : this.getPolicynocp().hashCode() );
         result = 37 * result + ( getCertnocp() == null ? 0 : this.getCertnocp().hashCode() );
         return result;
   }   


}


