package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cert generated by hbm2java
 */
@Entity
@Table(name="cert"
)
public class Cert  implements java.io.Serializable {


     private String policyno;
     private String certno;
     private String appno;
     private String reqdate;
     private String nameid;
     private Integer age;
     private Integer smi;
     private Integer lifesum;
     private Integer accidentsum;
     private String period;
     private String loanTerm;
     private BigDecimal lifepremium;
     private BigDecimal extrapremium;
     private BigDecimal tpdpremium;
     private BigDecimal extratpdpremium;
     private BigDecimal addpremium;
     private Integer em;
     private BigDecimal tpd;
     private String effectivedate;
     private String maturedate;
     private String premiumdate;
     private String certyyyymm;
     private String statcer;
     private String statcer2;
     private String statdate2;
     private String informdate1;
     private String paydate1;
     private BigDecimal amount1;
     private String informdate2;
     private String paydate2;
     private BigDecimal amount2;
     private String deaddate;
     private String endownmentyear;
     private String deadcause;
     private String receiptflag;
     private String referenceno;
     private String reserve;

    public Cert() {
    }

	
    public Cert(String policyno) {
        this.policyno = policyno;
    }
    public Cert(String policyno, String certno, String appno, String reqdate, String nameid, Integer age, Integer smi, Integer lifesum, Integer accidentsum, String period, String loanTerm, BigDecimal lifepremium, BigDecimal extrapremium, BigDecimal tpdpremium, BigDecimal extratpdpremium, BigDecimal addpremium, Integer em, BigDecimal tpd, String effectivedate, String maturedate, String premiumdate, String certyyyymm, String statcer, String statcer2, String statdate2, String informdate1, String paydate1, BigDecimal amount1, String informdate2, String paydate2, BigDecimal amount2, String deaddate, String endownmentyear, String deadcause, String receiptflag, String referenceno, String reserve) {
       this.policyno = policyno;
       this.certno = certno;
       this.appno = appno;
       this.reqdate = reqdate;
       this.nameid = nameid;
       this.age = age;
       this.smi = smi;
       this.lifesum = lifesum;
       this.accidentsum = accidentsum;
       this.period = period;
       this.loanTerm = loanTerm;
       this.lifepremium = lifepremium;
       this.extrapremium = extrapremium;
       this.tpdpremium = tpdpremium;
       this.extratpdpremium = extratpdpremium;
       this.addpremium = addpremium;
       this.em = em;
       this.tpd = tpd;
       this.effectivedate = effectivedate;
       this.maturedate = maturedate;
       this.premiumdate = premiumdate;
       this.certyyyymm = certyyyymm;
       this.statcer = statcer;
       this.statcer2 = statcer2;
       this.statdate2 = statdate2;
       this.informdate1 = informdate1;
       this.paydate1 = paydate1;
       this.amount1 = amount1;
       this.informdate2 = informdate2;
       this.paydate2 = paydate2;
       this.amount2 = amount2;
       this.deaddate = deaddate;
       this.endownmentyear = endownmentyear;
       this.deadcause = deadcause;
       this.receiptflag = receiptflag;
       this.referenceno = referenceno;
       this.reserve = reserve;
    }
   
     @Id 
    
    @Column(name="policyno", unique=true, nullable=false, length=4)
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }
    
    @Column(name="certno", length=8)
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }
    
    @Column(name="appno", length=12)
    public String getAppno() {
        return this.appno;
    }
    
    public void setAppno(String appno) {
        this.appno = appno;
    }
    
    @Column(name="reqdate", length=8)
    public String getReqdate() {
        return this.reqdate;
    }
    
    public void setReqdate(String reqdate) {
        this.reqdate = reqdate;
    }
    
    @Column(name="nameid", length=13)
    public String getNameid() {
        return this.nameid;
    }
    
    public void setNameid(String nameid) {
        this.nameid = nameid;
    }
    
    @Column(name="age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    
    @Column(name="smi")
    public Integer getSmi() {
        return this.smi;
    }
    
    public void setSmi(Integer smi) {
        this.smi = smi;
    }
    
    @Column(name="lifesum")
    public Integer getLifesum() {
        return this.lifesum;
    }
    
    public void setLifesum(Integer lifesum) {
        this.lifesum = lifesum;
    }
    
    @Column(name="accidentsum")
    public Integer getAccidentsum() {
        return this.accidentsum;
    }
    
    public void setAccidentsum(Integer accidentsum) {
        this.accidentsum = accidentsum;
    }
    
    @Column(name="period", length=2)
    public String getPeriod() {
        return this.period;
    }
    
    public void setPeriod(String period) {
        this.period = period;
    }
    
    @Column(name="loan_term", length=2)
    public String getLoanTerm() {
        return this.loanTerm;
    }
    
    public void setLoanTerm(String loanTerm) {
        this.loanTerm = loanTerm;
    }
    
    @Column(name="lifepremium", precision=10)
    public BigDecimal getLifepremium() {
        return this.lifepremium;
    }
    
    public void setLifepremium(BigDecimal lifepremium) {
        this.lifepremium = lifepremium;
    }
    
    @Column(name="extrapremium", precision=10)
    public BigDecimal getExtrapremium() {
        return this.extrapremium;
    }
    
    public void setExtrapremium(BigDecimal extrapremium) {
        this.extrapremium = extrapremium;
    }
    
    @Column(name="tpdpremium", precision=10)
    public BigDecimal getTpdpremium() {
        return this.tpdpremium;
    }
    
    public void setTpdpremium(BigDecimal tpdpremium) {
        this.tpdpremium = tpdpremium;
    }
    
    @Column(name="extratpdpremium", precision=10)
    public BigDecimal getExtratpdpremium() {
        return this.extratpdpremium;
    }
    
    public void setExtratpdpremium(BigDecimal extratpdpremium) {
        this.extratpdpremium = extratpdpremium;
    }
    
    @Column(name="addpremium", precision=10)
    public BigDecimal getAddpremium() {
        return this.addpremium;
    }
    
    public void setAddpremium(BigDecimal addpremium) {
        this.addpremium = addpremium;
    }
    
    @Column(name="em")
    public Integer getEm() {
        return this.em;
    }
    
    public void setEm(Integer em) {
        this.em = em;
    }
    
    @Column(name="tpd", precision=4)
    public BigDecimal getTpd() {
        return this.tpd;
    }
    
    public void setTpd(BigDecimal tpd) {
        this.tpd = tpd;
    }
    
    @Column(name="effectivedate", length=8)
    public String getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(String effectivedate) {
        this.effectivedate = effectivedate;
    }
    
    @Column(name="maturedate", length=8)
    public String getMaturedate() {
        return this.maturedate;
    }
    
    public void setMaturedate(String maturedate) {
        this.maturedate = maturedate;
    }
    
    @Column(name="premiumdate", length=8)
    public String getPremiumdate() {
        return this.premiumdate;
    }
    
    public void setPremiumdate(String premiumdate) {
        this.premiumdate = premiumdate;
    }
    
    @Column(name="certyyyymm", length=6)
    public String getCertyyyymm() {
        return this.certyyyymm;
    }
    
    public void setCertyyyymm(String certyyyymm) {
        this.certyyyymm = certyyyymm;
    }
    
    @Column(name="statcer", length=1)
    public String getStatcer() {
        return this.statcer;
    }
    
    public void setStatcer(String statcer) {
        this.statcer = statcer;
    }
    
    @Column(name="statcer2", length=1)
    public String getStatcer2() {
        return this.statcer2;
    }
    
    public void setStatcer2(String statcer2) {
        this.statcer2 = statcer2;
    }
    
    @Column(name="statdate2", length=8)
    public String getStatdate2() {
        return this.statdate2;
    }
    
    public void setStatdate2(String statdate2) {
        this.statdate2 = statdate2;
    }
    
    @Column(name="informdate1", length=8)
    public String getInformdate1() {
        return this.informdate1;
    }
    
    public void setInformdate1(String informdate1) {
        this.informdate1 = informdate1;
    }
    
    @Column(name="paydate1", length=8)
    public String getPaydate1() {
        return this.paydate1;
    }
    
    public void setPaydate1(String paydate1) {
        this.paydate1 = paydate1;
    }
    
    @Column(name="amount1", precision=10)
    public BigDecimal getAmount1() {
        return this.amount1;
    }
    
    public void setAmount1(BigDecimal amount1) {
        this.amount1 = amount1;
    }
    
    @Column(name="informdate2", length=8)
    public String getInformdate2() {
        return this.informdate2;
    }
    
    public void setInformdate2(String informdate2) {
        this.informdate2 = informdate2;
    }
    
    @Column(name="paydate2", length=8)
    public String getPaydate2() {
        return this.paydate2;
    }
    
    public void setPaydate2(String paydate2) {
        this.paydate2 = paydate2;
    }
    
    @Column(name="amount2", precision=10)
    public BigDecimal getAmount2() {
        return this.amount2;
    }
    
    public void setAmount2(BigDecimal amount2) {
        this.amount2 = amount2;
    }
    
    @Column(name="deaddate", length=8)
    public String getDeaddate() {
        return this.deaddate;
    }
    
    public void setDeaddate(String deaddate) {
        this.deaddate = deaddate;
    }
    
    @Column(name="endownmentyear", length=7)
    public String getEndownmentyear() {
        return this.endownmentyear;
    }
    
    public void setEndownmentyear(String endownmentyear) {
        this.endownmentyear = endownmentyear;
    }
    
    @Column(name="deadcause", length=4)
    public String getDeadcause() {
        return this.deadcause;
    }
    
    public void setDeadcause(String deadcause) {
        this.deadcause = deadcause;
    }
    
    @Column(name="receiptflag", length=1)
    public String getReceiptflag() {
        return this.receiptflag;
    }
    
    public void setReceiptflag(String receiptflag) {
        this.receiptflag = receiptflag;
    }
    
    @Column(name="referenceno", length=20)
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }
    
    @Column(name="reserve", length=2)
    public String getReserve() {
        return this.reserve;
    }
    
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }




}


