package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompensateidId generated by hbm2java
 */
@Embeddable
public class CompensateidId  implements java.io.Serializable {


     private String compensateid;
     private String referenceid;

    public CompensateidId() {
    }

    public CompensateidId(String compensateid, String referenceid) {
       this.compensateid = compensateid;
       this.referenceid = referenceid;
    }
   

    @Column(name="compensateid")
    public String getCompensateid() {
        return this.compensateid;
    }
    
    public void setCompensateid(String compensateid) {
        this.compensateid = compensateid;
    }

    @Column(name="referenceid")
    public String getReferenceid() {
        return this.referenceid;
    }
    
    public void setReferenceid(String referenceid) {
        this.referenceid = referenceid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompensateidId) ) return false;
		 CompensateidId castOther = ( CompensateidId ) other; 
         
		 return ( (this.getCompensateid()==castOther.getCompensateid()) || ( this.getCompensateid()!=null && castOther.getCompensateid()!=null && this.getCompensateid().equals(castOther.getCompensateid()) ) )
 && ( (this.getReferenceid()==castOther.getReferenceid()) || ( this.getReferenceid()!=null && castOther.getReferenceid()!=null && this.getReferenceid().equals(castOther.getReferenceid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCompensateid() == null ? 0 : this.getCompensateid().hashCode() );
         result = 37 * result + ( getReferenceid() == null ? 0 : this.getReferenceid().hashCode() );
         return result;
   }   


}


