package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetcertId generated by hbm2java
 */
@Embeddable
public class DetcertId  implements java.io.Serializable {


     private String policyno;
     private String certno;

    public DetcertId() {
    }

    public DetcertId(String policyno, String certno) {
       this.policyno = policyno;
       this.certno = certno;
    }
   

    @Column(name="policyno", nullable=false, length=4)
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }

    @Column(name="certno", nullable=false, length=8)
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetcertId) ) return false;
		 DetcertId castOther = ( DetcertId ) other; 
         
		 return ( (this.getPolicyno()==castOther.getPolicyno()) || ( this.getPolicyno()!=null && castOther.getPolicyno()!=null && this.getPolicyno().equals(castOther.getPolicyno()) ) )
 && ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyno() == null ? 0 : this.getPolicyno().hashCode() );
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         return result;
   }   


}


