package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Detcert generated by hbm2java
 */
@Entity
@Table(name="detcert"
)
public class Detcert  implements java.io.Serializable {


     private DetcertId id;
     private String code;
     private String address1;
     private String address2;
     private String telephoneno;
     private String mariagestatus;
     private String recname1;
     private BigDecimal percent1;
     private Integer relationshipcode1;
     private String recname2;
     private BigDecimal percent2;
     private Integer relationshipcode2;
     private String recname3;
     private BigDecimal percent3;
     private Integer relationshipcode3;
     private String analist;
     private String prmiseno;
     private String prmiseno2;
     private String loantype;
     private String med;
     private String reserve;

    public Detcert() {
    }

	
    public Detcert(DetcertId id) {
        this.id = id;
    }
    public Detcert(DetcertId id, String code, String address1, String address2, String telephoneno, String mariagestatus, String recname1, BigDecimal percent1, Integer relationshipcode1, String recname2, BigDecimal percent2, Integer relationshipcode2, String recname3, BigDecimal percent3, Integer relationshipcode3, String analist, String prmiseno, String prmiseno2, String loantype, String med, String reserve) {
       this.id = id;
       this.code = code;
       this.address1 = address1;
       this.address2 = address2;
       this.telephoneno = telephoneno;
       this.mariagestatus = mariagestatus;
       this.recname1 = recname1;
       this.percent1 = percent1;
       this.relationshipcode1 = relationshipcode1;
       this.recname2 = recname2;
       this.percent2 = percent2;
       this.relationshipcode2 = relationshipcode2;
       this.recname3 = recname3;
       this.percent3 = percent3;
       this.relationshipcode3 = relationshipcode3;
       this.analist = analist;
       this.prmiseno = prmiseno;
       this.prmiseno2 = prmiseno2;
       this.loantype = loantype;
       this.med = med;
       this.reserve = reserve;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="policyno", column=@Column(name="policyno", nullable=false, length=4) ), 
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ) } )
    public DetcertId getId() {
        return this.id;
    }
    
    public void setId(DetcertId id) {
        this.id = id;
    }
    
    @Column(name="code", length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="address1", length=70)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    
    @Column(name="address2", length=70)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    
    @Column(name="telephoneno", length=60)
    public String getTelephoneno() {
        return this.telephoneno;
    }
    
    public void setTelephoneno(String telephoneno) {
        this.telephoneno = telephoneno;
    }
    
    @Column(name="mariagestatus", length=1)
    public String getMariagestatus() {
        return this.mariagestatus;
    }
    
    public void setMariagestatus(String mariagestatus) {
        this.mariagestatus = mariagestatus;
    }
    
    @Column(name="recname1", length=100)
    public String getRecname1() {
        return this.recname1;
    }
    
    public void setRecname1(String recname1) {
        this.recname1 = recname1;
    }
    
    @Column(name="percent1", precision=5)
    public BigDecimal getPercent1() {
        return this.percent1;
    }
    
    public void setPercent1(BigDecimal percent1) {
        this.percent1 = percent1;
    }
    
    @Column(name="relationshipcode1")
    public Integer getRelationshipcode1() {
        return this.relationshipcode1;
    }
    
    public void setRelationshipcode1(Integer relationshipcode1) {
        this.relationshipcode1 = relationshipcode1;
    }
    
    @Column(name="recname2", length=100)
    public String getRecname2() {
        return this.recname2;
    }
    
    public void setRecname2(String recname2) {
        this.recname2 = recname2;
    }
    
    @Column(name="percent2", precision=5)
    public BigDecimal getPercent2() {
        return this.percent2;
    }
    
    public void setPercent2(BigDecimal percent2) {
        this.percent2 = percent2;
    }
    
    @Column(name="relationshipcode2")
    public Integer getRelationshipcode2() {
        return this.relationshipcode2;
    }
    
    public void setRelationshipcode2(Integer relationshipcode2) {
        this.relationshipcode2 = relationshipcode2;
    }
    
    @Column(name="recname3", length=100)
    public String getRecname3() {
        return this.recname3;
    }
    
    public void setRecname3(String recname3) {
        this.recname3 = recname3;
    }
    
    @Column(name="percent3", precision=5)
    public BigDecimal getPercent3() {
        return this.percent3;
    }
    
    public void setPercent3(BigDecimal percent3) {
        this.percent3 = percent3;
    }
    
    @Column(name="relationshipcode3")
    public Integer getRelationshipcode3() {
        return this.relationshipcode3;
    }
    
    public void setRelationshipcode3(Integer relationshipcode3) {
        this.relationshipcode3 = relationshipcode3;
    }
    
    @Column(name="analist", length=10)
    public String getAnalist() {
        return this.analist;
    }
    
    public void setAnalist(String analist) {
        this.analist = analist;
    }
    
    @Column(name="prmiseno", length=12)
    public String getPrmiseno() {
        return this.prmiseno;
    }
    
    public void setPrmiseno(String prmiseno) {
        this.prmiseno = prmiseno;
    }
    
    @Column(name="prmiseno2", length=12)
    public String getPrmiseno2() {
        return this.prmiseno2;
    }
    
    public void setPrmiseno2(String prmiseno2) {
        this.prmiseno2 = prmiseno2;
    }
    
    @Column(name="loantype", length=1)
    public String getLoantype() {
        return this.loantype;
    }
    
    public void setLoantype(String loantype) {
        this.loantype = loantype;
    }
    
    @Column(name="med", length=1)
    public String getMed() {
        return this.med;
    }
    
    public void setMed(String med) {
        this.med = med;
    }
    
    @Column(name="reserve", length=1)
    public String getReserve() {
        return this.reserve;
    }
    
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }




}


