package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgclaimId generated by hbm2java
 */
@Embeddable
public class MgclaimId  implements java.io.Serializable {


     private String certno;
     private String accidentdate;
     private String receivedate;
     private String claimtype;
     private String referenceno;

    public MgclaimId() {
    }

    public MgclaimId(String certno, String accidentdate, String receivedate, String claimtype, String referenceno) {
       this.certno = certno;
       this.accidentdate = accidentdate;
       this.receivedate = receivedate;
       this.claimtype = claimtype;
       this.referenceno = referenceno;
    }
   

    @Column(name="certno", nullable=false, length=8)
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="accidentdate", nullable=false, length=8)
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="receivedate", nullable=false, length=8)
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="claimtype", nullable=false, length=1)
    public String getClaimtype() {
        return this.claimtype;
    }
    
    public void setClaimtype(String claimtype) {
        this.claimtype = claimtype;
    }

    @Column(name="referenceno", nullable=false, length=10)
    public String getReferenceno() {
        return this.referenceno;
    }
    
    public void setReferenceno(String referenceno) {
        this.referenceno = referenceno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgclaimId) ) return false;
		 MgclaimId castOther = ( MgclaimId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getClaimtype()==castOther.getClaimtype()) || ( this.getClaimtype()!=null && castOther.getClaimtype()!=null && this.getClaimtype().equals(castOther.getClaimtype()) ) )
 && ( (this.getReferenceno()==castOther.getReferenceno()) || ( this.getReferenceno()!=null && castOther.getReferenceno()!=null && this.getReferenceno().equals(castOther.getReferenceno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getClaimtype() == null ? 0 : this.getClaimtype().hashCode() );
         result = 37 * result + ( getReferenceno() == null ? 0 : this.getReferenceno().hashCode() );
         return result;
   }   


}


