package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgclaim generated by hbm2java
 */
@Entity
@Table(name="mgclaim"
)
public class Mgclaim  implements java.io.Serializable {


     private MgclaimId id;
     private String sectioncode;
     private String orderno;
     private String linkerno;
     private String okdate;
     private String policyno;

    public Mgclaim() {
    }

	
    public Mgclaim(MgclaimId id) {
        this.id = id;
    }
    public Mgclaim(MgclaimId id, String sectioncode, String orderno, String linkerno, String okdate, String policyno) {
       this.id = id;
       this.sectioncode = sectioncode;
       this.orderno = orderno;
       this.linkerno = linkerno;
       this.okdate = okdate;
       this.policyno = policyno;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate", nullable=false, length=8) ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate", nullable=false, length=8) ), 
        @AttributeOverride(name="claimtype", column=@Column(name="claimtype", nullable=false, length=1) ), 
        @AttributeOverride(name="referenceno", column=@Column(name="referenceno", nullable=false, length=10) ) } )
    public MgclaimId getId() {
        return this.id;
    }
    
    public void setId(MgclaimId id) {
        this.id = id;
    }
    
    @Column(name="sectioncode", length=2)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }
    
    @Column(name="orderno", length=8)
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    
    @Column(name="linkerno", length=7)
    public String getLinkerno() {
        return this.linkerno;
    }
    
    public void setLinkerno(String linkerno) {
        this.linkerno = linkerno;
    }
    
    @Column(name="okdate", length=8)
    public String getOkdate() {
        return this.okdate;
    }
    
    public void setOkdate(String okdate) {
        this.okdate = okdate;
    }
    
    @Column(name="policyno", length=4)
    public String getPolicyno() {
        return this.policyno;
    }
    
    public void setPolicyno(String policyno) {
        this.policyno = policyno;
    }




}


