package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mghis generated by hbm2java
 */
@Entity
@Table(name="mghis"
)
public class Mghis  implements java.io.Serializable {


     private MghisId id;
     private String remarkdate;
     private String remarkno;
     private String remark;
     private String employeeid;
     private String rectime;

    public Mghis() {
    }

	
    public Mghis(MghisId id) {
        this.id = id;
    }
    public Mghis(MghisId id, String remarkdate, String remarkno, String remark, String employeeid, String rectime) {
       this.id = id;
       this.remarkdate = remarkdate;
       this.remarkno = remarkno;
       this.remark = remark;
       this.employeeid = employeeid;
       this.rectime = rectime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate", nullable=false, length=8) ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate", nullable=false, length=8) ), 
        @AttributeOverride(name="claimtype", column=@Column(name="claimtype", nullable=false, length=1) ), 
        @AttributeOverride(name="seqno", column=@Column(name="seqno", nullable=false) ) } )
    public MghisId getId() {
        return this.id;
    }
    
    public void setId(MghisId id) {
        this.id = id;
    }
    
    @Column(name="remarkdate", length=8)
    public String getRemarkdate() {
        return this.remarkdate;
    }
    
    public void setRemarkdate(String remarkdate) {
        this.remarkdate = remarkdate;
    }
    
    @Column(name="remarkno", length=2)
    public String getRemarkno() {
        return this.remarkno;
    }
    
    public void setRemarkno(String remarkno) {
        this.remarkno = remarkno;
    }
    
    @Column(name="remark", length=100)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="employeeid", length=7)
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }
    
    @Column(name="rectime", length=6)
    public String getRectime() {
        return this.rectime;
    }
    
    public void setRectime(String rectime) {
        this.rectime = rectime;
    }




}


