package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MginterestId generated by hbm2java
 */
@Embeddable
public class MginterestId  implements java.io.Serializable {


     private String certno;
     private String accidentdate;
     private String receivedate;
     private String ridertype;
     private String paytype;

    public MginterestId() {
    }

    public MginterestId(String certno, String accidentdate, String receivedate, String ridertype, String paytype) {
       this.certno = certno;
       this.accidentdate = accidentdate;
       this.receivedate = receivedate;
       this.ridertype = ridertype;
       this.paytype = paytype;
    }
   

    @Column(name="certno", nullable=false, length=8)
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="accidentdate", nullable=false, length=8)
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="receivedate", nullable=false, length=8)
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="ridertype", nullable=false, length=3)
    public String getRidertype() {
        return this.ridertype;
    }
    
    public void setRidertype(String ridertype) {
        this.ridertype = ridertype;
    }

    @Column(name="paytype", nullable=false, length=1)
    public String getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MginterestId) ) return false;
		 MginterestId castOther = ( MginterestId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getRidertype()==castOther.getRidertype()) || ( this.getRidertype()!=null && castOther.getRidertype()!=null && this.getRidertype().equals(castOther.getRidertype()) ) )
 && ( (this.getPaytype()==castOther.getPaytype()) || ( this.getPaytype()!=null && castOther.getPaytype()!=null && this.getPaytype().equals(castOther.getPaytype()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getRidertype() == null ? 0 : this.getRidertype().hashCode() );
         result = 37 * result + ( getPaytype() == null ? 0 : this.getPaytype().hashCode() );
         return result;
   }   


}


