package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mginterest generated by hbm2java
 */
@Entity
@Table(name="mginterest"
)
public class Mginterest  implements java.io.Serializable {


     private MginterestId id;
     private String startdate;
     private String enddate;
     private String day;
     private BigDecimal payamount;
     private BigDecimal interestamount;

    public Mginterest() {
    }

	
    public Mginterest(MginterestId id) {
        this.id = id;
    }
    public Mginterest(MginterestId id, String startdate, String enddate, String day, BigDecimal payamount, BigDecimal interestamount) {
       this.id = id;
       this.startdate = startdate;
       this.enddate = enddate;
       this.day = day;
       this.payamount = payamount;
       this.interestamount = interestamount;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate", nullable=false, length=8) ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate", nullable=false, length=8) ), 
        @AttributeOverride(name="ridertype", column=@Column(name="ridertype", nullable=false, length=3) ), 
        @AttributeOverride(name="paytype", column=@Column(name="paytype", nullable=false, length=1) ) } )
    public MginterestId getId() {
        return this.id;
    }
    
    public void setId(MginterestId id) {
        this.id = id;
    }
    
    @Column(name="startdate", length=8)
    public String getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }
    
    @Column(name="enddate", length=8)
    public String getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }
    
    @Column(name="day", length=4)
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }
    
    @Column(name="payamount", precision=12)
    public BigDecimal getPayamount() {
        return this.payamount;
    }
    
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }
    
    @Column(name="interestamount", precision=11)
    public BigDecimal getInterestamount() {
        return this.interestamount;
    }
    
    public void setInterestamount(BigDecimal interestamount) {
        this.interestamount = interestamount;
    }




}


