package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mginsmemo generated by hbm2java
 */
@Entity
@Table(name="mginsmemo"
)
public class Mginsmemo  implements java.io.Serializable {


     private MginsmemoId id;
     private String detail1;
     private String detail2;
     private String savedate;

    public Mginsmemo() {
    }

	
    public Mginsmemo(MginsmemoId id) {
        this.id = id;
    }
    public Mginsmemo(MginsmemoId id, String detail1, String detail2, String savedate) {
       this.id = id;
       this.detail1 = detail1;
       this.detail2 = detail2;
       this.savedate = savedate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate", nullable=false, length=8) ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate", nullable=false, length=8) ), 
        @AttributeOverride(name="memocode", column=@Column(name="memocode", nullable=false, length=3) ) } )
    public MginsmemoId getId() {
        return this.id;
    }
    
    public void setId(MginsmemoId id) {
        this.id = id;
    }
    
    @Column(name="detail1", length=100)
    public String getDetail1() {
        return this.detail1;
    }
    
    public void setDetail1(String detail1) {
        this.detail1 = detail1;
    }
    
    @Column(name="detail2", length=100)
    public String getDetail2() {
        return this.detail2;
    }
    
    public void setDetail2(String detail2) {
        this.detail2 = detail2;
    }
    
    @Column(name="savedate", length=8)
    public String getSavedate() {
        return this.savedate;
    }
    
    public void setSavedate(String savedate) {
        this.savedate = savedate;
    }




}


