package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgorder generated by hbm2java
 */
@Entity
@Table(name="mgorder"
)
public class Mgorder  implements java.io.Serializable {


     private MgorderId id;
     private String receivetime;
     private String causecode;
     private String causedetail;
     private String receiverid;
     private String considerid;
     private String admitdate;
     private String admitflag;
     private String billingorderno;
     private String interimflag;
     private String hospitalcode;
     private String receivedocdate;

    public Mgorder() {
    }

	
    public Mgorder(MgorderId id) {
        this.id = id;
    }
    public Mgorder(MgorderId id, String receivetime, String causecode, String causedetail, String receiverid, String considerid, String admitdate, String admitflag, String billingorderno, String interimflag, String hospitalcode, String receivedocdate) {
       this.id = id;
       this.receivetime = receivetime;
       this.causecode = causecode;
       this.causedetail = causedetail;
       this.receiverid = receiverid;
       this.considerid = considerid;
       this.admitdate = admitdate;
       this.admitflag = admitflag;
       this.billingorderno = billingorderno;
       this.interimflag = interimflag;
       this.hospitalcode = hospitalcode;
       this.receivedocdate = receivedocdate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="sectioncode", column=@Column(name="sectioncode", nullable=false, length=2) ), 
        @AttributeOverride(name="orderno", column=@Column(name="orderno", nullable=false, length=8) ) } )
    public MgorderId getId() {
        return this.id;
    }
    
    public void setId(MgorderId id) {
        this.id = id;
    }
    
    @Column(name="receivetime", length=6)
    public String getReceivetime() {
        return this.receivetime;
    }
    
    public void setReceivetime(String receivetime) {
        this.receivetime = receivetime;
    }
    
    @Column(name="causecode", length=6)
    public String getCausecode() {
        return this.causecode;
    }
    
    public void setCausecode(String causecode) {
        this.causecode = causecode;
    }
    
    @Column(name="causedetail", length=50)
    public String getCausedetail() {
        return this.causedetail;
    }
    
    public void setCausedetail(String causedetail) {
        this.causedetail = causedetail;
    }
    
    @Column(name="receiverid", length=7)
    public String getReceiverid() {
        return this.receiverid;
    }
    
    public void setReceiverid(String receiverid) {
        this.receiverid = receiverid;
    }
    
    @Column(name="considerid", length=7)
    public String getConsiderid() {
        return this.considerid;
    }
    
    public void setConsiderid(String considerid) {
        this.considerid = considerid;
    }
    
    @Column(name="admitdate", length=8)
    public String getAdmitdate() {
        return this.admitdate;
    }
    
    public void setAdmitdate(String admitdate) {
        this.admitdate = admitdate;
    }
    
    @Column(name="admitflag", length=1)
    public String getAdmitflag() {
        return this.admitflag;
    }
    
    public void setAdmitflag(String admitflag) {
        this.admitflag = admitflag;
    }
    
    @Column(name="billingorderno", length=10)
    public String getBillingorderno() {
        return this.billingorderno;
    }
    
    public void setBillingorderno(String billingorderno) {
        this.billingorderno = billingorderno;
    }
    
    @Column(name="interimflag", length=1)
    public String getInterimflag() {
        return this.interimflag;
    }
    
    public void setInterimflag(String interimflag) {
        this.interimflag = interimflag;
    }
    
    @Column(name="hospitalcode", length=4)
    public String getHospitalcode() {
        return this.hospitalcode;
    }
    
    public void setHospitalcode(String hospitalcode) {
        this.hospitalcode = hospitalcode;
    }
    
    @Column(name="receivedocdate", length=8)
    public String getReceivedocdate() {
        return this.receivedocdate;
    }
    
    public void setReceivedocdate(String receivedocdate) {
        this.receivedocdate = receivedocdate;
    }




}


