package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgorderId generated by hbm2java
 */
@Embeddable
public class MgorderId  implements java.io.Serializable {


     private String sectioncode;
     private String orderno;

    public MgorderId() {
    }

    public MgorderId(String sectioncode, String orderno) {
       this.sectioncode = sectioncode;
       this.orderno = orderno;
    }
   

    @Column(name="sectioncode", nullable=false, length=2)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @Column(name="orderno", nullable=false, length=8)
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgorderId) ) return false;
		 MgorderId castOther = ( MgorderId ) other; 
         
		 return ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) )
 && ( (this.getOrderno()==castOther.getOrderno()) || ( this.getOrderno()!=null && castOther.getOrderno()!=null && this.getOrderno().equals(castOther.getOrderno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         result = 37 * result + ( getOrderno() == null ? 0 : this.getOrderno().hashCode() );
         return result;
   }   


}


