package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgpay generated by hbm2java
 */
@Entity
@Table(name="mgpay"
)
public class Mgpay  implements java.io.Serializable {


     private MgpayId id;
     private String policystatus;
     private String policystatusdate;
     private String policystatus2;
     private String policystatusdate2;
     private String branchcode;
     private String servicebranch;
     private String claimtype;
     private String paytype;
     private Integer proofinsuredage;
     private String disabilitytype;
     private String disnumber;
     private String payrate;
     private Integer payamount;
     private Integer accdamount;
     private Integer surrenderamount;
     private Integer returnamount;
     private Integer deductamount;
     private String claimokdate;
     private String claimpaydate;
     private String allowtype;

    public Mgpay() {
    }

	
    public Mgpay(MgpayId id) {
        this.id = id;
    }
    public Mgpay(MgpayId id, String policystatus, String policystatusdate, String policystatus2, String policystatusdate2, String branchcode, String servicebranch, String claimtype, String paytype, Integer proofinsuredage, String disabilitytype, String disnumber, String payrate, Integer payamount, Integer accdamount, Integer surrenderamount, Integer returnamount, Integer deductamount, String claimokdate, String claimpaydate, String allowtype) {
       this.id = id;
       this.policystatus = policystatus;
       this.policystatusdate = policystatusdate;
       this.policystatus2 = policystatus2;
       this.policystatusdate2 = policystatusdate2;
       this.branchcode = branchcode;
       this.servicebranch = servicebranch;
       this.claimtype = claimtype;
       this.paytype = paytype;
       this.proofinsuredage = proofinsuredage;
       this.disabilitytype = disabilitytype;
       this.disnumber = disnumber;
       this.payrate = payrate;
       this.payamount = payamount;
       this.accdamount = accdamount;
       this.surrenderamount = surrenderamount;
       this.returnamount = returnamount;
       this.deductamount = deductamount;
       this.claimokdate = claimokdate;
       this.claimpaydate = claimpaydate;
       this.allowtype = allowtype;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate", nullable=false, length=8) ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate", nullable=false, length=8) ), 
        @AttributeOverride(name="sectioncode", column=@Column(name="sectioncode", nullable=false, length=2) ), 
        @AttributeOverride(name="orderno", column=@Column(name="orderno", nullable=false, length=8) ) } )
    public MgpayId getId() {
        return this.id;
    }
    
    public void setId(MgpayId id) {
        this.id = id;
    }
    
    @Column(name="policystatus", length=1)
    public String getPolicystatus() {
        return this.policystatus;
    }
    
    public void setPolicystatus(String policystatus) {
        this.policystatus = policystatus;
    }
    
    @Column(name="policystatusdate", length=8)
    public String getPolicystatusdate() {
        return this.policystatusdate;
    }
    
    public void setPolicystatusdate(String policystatusdate) {
        this.policystatusdate = policystatusdate;
    }
    
    @Column(name="policystatus2", length=1)
    public String getPolicystatus2() {
        return this.policystatus2;
    }
    
    public void setPolicystatus2(String policystatus2) {
        this.policystatus2 = policystatus2;
    }
    
    @Column(name="policystatusdate2", length=8)
    public String getPolicystatusdate2() {
        return this.policystatusdate2;
    }
    
    public void setPolicystatusdate2(String policystatusdate2) {
        this.policystatusdate2 = policystatusdate2;
    }
    
    @Column(name="branchcode", length=3)
    public String getBranchcode() {
        return this.branchcode;
    }
    
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }
    
    @Column(name="servicebranch", length=3)
    public String getServicebranch() {
        return this.servicebranch;
    }
    
    public void setServicebranch(String servicebranch) {
        this.servicebranch = servicebranch;
    }
    
    @Column(name="claimtype", length=1)
    public String getClaimtype() {
        return this.claimtype;
    }
    
    public void setClaimtype(String claimtype) {
        this.claimtype = claimtype;
    }
    
    @Column(name="paytype", length=1)
    public String getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }
    
    @Column(name="proofinsuredage")
    public Integer getProofinsuredage() {
        return this.proofinsuredage;
    }
    
    public void setProofinsuredage(Integer proofinsuredage) {
        this.proofinsuredage = proofinsuredage;
    }
    
    @Column(name="disabilitytype", length=1)
    public String getDisabilitytype() {
        return this.disabilitytype;
    }
    
    public void setDisabilitytype(String disabilitytype) {
        this.disabilitytype = disabilitytype;
    }
    
    @Column(name="disnumber", length=1)
    public String getDisnumber() {
        return this.disnumber;
    }
    
    public void setDisnumber(String disnumber) {
        this.disnumber = disnumber;
    }
    
    @Column(name="payrate", length=3)
    public String getPayrate() {
        return this.payrate;
    }
    
    public void setPayrate(String payrate) {
        this.payrate = payrate;
    }
    
    @Column(name="payamount")
    public Integer getPayamount() {
        return this.payamount;
    }
    
    public void setPayamount(Integer payamount) {
        this.payamount = payamount;
    }
    
    @Column(name="accdamount")
    public Integer getAccdamount() {
        return this.accdamount;
    }
    
    public void setAccdamount(Integer accdamount) {
        this.accdamount = accdamount;
    }
    
    @Column(name="surrenderamount")
    public Integer getSurrenderamount() {
        return this.surrenderamount;
    }
    
    public void setSurrenderamount(Integer surrenderamount) {
        this.surrenderamount = surrenderamount;
    }
    
    @Column(name="returnamount")
    public Integer getReturnamount() {
        return this.returnamount;
    }
    
    public void setReturnamount(Integer returnamount) {
        this.returnamount = returnamount;
    }
    
    @Column(name="deductamount")
    public Integer getDeductamount() {
        return this.deductamount;
    }
    
    public void setDeductamount(Integer deductamount) {
        this.deductamount = deductamount;
    }
    
    @Column(name="claimokdate", length=8)
    public String getClaimokdate() {
        return this.claimokdate;
    }
    
    public void setClaimokdate(String claimokdate) {
        this.claimokdate = claimokdate;
    }
    
    @Column(name="claimpaydate", length=8)
    public String getClaimpaydate() {
        return this.claimpaydate;
    }
    
    public void setClaimpaydate(String claimpaydate) {
        this.claimpaydate = claimpaydate;
    }
    
    @Column(name="allowtype", length=1)
    public String getAllowtype() {
        return this.allowtype;
    }
    
    public void setAllowtype(String allowtype) {
        this.allowtype = allowtype;
    }




}


