package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgpayId generated by hbm2java
 */
@Embeddable
public class MgpayId  implements java.io.Serializable {


     private String certno;
     private String receivedate;
     private String accidentdate;
     private String sectioncode;
     private String orderno;

    public MgpayId() {
    }

    public MgpayId(String certno, String receivedate, String accidentdate, String sectioncode, String orderno) {
       this.certno = certno;
       this.receivedate = receivedate;
       this.accidentdate = accidentdate;
       this.sectioncode = sectioncode;
       this.orderno = orderno;
    }
   

    @Column(name="certno", nullable=false, length=8)
    public String getCertno() {
        return this.certno;
    }
    
    public void setCertno(String certno) {
        this.certno = certno;
    }

    @Column(name="receivedate", nullable=false, length=8)
    public String getReceivedate() {
        return this.receivedate;
    }
    
    public void setReceivedate(String receivedate) {
        this.receivedate = receivedate;
    }

    @Column(name="accidentdate", nullable=false, length=8)
    public String getAccidentdate() {
        return this.accidentdate;
    }
    
    public void setAccidentdate(String accidentdate) {
        this.accidentdate = accidentdate;
    }

    @Column(name="sectioncode", nullable=false, length=2)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    @Column(name="orderno", nullable=false, length=8)
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgpayId) ) return false;
		 MgpayId castOther = ( MgpayId ) other; 
         
		 return ( (this.getCertno()==castOther.getCertno()) || ( this.getCertno()!=null && castOther.getCertno()!=null && this.getCertno().equals(castOther.getCertno()) ) )
 && ( (this.getReceivedate()==castOther.getReceivedate()) || ( this.getReceivedate()!=null && castOther.getReceivedate()!=null && this.getReceivedate().equals(castOther.getReceivedate()) ) )
 && ( (this.getAccidentdate()==castOther.getAccidentdate()) || ( this.getAccidentdate()!=null && castOther.getAccidentdate()!=null && this.getAccidentdate().equals(castOther.getAccidentdate()) ) )
 && ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) )
 && ( (this.getOrderno()==castOther.getOrderno()) || ( this.getOrderno()!=null && castOther.getOrderno()!=null && this.getOrderno().equals(castOther.getOrderno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCertno() == null ? 0 : this.getCertno().hashCode() );
         result = 37 * result + ( getReceivedate() == null ? 0 : this.getReceivedate().hashCode() );
         result = 37 * result + ( getAccidentdate() == null ? 0 : this.getAccidentdate().hashCode() );
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         result = 37 * result + ( getOrderno() == null ? 0 : this.getOrderno().hashCode() );
         return result;
   }   


}


