package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgpayrider generated by hbm2java
 */
@Entity
@Table(name="mgpayrider"
)
public class Mgpayrider  implements java.io.Serializable {


     private MgpayriderId id;
     private String policystatus;
     private String policystatusdate;
     private String policystatus2;
     private String policystatusdate2;
     private String branchcode;
     private String servicebranch;
     private String amestartdate;
     private Short ameday;
     private BigDecimal ameexpense;
     private BigDecimal amepayment;
     private Integer tdday;
     private String tdstartdate;
     private BigDecimal tdpayment;
     private BigDecimal returnamount;
     private BigDecimal deductamount;
     private String voiddate;
     private String claimokdate;
     private String claimpaydate;

    public Mgpayrider() {
    }

	
    public Mgpayrider(MgpayriderId id) {
        this.id = id;
    }
    public Mgpayrider(MgpayriderId id, String policystatus, String policystatusdate, String policystatus2, String policystatusdate2, String branchcode, String servicebranch, String amestartdate, Short ameday, BigDecimal ameexpense, BigDecimal amepayment, Integer tdday, String tdstartdate, BigDecimal tdpayment, BigDecimal returnamount, BigDecimal deductamount, String voiddate, String claimokdate, String claimpaydate) {
       this.id = id;
       this.policystatus = policystatus;
       this.policystatusdate = policystatusdate;
       this.policystatus2 = policystatus2;
       this.policystatusdate2 = policystatusdate2;
       this.branchcode = branchcode;
       this.servicebranch = servicebranch;
       this.amestartdate = amestartdate;
       this.ameday = ameday;
       this.ameexpense = ameexpense;
       this.amepayment = amepayment;
       this.tdday = tdday;
       this.tdstartdate = tdstartdate;
       this.tdpayment = tdpayment;
       this.returnamount = returnamount;
       this.deductamount = deductamount;
       this.voiddate = voiddate;
       this.claimokdate = claimokdate;
       this.claimpaydate = claimpaydate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate", nullable=false, length=8) ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate", nullable=false, length=8) ), 
        @AttributeOverride(name="sectioncode", column=@Column(name="sectioncode", nullable=false, length=2) ), 
        @AttributeOverride(name="orderno", column=@Column(name="orderno", nullable=false, length=8) ) } )
    public MgpayriderId getId() {
        return this.id;
    }
    
    public void setId(MgpayriderId id) {
        this.id = id;
    }
    
    @Column(name="policystatus", length=1)
    public String getPolicystatus() {
        return this.policystatus;
    }
    
    public void setPolicystatus(String policystatus) {
        this.policystatus = policystatus;
    }
    
    @Column(name="policystatusdate", length=8)
    public String getPolicystatusdate() {
        return this.policystatusdate;
    }
    
    public void setPolicystatusdate(String policystatusdate) {
        this.policystatusdate = policystatusdate;
    }
    
    @Column(name="policystatus2", length=1)
    public String getPolicystatus2() {
        return this.policystatus2;
    }
    
    public void setPolicystatus2(String policystatus2) {
        this.policystatus2 = policystatus2;
    }
    
    @Column(name="policystatusdate2", length=8)
    public String getPolicystatusdate2() {
        return this.policystatusdate2;
    }
    
    public void setPolicystatusdate2(String policystatusdate2) {
        this.policystatusdate2 = policystatusdate2;
    }
    
    @Column(name="branchcode", length=3)
    public String getBranchcode() {
        return this.branchcode;
    }
    
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }
    
    @Column(name="servicebranch", length=3)
    public String getServicebranch() {
        return this.servicebranch;
    }
    
    public void setServicebranch(String servicebranch) {
        this.servicebranch = servicebranch;
    }
    
    @Column(name="amestartdate", length=8)
    public String getAmestartdate() {
        return this.amestartdate;
    }
    
    public void setAmestartdate(String amestartdate) {
        this.amestartdate = amestartdate;
    }
    
    @Column(name="ameday", precision=3, scale=0)
    public Short getAmeday() {
        return this.ameday;
    }
    
    public void setAmeday(Short ameday) {
        this.ameday = ameday;
    }
    
    @Column(name="ameexpense", precision=9)
    public BigDecimal getAmeexpense() {
        return this.ameexpense;
    }
    
    public void setAmeexpense(BigDecimal ameexpense) {
        this.ameexpense = ameexpense;
    }
    
    @Column(name="amepayment", precision=9)
    public BigDecimal getAmepayment() {
        return this.amepayment;
    }
    
    public void setAmepayment(BigDecimal amepayment) {
        this.amepayment = amepayment;
    }
    
    @Column(name="tdday")
    public Integer getTdday() {
        return this.tdday;
    }
    
    public void setTdday(Integer tdday) {
        this.tdday = tdday;
    }
    
    @Column(name="tdstartdate", length=8)
    public String getTdstartdate() {
        return this.tdstartdate;
    }
    
    public void setTdstartdate(String tdstartdate) {
        this.tdstartdate = tdstartdate;
    }
    
    @Column(name="tdpayment", precision=9)
    public BigDecimal getTdpayment() {
        return this.tdpayment;
    }
    
    public void setTdpayment(BigDecimal tdpayment) {
        this.tdpayment = tdpayment;
    }
    
    @Column(name="returnamount", precision=12)
    public BigDecimal getReturnamount() {
        return this.returnamount;
    }
    
    public void setReturnamount(BigDecimal returnamount) {
        this.returnamount = returnamount;
    }
    
    @Column(name="deductamount", precision=12)
    public BigDecimal getDeductamount() {
        return this.deductamount;
    }
    
    public void setDeductamount(BigDecimal deductamount) {
        this.deductamount = deductamount;
    }
    
    @Column(name="voiddate", length=8)
    public String getVoiddate() {
        return this.voiddate;
    }
    
    public void setVoiddate(String voiddate) {
        this.voiddate = voiddate;
    }
    
    @Column(name="claimokdate", length=8)
    public String getClaimokdate() {
        return this.claimokdate;
    }
    
    public void setClaimokdate(String claimokdate) {
        this.claimokdate = claimokdate;
    }
    
    @Column(name="claimpaydate", length=8)
    public String getClaimpaydate() {
        return this.claimpaydate;
    }
    
    public void setClaimpaydate(String claimpaydate) {
        this.claimpaydate = claimpaydate;
    }




}


