package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Mgreceiver generated by hbm2java
 */
@Entity
@Table(name="mgreceiver"
)
public class Mgreceiver  implements java.io.Serializable {


     private MgreceiverId id;
     private String prename;
     private String firstname;
     private String lastname;
     private String type;
     private BigDecimal payamount;
     private String address;
     private String tumbon;
     private String zipcode;
     private String mobilephone;
     private String citizenid;
     private String paytype;
     private String banktype;
     private String bankcode;
     private String bankbranch;
     private String bankaccount;
     private String guardianbeneficiary;
     private String ispay;
     private String haveindicia;
     private String countrycode;
     private String claimpaydate;
     private String bookstatus;
     private String chqdate;
     private String chqno;
     private String docno;
     private String isbeneficiarykilled;
     private String birthdate;

    public Mgreceiver() {
    }

	
    public Mgreceiver(MgreceiverId id) {
        this.id = id;
    }
    public Mgreceiver(MgreceiverId id, String prename, String firstname, String lastname, String type, BigDecimal payamount, String address, String tumbon, String zipcode, String mobilephone, String citizenid, String paytype, String banktype, String bankcode, String bankbranch, String bankaccount, String guardianbeneficiary, String ispay, String haveindicia, String countrycode, String claimpaydate, String bookstatus, String chqdate, String chqno, String docno, String isbeneficiarykilled, String birthdate) {
       this.id = id;
       this.prename = prename;
       this.firstname = firstname;
       this.lastname = lastname;
       this.type = type;
       this.payamount = payamount;
       this.address = address;
       this.tumbon = tumbon;
       this.zipcode = zipcode;
       this.mobilephone = mobilephone;
       this.citizenid = citizenid;
       this.paytype = paytype;
       this.banktype = banktype;
       this.bankcode = bankcode;
       this.bankbranch = bankbranch;
       this.bankaccount = bankaccount;
       this.guardianbeneficiary = guardianbeneficiary;
       this.ispay = ispay;
       this.haveindicia = haveindicia;
       this.countrycode = countrycode;
       this.claimpaydate = claimpaydate;
       this.bookstatus = bookstatus;
       this.chqdate = chqdate;
       this.chqno = chqno;
       this.docno = docno;
       this.isbeneficiarykilled = isbeneficiarykilled;
       this.birthdate = birthdate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="certno", column=@Column(name="certno", nullable=false, length=8) ), 
        @AttributeOverride(name="accidentdate", column=@Column(name="accidentdate", nullable=false, length=8) ), 
        @AttributeOverride(name="receivedate", column=@Column(name="receivedate", nullable=false, length=8) ), 
        @AttributeOverride(name="seqno", column=@Column(name="seqno", nullable=false) ) } )
    public MgreceiverId getId() {
        return this.id;
    }
    
    public void setId(MgreceiverId id) {
        this.id = id;
    }
    
    @Column(name="prename", length=30)
    public String getPrename() {
        return this.prename;
    }
    
    public void setPrename(String prename) {
        this.prename = prename;
    }
    
    @Column(name="firstname", length=60)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="lastname", length=60)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
    @Column(name="type", length=1)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="payamount", precision=12)
    public BigDecimal getPayamount() {
        return this.payamount;
    }
    
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }
    
    @Column(name="address", length=128)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="tumbon", length=5)
    public String getTumbon() {
        return this.tumbon;
    }
    
    public void setTumbon(String tumbon) {
        this.tumbon = tumbon;
    }
    
    @Column(name="zipcode", length=5)
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    
    @Column(name="mobilephone", length=10)
    public String getMobilephone() {
        return this.mobilephone;
    }
    
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }
    
    @Column(name="citizenid", length=13)
    public String getCitizenid() {
        return this.citizenid;
    }
    
    public void setCitizenid(String citizenid) {
        this.citizenid = citizenid;
    }
    
    @Column(name="paytype", length=1)
    public String getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }
    
    @Column(name="banktype", length=1)
    public String getBanktype() {
        return this.banktype;
    }
    
    public void setBanktype(String banktype) {
        this.banktype = banktype;
    }
    
    @Column(name="bankcode", length=10)
    public String getBankcode() {
        return this.bankcode;
    }
    
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }
    
    @Column(name="bankbranch", length=35)
    public String getBankbranch() {
        return this.bankbranch;
    }
    
    public void setBankbranch(String bankbranch) {
        this.bankbranch = bankbranch;
    }
    
    @Column(name="bankaccount", length=15)
    public String getBankaccount() {
        return this.bankaccount;
    }
    
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }
    
    @Column(name="guardianbeneficiary", length=80)
    public String getGuardianbeneficiary() {
        return this.guardianbeneficiary;
    }
    
    public void setGuardianbeneficiary(String guardianbeneficiary) {
        this.guardianbeneficiary = guardianbeneficiary;
    }
    
    @Column(name="ispay", length=1)
    public String getIspay() {
        return this.ispay;
    }
    
    public void setIspay(String ispay) {
        this.ispay = ispay;
    }
    
    @Column(name="haveindicia", length=1)
    public String getHaveindicia() {
        return this.haveindicia;
    }
    
    public void setHaveindicia(String haveindicia) {
        this.haveindicia = haveindicia;
    }
    
    @Column(name="countrycode", length=3)
    public String getCountrycode() {
        return this.countrycode;
    }
    
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode;
    }
    
    @Column(name="claimpaydate ", length=8)
    public String getClaimpaydate() {
        return this.claimpaydate;
    }
    
    public void setClaimpaydate(String claimpaydate) {
        this.claimpaydate = claimpaydate;
    }
    
    @Column(name="bookstatus", length=1)
    public String getBookstatus() {
        return this.bookstatus;
    }
    
    public void setBookstatus(String bookstatus) {
        this.bookstatus = bookstatus;
    }
    
    @Column(name="chqdate", length=8)
    public String getChqdate() {
        return this.chqdate;
    }
    
    public void setChqdate(String chqdate) {
        this.chqdate = chqdate;
    }
    
    @Column(name="chqno", length=10)
    public String getChqno() {
        return this.chqno;
    }
    
    public void setChqno(String chqno) {
        this.chqno = chqno;
    }
    
    @Column(name="docno", length=5)
    public String getDocno() {
        return this.docno;
    }
    
    public void setDocno(String docno) {
        this.docno = docno;
    }
    
    @Column(name="isbeneficiarykilled", length=1)
    public String getIsbeneficiarykilled() {
        return this.isbeneficiarykilled;
    }
    
    public void setIsbeneficiarykilled(String isbeneficiarykilled) {
        this.isbeneficiarykilled = isbeneficiarykilled;
    }
    
    @Column(name="birthdate", length=8)
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }




}


