package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Name generated by hbm2java
 */
@Entity
@Table(name="name"
)
public class Name  implements java.io.Serializable {


     private String nameid;
     private String personid;
     private String prename;
     private String firstname;
     private String lastname;
     private String startdate;

    public Name() {
    }

	
    public Name(String nameid) {
        this.nameid = nameid;
    }
    public Name(String nameid, String personid, String prename, String firstname, String lastname, String startdate) {
       this.nameid = nameid;
       this.personid = personid;
       this.prename = prename;
       this.firstname = firstname;
       this.lastname = lastname;
       this.startdate = startdate;
    }
   
     @Id 
    
    @Column(name="nameid", unique=true, nullable=false, length=13)
    public String getNameid() {
        return this.nameid;
    }
    
    public void setNameid(String nameid) {
        this.nameid = nameid;
    }
    
    @Column(name="personid", length=13)
    public String getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(String personid) {
        this.personid = personid;
    }
    
    @Column(name="prename", length=30)
    public String getPrename() {
        return this.prename;
    }
    
    public void setPrename(String prename) {
        this.prename = prename;
    }
    
    @Column(name="firstname", length=30)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    
    @Column(name="lastname", length=30)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
    @Column(name="startdate", length=8)
    public String getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(String startdate) {
        this.startdate = startdate;
    }




}


