package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonId generated by hbm2java
 */
@Embeddable
public class PersonId  implements java.io.Serializable {


     private String personid;
     private String referenceid;

    public PersonId() {
    }

    public PersonId(String personid, String referenceid) {
       this.personid = personid;
       this.referenceid = referenceid;
    }
   

    @Column(name="personid", nullable=false, length=13)
    public String getPersonid() {
        return this.personid;
    }
    
    public void setPersonid(String personid) {
        this.personid = personid;
    }

    @Column(name="referenceid", nullable=false, length=13)
    public String getReferenceid() {
        return this.referenceid;
    }
    
    public void setReferenceid(String referenceid) {
        this.referenceid = referenceid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonId) ) return false;
		 PersonId castOther = ( PersonId ) other; 
         
		 return ( (this.getPersonid()==castOther.getPersonid()) || ( this.getPersonid()!=null && castOther.getPersonid()!=null && this.getPersonid().equals(castOther.getPersonid()) ) )
 && ( (this.getReferenceid()==castOther.getReferenceid()) || ( this.getReferenceid()!=null && castOther.getReferenceid()!=null && this.getReferenceid().equals(castOther.getReferenceid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPersonid() == null ? 0 : this.getPersonid().hashCode() );
         result = 37 * result + ( getReferenceid() == null ? 0 : this.getReferenceid().hashCode() );
         return result;
   }   


}


