package th.co.ipassion.testtool.entity.tli;
// Generated Dec 29, 2017 9:15:36 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
)
public class Person  implements java.io.Serializable {


     private PersonId id;
     private String referencetype;
     private String birthdate;
     private String sex;
     private String customerid;
     private String bluecard;
     private String reserve;

    public Person() {
    }

	
    public Person(PersonId id) {
        this.id = id;
    }
    public Person(PersonId id, String referencetype, String birthdate, String sex, String customerid, String bluecard, String reserve) {
       this.id = id;
       this.referencetype = referencetype;
       this.birthdate = birthdate;
       this.sex = sex;
       this.customerid = customerid;
       this.bluecard = bluecard;
       this.reserve = reserve;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="personid", column=@Column(name="personid", nullable=false, length=13) ), 
        @AttributeOverride(name="referenceid", column=@Column(name="referenceid", nullable=false, length=13) ) } )
    public PersonId getId() {
        return this.id;
    }
    
    public void setId(PersonId id) {
        this.id = id;
    }
    
    @Column(name="referencetype", length=2)
    public String getReferencetype() {
        return this.referencetype;
    }
    
    public void setReferencetype(String referencetype) {
        this.referencetype = referencetype;
    }
    
    @Column(name="birthdate", length=8)
    public String getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }
    
    @Column(name="sex", length=1)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="customerid", length=13)
    public String getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }
    
    @Column(name="bluecard", length=1)
    public String getBluecard() {
        return this.bluecard;
    }
    
    public void setBluecard(String bluecard) {
        this.bluecard = bluecard;
    }
    
    @Column(name="reserve", length=6)
    public String getReserve() {
        return this.reserve;
    }
    
    public void setReserve(String reserve) {
        this.reserve = reserve;
    }




}


